// Block D — lib/staffProfileShared.ts and lib/staffProfile.ts, every branch, against the REAL files.
import { chk, assert, eq, throws } from "./core.mjs";
import * as P from "@/lib/staffProfileShared";
import * as SP from "@/lib/staffProfile";

const S = "lib/staffProfileShared.ts", SV = "lib/staffProfile.ts", node = "node: the real export";
const K = (f, c, h, fn) => chk(f, c, h, fn);
const mp = (cur, patch, fields = P.PROFILE_FIELDS) => P.mergeProfilePatch(cur, patch, fields);

await K(S, "PROFILE_ROLES owner · manager · tablet; hasProfile true for exactly those (R7)", node, () => { eq([...P.PROFILE_ROLES], ["owner", "manager", "tablet"]); eq(["owner", "manager", "tablet", "kitchen", "admin", ""].map(P.hasProfile), [true, true, true, false, false, false]); });
await K(S, "the three pay powers' names", node, () => eq([P.POWER_SEE_PAY, P.POWER_RECORD_PAY, P.POWER_EDIT_PROFILE], ["see_staff_pay", "record_staff_payment", "edit_staff_profiles"]));
await K(S, "ABSENT_ON_PAY_POWERS: record + edit, never see-pay", node, () => { eq([...P.ABSENT_ON_PAY_POWERS].sort(), ["edit_staff_profiles", "record_staff_payment"]); assert(!P.ABSENT_ON_PAY_POWERS.has("see_staff_pay")); });
await K(S, "SELF_PROFILE_FIELDS is PROFILE_FIELDS minus the four owner-held fields, in the same order", node, () => eq([...P.SELF_PROFILE_FIELDS], P.PROFILE_FIELDS.filter((f) => !["id_type", "id_last4", "id_verified", "notes"].includes(f))));
await K(S, "JOB_COLUMNS and PAY_COLUMNS are the columns the docs name", node, () => { eq([...P.JOB_COLUMNS], ["joined_on", "left_on", "designation", "employment_type", "shift_label", "weekly_off"]); eq([...P.PAY_COLUMNS], ["pay_type", "pay_amount", "pay_day", "pay_mode", "pay_extras"]); });
await K(S, "the enum lists", node, () => { eq([...P.PAY_TYPES], ["monthly", "daily", "hourly", "per_shift"]); eq([...P.EMPLOYMENT_TYPES], ["full_time", "part_time", "trial", "casual"]); eq([...P.PAY_MODES], ["cash", "upi", "bank"]); eq([...P.WEEK_DAYS], ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]); });
await K(S, "isPayKind: each kind yes; anything else (incl. a number, 'Salary') no", node, () => { assert(P.PAY_KINDS.every(P.isPayKind)); for (const v of ["Salary", 1, null, "", "gift"]) assert(!P.isPayKind(v), String(v)); });
await K(S, "isPayout: false only for a deduction", node, () => eq(P.PAY_KINDS.map(P.isPayout), [true, true, true, true, true, false]));

// completeness
const FULL = { phone: "9", profile: { full_name: "a", dob: "1990-01-01", email: "e", address: "a", city: "c", emg_name: "n", emg_phone: "9", id_type: "PAN", id_last4: "1234" }, joined_on: "2024-01-01", designation: "d", employment_type: "full_time", shift_label: "s", pay_type: "daily", pay_amount: 1 };
await K(S, "completeness: a full record 14/14, self 8/8, nothing missing", node, () => eq(P.completeness(FULL), { filled: 14, total: 14, selfFilled: 8, selfTotal: 8, missing: [] }));
await K(S, "completeness: empty → 0/14 and the fourteen missing labels in order", node, () => { const c = P.completeness({}); eq([c.filled, c.total], [0, 14]); eq(c.missing[0], "phone number"); eq(c.missing[13], "pay setup"); });
await K(S, "completeness: profile null is treated as {}", node, () => eq(P.completeness({ profile: null }).filled, 0));
await K(S, "completeness: { pay: false } drops pay setup from total AND missing; { pay: true } keeps it", node, () => { eq(P.completeness({}, { pay: false }).total, 13); assert(!P.completeness({}, { pay: false }).missing.includes("pay setup")); eq(P.completeness({}, { pay: true }).total, 14); });
await K(S, "completeness: selfFilled counts only the self fields that are filled", node, () => eq(P.completeness({ phone: "9", designation: "x" }).selfFilled, 1));
await K(S, "completeness: 0 and '0' count as filled; whitespace does not", node, () => { eq(P.completeness({ pay_type: "daily", pay_amount: "0" }).missing.includes("pay setup"), false); eq(P.completeness({ phone: "  " }).filled, 0); });

// mergeProfilePatch
await K(S, "mergeProfilePatch: a key not in the allowed list is ignored even if the patch has it", node, () => eq(mp({}, { notes: "x" }, P.SELF_PROFILE_FIELDS), {}));
await K(S, "mergeProfilePatch: a key absent from the patch leaves the stored one alone", node, () => eq(mp({ city: "A" }, { email: "e" }), { city: "A", email: "e" }));
await K(S, "mergeProfilePatch: current null/undefined is treated as {}", node, () => { eq(mp(null, { city: "A" }), { city: "A" }); eq(mp(undefined, {}), {}); });
await K(S, "mergeProfilePatch: id_verified true stores true; anything else clears", node, () => { eq(mp({}, { id_verified: true }), { id_verified: true }); for (const v of [false, "true", 1, null]) eq(mp({ id_verified: true }, { id_verified: v }), {}, String(v)); });
await K(S, "mergeProfilePatch: last-4 fields keep the LAST four digits; no digits clears", node, () => { eq(mp({}, { id_last4: "1234567" }).id_last4, "4567"); eq(mp({}, { bank_last4: "x9y" }).bank_last4, "9"); eq(mp({ bank_last4: "1" }, { bank_last4: "none" }), {}); });
await K(S, "mergeProfilePatch: a last-4 given a number is read as digits", node, () => eq(mp({}, { id_last4: 98765 }).id_last4, "8765"));
await K(S, "mergeProfilePatch: dob a real day kept; empty clears; a bad one keeps the stored value (item 3)", node, () => { eq(mp({}, { dob: "2000-02-29" }).dob, "2000-02-29"); eq(mp({ dob: "1990-01-01" }, { dob: "" }), {}); eq(mp({ dob: "1990-01-01" }, { dob: "1990-02-30" }).dob, "1990-01-01"); eq(mp({ dob: "1990-01-01" }, { dob: "01/01/1990" }).dob, "1990-01-01"); });
await K(S, "mergeProfilePatch: dob before 1900 or 2100-02-29 is not a real day here", node, () => { eq(mp({}, { dob: "1899-12-31" }), {}); eq(mp({}, { dob: "2100-02-29" }), {}); });
await K(S, "mergeProfilePatch: address and notes cap at 500, every other text field at 200", node, () => { eq(mp({}, { address: "a".repeat(600) }).address.length, 500); eq(mp({}, { notes: "n".repeat(600) }).notes.length, 500); eq(mp({}, { city: "c".repeat(600) }).city.length, 200); });
await K(S, "mergeProfilePatch: a boolean text value is stored as its word", node, () => eq(mp({}, { city: true }).city, "true"));
await K(S, "mergeProfilePatch: a non-text value (object, array, function) keeps the stored field (item 5)", node, () => { for (const v of [{ a: 1 }, ["x"], () => 1]) eq(mp({ city: "A" }, { city: v }), { city: "A" }, typeof v); });
await K(S, "mergeProfilePatch: an object value for a last-4 or dob also keeps the stored field", node, () => { eq(mp({ id_last4: "1111" }, { id_last4: { x: 1 } }).id_last4, "1111"); eq(mp({ dob: "1990-01-01" }, { dob: ["2000-01-01"] }).dob, "1990-01-01"); });

// jobPatchFrom
await K(S, "jobPatchFrom({}) is {}", node, () => eq(P.jobPatchFrom({}), {}));
await K(S, "jobPatchFrom: real joining/leaving dates kept; '' and null clear", node, () => { eq(P.jobPatchFrom({ joined_on: "2025-12-31", left_on: null }), { joined_on: "2025-12-31", left_on: null }); eq(P.jobPatchFrom({ joined_on: "  " }).joined_on, null); });
await K(S, "jobPatchFrom: an impossible or mis-shaped date is refused with the field named", node, () => { throws(() => P.jobPatchFrom({ joined_on: "2025-02-29" }), /joining date isn't a real date/); throws(() => P.jobPatchFrom({ left_on: "31-12-2025" }), /leaving date isn't a real date/); });
await K(S, "jobPatchFrom: designation 80 · shift 80 · pay day 40 characters, trimmed", node, () => { const o = P.jobPatchFrom({ designation: " " + "d".repeat(100), shift_label: "s".repeat(100), pay_day: "p".repeat(100) }); eq([o.designation.length, o.shift_label.length, o.pay_day.length], [80, 80, 40]); });
await K(S, "jobPatchFrom: a non-text designation / shift / pay day is refused in words (item 5)", node, () => { throws(() => P.jobPatchFrom({ designation: { a: 1 } }), /designation isn't plain text/); throws(() => P.jobPatchFrom({ shift_label: [1] }), /shift name isn't plain text/); throws(() => P.jobPatchFrom({ pay_day: {} }), /pay day isn't plain text/); });
await K(S, "jobPatchFrom: an enum given '' clears it (null); an unknown value is refused", node, () => { eq(P.jobPatchFrom({ employment_type: "", pay_type: "", pay_mode: "" }), { employment_type: null, pay_type: null, pay_mode: null }); throws(() => P.jobPatchFrom({ pay_type: "weekly" }), /Unknown pay type/); throws(() => P.jobPatchFrom({ pay_mode: "card" }), /Unknown payment mode/); throws(() => P.jobPatchFrom({ employment_type: "intern" }), /Unknown employment type/); });
await K(S, "jobPatchFrom: an enum given an object is refused as not text", node, () => throws(() => P.jobPatchFrom({ pay_type: { x: 1 } }), /pay type isn't plain text/));
await K(S, "jobPatchFrom: pay_amount null / undefined / '  ' → null", node, () => { eq(P.jobPatchFrom({ pay_amount: null }).pay_amount, null); eq(P.jobPatchFrom({ pay_amount: undefined }).pay_amount, null); eq(P.jobPatchFrom({ pay_amount: "  " }).pay_amount, null); });
await K(S, "jobPatchFrom: pay_amount strips ₹ , and spaces; refuses negative and non-numbers; caps at 99,999,999", node, () => { eq(P.jobPatchFrom({ pay_amount: "₹ 12,000" }).pay_amount, 12000); throws(() => P.jobPatchFrom({ pay_amount: -1 }), /must be a number/); throws(() => P.jobPatchFrom({ pay_amount: "12x" }), /must be a number/); throws(() => P.jobPatchFrom({ pay_amount: 100000000 }), /too large/); });
await K(S, "jobPatchFrom: pay_amount rounds to paise (1.005 → 1.01 or 1, never 1.005)", node, () => { const v = P.jobPatchFrom({ pay_amount: 1.005 }).pay_amount; assert(Math.round(v * 100) === v * 100, String(v)); });
await K(S, "jobPatchFrom: weekly_off lower-cases and keeps three letters, de-duplicates, drops unknowns", node, () => eq(P.jobPatchFrom({ weekly_off: ["SUNDAY", "sun", "Holiday", "Mon"] }).weekly_off, ["sun", "mon"]));
await K(S, "jobPatchFrom: weekly_off with nothing valid or a non-array → null", node, () => { eq(P.jobPatchFrom({ weekly_off: ["x"] }).weekly_off, null); eq(P.jobPatchFrom({ weekly_off: null }).weekly_off, null); });
await K(S, "jobPatchFrom: pay_extras — label 60 chars, kind allowance unless 'deduction', amount rounded", node, () => eq(P.jobPatchFrom({ pay_extras: [{ label: "L".repeat(70), kind: "deduction", amount: "1,000.555" }, { amount: 0 }] }).pay_extras, [{ label: "L".repeat(60), kind: "deduction", amount: 1000.56 }, { label: "Extra", kind: "allowance", amount: 0 }]));
await K(S, "jobPatchFrom: pay_extras — an entry that is null is read as {} (amount '' → 0)", node, () => eq(P.jobPatchFrom({ pay_extras: [null] }).pay_extras, [{ label: "Extra", kind: "allowance", amount: 0 }]));
await K(S, "jobPatchFrom: pay_extras — a bad or negative amount, or a non-text label, is refused", node, () => { throws(() => P.jobPatchFrom({ pay_extras: [{ amount: "x" }] }), /allowance\/deduction amount/); throws(() => P.jobPatchFrom({ pay_extras: [{ amount: -2 }] }), /allowance\/deduction amount/); throws(() => P.jobPatchFrom({ pay_extras: [{ label: { a: 1 }, amount: 1 }] }), /allowance name isn't plain text/); });
await K(S, "jobPatchFrom: pay_extras — more than 12 entries keeps the first 12", node, () => eq(P.jobPatchFrom({ pay_extras: Array.from({ length: 13 }, (_, i) => ({ label: `e${i}`, amount: i })) }).pay_extras.at(-1).label, "e11"));

// paymentFrom
await K(S, "paymentFrom: defaults kind salary, mode cash, no period, no note, today", node, () => eq(P.paymentFrom({ amount: 5 }), { kind: "salary", amount: 5, for_period: null, mode: "cash", paid_on: P.todayIST(), note: null }));
await K(S, "paymentFrom: amount refused when missing, non-numeric, ≤ 0, rounds to 0 (item 13), or too large", node, () => { for (const a of [undefined, "", "x", 0, -1, 0.004]) throws(() => P.paymentFrom({ amount: a }), /greater than zero/, String(a)); throws(() => P.paymentFrom({ amount: 1e9 }), /too large/); });
await K(S, "paymentFrom: amount strips ₹ , spaces and rounds to paise", node, () => eq(P.paymentFrom({ amount: "₹ 1,234.567" }).amount, 1234.57));
await K(S, "paymentFrom: an unknown kind / mode is refused", node, () => { throws(() => P.paymentFrom({ amount: 1, kind: "tip" }), /Unknown payment type/); throws(() => P.paymentFrom({ amount: 1, mode: "card" }), /Unknown payment mode/); });
await K(S, "paymentFrom: for_period YYYY-MM or a full date → the 1st; month 00 / 13 / one digit refused", node, () => { eq(P.paymentFrom({ amount: 1, for_period: "2026-07" }).for_period, "2026-07-01"); eq(P.paymentFrom({ amount: 1, for_period: " 2026-07-31 " }).for_period, "2026-07-01"); for (const p of ["2026-00", "2026-13", "2026-7", "July"]) throws(() => P.paymentFrom({ amount: 1, for_period: p }), /valid month/, p); });
await K(S, "paymentFrom: paid_on a real past day kept; a bad one refused; future refused", node, () => { eq(P.paymentFrom({ amount: 1, paid_on: "2025-03-01" }).paid_on, "2025-03-01"); throws(() => P.paymentFrom({ amount: 1, paid_on: "2025-02-29" }), /payment date isn't a real date/); throws(() => P.paymentFrom({ amount: 1, paid_on: "2999-12-31" }), /future/); });
await K(S, "paymentFrom: note trimmed to 200; a non-text note refused (item 5)", node, () => { eq(P.paymentFrom({ amount: 1, note: " hi " }).note, "hi"); throws(() => P.paymentFrom({ amount: 1, note: ["x"] }), /note isn't plain text/); });
await K(S, "todayIST is the date 5.5 hours ahead of UTC, YYYY-MM-DD", node, () => { eq(P.todayIST(), new Date(Date.now() + 5.5 * 3600e3).toISOString().slice(0, 10)); });
await K(S, "istDateOf: 18:29:59Z stays, 18:30:00Z is the next day; garbage → today", node, () => { eq(P.istDateOf("2026-01-01T18:29:59Z"), "2026-01-01"); eq(P.istDateOf("2026-01-01T18:30:00Z"), "2026-01-02"); eq(P.istDateOf("nope"), P.todayIST()); });

// staffProfile
await K(SV, "it re-exports every value of staffProfileShared", node, () => { for (const k of Object.keys(P)) assert(k in SP, k); });
const pa = SP.payAccessWith;
await K(SV, "payAccessWith: module off → all five false, for every actor", node, () => { for (const a of ["admin", "owner", "manager"]) eq(pa(a, {}, false), { moduleOn: false, canSeePay: false, canRecordPay: false, canEditProfile: false, canEditJobPay: false }); });
await K(SV, "payAccessWith: admin and owner → all five true", node, () => { for (const a of ["admin", "owner"]) eq(pa(a, {}, true), { moduleOn: true, canSeePay: true, canRecordPay: true, canEditProfile: true, canEditJobPay: true }); });
await K(SV, "payAccessWith: manager, nothing stored → record + edit, not see, never job/pay setup", node, () => eq(pa("manager", { manager_permissions: null }, true), { moduleOn: true, canSeePay: false, canRecordPay: true, canEditProfile: true, canEditJobPay: false }));
await K(SV, "payAccessWith: manager, every power stored true → see + record + edit, still no job/pay setup", node, () => eq(pa("manager", { manager_permissions: { see_staff_pay: true, record_staff_payment: true, edit_staff_profiles: true } }, true), { moduleOn: true, canSeePay: true, canRecordPay: true, canEditProfile: true, canEditJobPay: false }));
await K(SV, "payAccessWith: manager, stored false beats the absent-ON rule", node, () => eq(pa("manager", { manager_permissions: { record_staff_payment: false, edit_staff_profiles: false } }, true).canRecordPay || pa("manager", { manager_permissions: { edit_staff_profiles: false } }, true).canEditProfile, false));
await K(SV, "payAccessWith: manager, a stored non-boolean falls to the absent rule", node, () => { const a = pa("manager", { manager_permissions: { see_staff_pay: "yes", record_staff_payment: 0 } }, true); eq([a.canSeePay, a.canRecordPay], [false, true]); });
await K(SV, "payAccess reads the payroll ladder for that restaurant and applies payAccessWith", "drive with the stand-in ladder", async () => { const seen = []; globalThis.__t18.payroll = (rid) => { seen.push(rid); return false; }; eq((await SP.payAccess("owner", {}, "r-9")).moduleOn, false); eq(seen, ["r-9"]); globalThis.__t18.payroll = () => true; eq((await SP.payAccess("owner", {}, "r-9")).canEditJobPay, true); });
const client = (reply) => ({ from: (t) => { const q = { t, ops: [] }; const c = new Proxy({}, { get(_, k) { if (k === "then") return (r) => r(reply(q)); return (...a) => { q.ops.push([k, ...a]); return c; }; } }); client.last = q; return c; } });
await K(SV, "payHistoryBlocksDelete: the read is staff_payments, head-only count, that one person", "drive with a recording client", async () => { const cl = client(() => ({ count: 0 })); await SP.payHistoryBlocksDelete(cl, "s-1"); eq(client.last.t, "staff_payments"); eq(client.last.ops, [["select", "id", { count: "exact", head: true }], ["eq", "staff_id", "s-1"]]); });
await K(SV, "payHistoryBlocksDelete: error → blocked, count -1 (fails closed)", "drive", async () => eq(await SP.payHistoryBlocksDelete(client(() => ({ error: { message: "x" } })), "s"), { blocked: true, count: -1 }));
await K(SV, "payHistoryBlocksDelete: 0 → not blocked; 2 → blocked; null count → 0", "drive", async () => { eq(await SP.payHistoryBlocksDelete(client(() => ({ count: 0 })), "s"), { blocked: false, count: 0 }); eq(await SP.payHistoryBlocksDelete(client(() => ({ count: 2 })), "s"), { blocked: true, count: 2 }); eq(await SP.payHistoryBlocksDelete(client(() => ({ count: null })), "s"), { blocked: false, count: 0 }); });
await K(SV, "PAY_HISTORY_DELETE_MESSAGE: -1 says it could not check; 1 entry/it; 3 entries/them; all point at Mark as left", node, () => { assert(/Couldn't check/.test(SP.PAY_HISTORY_DELETE_MESSAGE(-1))); assert(/1 pay entry on record, and deleting the login would erase it/.test(SP.PAY_HISTORY_DELETE_MESSAGE(1))); assert(/3 pay entries on record, and deleting the login would erase them/.test(SP.PAY_HISTORY_DELETE_MESSAGE(3))); assert(/Mark as left/.test(SP.PAY_HISTORY_DELETE_MESSAGE(3))); });
