// Block E — lib/features.ts · lib/ownerEntitlements.ts · lib/viewAsPerson.ts, every branch, REAL files.
import { chk, assert, eq, db, calls } from "./core.mjs";
import * as F from "@/lib/features";
import * as OE from "@/lib/ownerEntitlements";
import * as VA from "@/lib/viewAsPerson";

const FE = "lib/features.ts", OW = "lib/ownerEntitlements.ts", VP = "lib/viewAsPerson.ts", node = "node: the real export";
const K = (f, c, h, fn) => chk(f, c, h, fn);
const D = F.FEATURE_DEFAULTS;
let ridN = 0;
const fresh = () => `rid-${++ridN}-${Date.now()}`;   // a never-seen restaurant: the module caches per id
const store = (init = {}) => { const m = new Map(Object.entries(init)); const ls = { getItem: (k) => (m.has(k) ? m.get(k) : null), setItem: (k, v) => m.set(k, String(v)), removeItem: (k) => m.delete(k), _m: m }; Object.defineProperty(globalThis, "localStorage", { value: ls, configurable: true, writable: true }); return ls; };
const noStore = () => Object.defineProperty(globalThis, "localStorage", { get() { throw new Error("SecurityError: storage refused"); }, configurable: true });
const settings = (fn) => { globalThis.__t18.getSettings = fn; globalThis.__t18.invalidated = []; };
const flush = () => new Promise((r) => setTimeout(r, 5));

// ── FEATURE_DEFAULTS ───────────────────────────────────────────────────────────────────────────
await K(FE, "FEATURE_DEFAULTS: guest switches ON, prep_time OFF, the four backend-only flags OFF", node, () => { eq(Object.entries(D).filter(([, v]) => !v).map(([k]) => k).sort(), ["aggregators", "gst_invoice", "payments", "prep_time", "verification"]); });
await K(FE, "FEATURE_DEFAULTS has no `scrollspy` (removed 2026-08-07)", node, () => assert(!("scrollspy" in D)));
// ── getFeatures ────────────────────────────────────────────────────────────────────────────────
await K(FE, "getFeatures('') answers a copy of the defaults and reads nothing", node, async () => { let n = 0; settings(async () => { n++; return {}; }); const a = await F.getFeatures(""); eq(a, { ...D }); eq(n, 0); a.reviews = false; eq(D.reviews, true); });
await K(FE, "getFeatures(): no argument means the default restaurant id", "drive the stand-in settings reader", async () => { const seen = []; settings(async (rid) => { seen.push(rid); return {}; }); store(); await F.refreshFeatures(); eq(seen.at(-1), "00000000-0000-0000-0000-000000000001"); });
await K(FE, "getFeatures: defaults + stored overrides; stored keys the code does not know ride along", "drive", async () => { store(); settings(async () => ({ features: { reviews: false, scrollspy: true } })); const f = await F.getFeatures(fresh()); eq([f.reviews, f.model3d, f.scrollspy], [false, true, true]); });
await K(FE, "getFeatures: a settings row with features null / missing reads the defaults", "drive", async () => { store(); settings(async () => ({ features: null })); eq(await F.getFeatures(fresh()), { ...D }); settings(async () => ({})); eq(await F.getFeatures(fresh()), { ...D }); });
await K(FE, "getFeatures caches: the second call for a restaurant reads nothing", "drive", async () => { store(); let n = 0; settings(async () => { n++; return { features: {} }; }); const r = fresh(); await F.getFeatures(r); await F.getFeatures(r); eq(n, 1); });
await K(FE, "getFeatures: two calls at once share ONE read", "drive", async () => { store(); let n = 0; settings(async () => { n++; await flush(); return {}; }); const r = fresh(); await Promise.all([F.getFeatures(r), F.getFeatures(r)]); eq(n, 1); });
await K(FE, "getFeatures saves the map to the phone under lfh_features:<rid>", "drive with an in-memory localStorage", async () => { const ls = store(); settings(async () => ({ features: { favorites: false } })); const r = fresh(); await F.getFeatures(r); eq(JSON.parse(ls.getItem(`lfh_features:${r}`)).favorites, false); });
await K(FE, "getFeatures: a phone that refuses storage still gets the switches", "drive with a throwing localStorage", async () => { noStore(); settings(async () => ({ features: { search: false } })); eq((await F.getFeatures(fresh())).search, false); store(); });
await K(FE, "getFeatures: a failed read answers the switches last saved on this phone", "drive", async () => { const r = fresh(); store({ [`lfh_features:${r}`]: JSON.stringify({ reviews: false }) }); settings(async () => { throw new Error("offline"); }); const f = await F.getFeatures(r); eq([f.reviews, f.model3d], [false, true]); });
await K(FE, "getFeatures: a failed read with nothing saved answers the defaults", "drive", async () => { store(); settings(async () => { throw new Error("offline"); }); eq(await F.getFeatures(fresh()), { ...D }); });
await K(FE, "getFeatures: a failed read is not remembered — the next call reads again", "drive", async () => { store(); let n = 0; settings(async () => { n++; throw new Error("x"); }); const r = fresh(); await F.getFeatures(r); await F.getFeatures(r); eq(n, 2); });
await K(FE, "getFeatures: a saved value that is not JSON, or JSON null, is ignored", "drive", async () => { for (const bad of ["{not json", "null", "7"]) { const r = fresh(); store({ [`lfh_features:${r}`]: bad }); settings(async () => { throw new Error("x"); }); const f = await F.getFeatures(r); eq(f.reviews, true, bad); } });
await K(FE, "getFeatures: one restaurant's switches never show for another", "drive", async () => { store(); settings(async (rid) => ({ features: { reviews: rid.endsWith("A") } })); const a = `${fresh()}A`, b = `${fresh()}B`; eq([(await F.getFeatures(a)).reviews, (await F.getFeatures(b)).reviews], [true, false]); });
// ── refreshFeatures ────────────────────────────────────────────────────────────────────────────
await K(FE, "refreshFeatures: drops the settings cache FIRST, then reads, then tells subscribers", "drive", async () => { store(); const order = []; globalThis.__t18.invalidated = { push: () => order.push("drop") }; globalThis.__t18.getSettings = async () => { order.push("read"); return {}; }; await F.refreshFeatures(fresh()); eq(order, ["drop", "read"]); });
await K(FE, "refreshFeatures {fresh:false} keeps the settings cache (the 60s poll)", "drive", async () => { store(); settings(async () => ({})); await F.refreshFeatures(fresh(), { fresh: false }); eq(globalThis.__t18.invalidated, []); });
await K(FE, "refreshFeatures {fresh:true} / no option drops it", "drive", async () => { store(); settings(async () => ({})); const r = fresh(); await F.refreshFeatures(r, { fresh: true }); eq(globalThis.__t18.invalidated, [r]); });
await K(FE, "refreshFeatures re-reads even when the map was cached", "drive", async () => { store(); let n = 0; settings(async () => { n++; return {}; }); const r = fresh(); await F.getFeatures(r); await F.refreshFeatures(r); eq(n, 2); });
// ── useFeatures (stand-in React: state box + recorded effect) ───────────────────────────────────
await K(FE, "useFeatures: first value is the defaults when nothing is cached and no seed is given", "run the hook with a stand-in React", () => { store(); eq(F.useFeatures(fresh()), { ...D }); });
await K(FE, "useFeatures: a seed LEADS the first value (server-known switches)", "run the hook", () => { store(); eq(F.useFeatures(fresh(), { reviews: false }).reviews, false); });
await K(FE, "useFeatures: a cached map beats the seed", "run the hook", async () => { store(); settings(async () => ({ features: { reviews: true } })); const r = fresh(); await F.getFeatures(r); eq(F.useFeatures(r, { reviews: false }).reviews, true); });
await K(FE, "useFeatures: the first value never reads the phone's storage (hydration-safe)", "run the hook with a saved value present", () => { const r = fresh(); store({ [`lfh_features:${r}`]: JSON.stringify({ reviews: false }) }); eq(F.useFeatures(r).reviews, true); });
await K(FE, "useFeatures effect: the saved switches apply at once, then the live read lands", "run the recorded effect", async () => { const r = fresh(); store({ [`lfh_features:${r}`]: JSON.stringify({ reviews: false }) }); settings(async () => { await flush(); return { features: { reviews: true, search: false } }; }); F.useFeatures(r); const { box } = globalThis.__t18.hook; const stop = globalThis.__t18.effect.fn(); eq(box.v.reviews, false, "saved switches first"); await flush(); await flush(); eq([box.v.reviews, box.v.search], [true, false], "then the live answer"); stop(); });
await K(FE, "useFeatures effect: re-runs on the restaurant id (deps = [restaurantId])", "read the recorded deps", () => { store(); const r = fresh(); F.useFeatures(r); eq(globalThis.__t18.effect.deps, [r]); });
await K(FE, "useFeatures effect: subscribed — a refresh for THAT restaurant updates the state", "run effect, then refreshFeatures", async () => { store(); const r = fresh(); settings(async () => ({ features: {} })); F.useFeatures(r); const { box } = globalThis.__t18.hook; const stop = globalThis.__t18.effect.fn(); await flush(); settings(async () => ({ features: { favorites: false } })); await F.refreshFeatures(r); eq(box.v.favorites, false); stop(); });
await K(FE, "useFeatures effect: a refresh for ANOTHER restaurant changes nothing", "run effect, refresh a different id", async () => { store(); const r = fresh(); settings(async () => ({ features: {} })); F.useFeatures(r); const { box } = globalThis.__t18.hook; const stop = globalThis.__t18.effect.fn(); await flush(); const before = box.sets; settings(async () => ({ features: { favorites: false } })); await F.refreshFeatures(fresh()); eq(box.sets, before); stop(); });
await K(FE, "useFeatures cleanup: after unmount neither a late read nor a refresh touches the state", "run effect, clean up, then let the read land", async () => { store(); const r = fresh(); settings(async () => { await flush(); return { features: { reviews: false } }; }); F.useFeatures(r); const { box } = globalThis.__t18.hook; const stop = globalThis.__t18.effect.fn(); stop(); await flush(); await flush(); eq(box.v.reviews, true, "late read ignored"); await F.refreshFeatures(r); eq(box.v.reviews, true, "unsubscribed"); });
await K(FE, "useFeatures(''): the effect does nothing — no read, no subscription", "run the effect for an unknown restaurant", async () => { store(); let n = 0; settings(async () => { n++; return {}; }); F.useFeatures(""); const ret = globalThis.__t18.effect.fn(); eq(ret, undefined); await flush(); eq(n, 0); });
await K(FE, "useFeatures effect: with a cached map, the saved value is NOT re-applied over it", "run effect with cache + a different saved value", async () => { const r = fresh(); store(); settings(async () => ({ features: { reviews: true } })); await F.getFeatures(r); localStorage.setItem(`lfh_features:${r}`, JSON.stringify({ reviews: false })); F.useFeatures(r); const { box } = globalThis.__t18.hook; const stop = globalThis.__t18.effect.fn(); eq(box.sets, 0); await flush(); eq(box.v.reviews, true); stop(); });

// ── ownerEntitlements ──────────────────────────────────────────────────────────────────────────
const KEYS = OE.OWNER_ENTITLEMENT_KEYS;
await K(OW, "OWNER_SECTION_KEYS: the twelve owner sections", node, () => eq(OE.OWNER_SECTION_KEYS.length, 12));
await K(OW, "OWNER_ENTITLEMENT_KEYS = the sections + power_<flag> for every manager power", node, async () => { const M = await import("@/lib/accessModel"); eq(KEYS.length, 12 + M.MANAGER_POWER_FLAGS.length); assert(KEYS.includes("power_khata")); });
await K(OW, "powerEntitlementKey('x') is 'power_x'", node, () => eq(OE.powerEntitlementKey("x"), "power_x"));
await K(OW, "powerEntitled is gone; the key shape survives only in powerEntitlementKey (item 26)", node, () => { assert(!("powerEntitled" in OE)); eq(OE.powerEntitlementKey("khata"), "power_khata"); });
await K(OW, "mergeOwnerEntitlements: every key ON by default; only booleans override", node, () => { const m = OE.mergeOwnerEntitlements({ reports: false, menu: 0, bogus: false }); eq(Object.keys(m).length, KEYS.length); eq([m.reports, m.menu, "bogus" in m], [false, true, false]); });
await K(OW, "mergeOwnerEntitlements: null / a string / an array → all ON", node, () => { for (const v of [null, "x", [false]]) assert(Object.values(OE.mergeOwnerEntitlements(v)).every(Boolean)); });
await K(OW, "getOwnerEntitlements(''): all ON, nothing read", "drive", async () => { db(() => ({ data: null })); const r = await OE.getOwnerEntitlements(""); eq(calls().length, 0); assert(Object.values(r).every(Boolean)); });
await K(OW, "getOwnerEntitlements: one column, one row; the stored bag merged", "drive", async () => { db(() => ({ data: { owner_entitlements: { customers: false } }, error: null })); const r = await OE.getOwnerEntitlements("r1"); eq(calls()[0].ops.slice(0, 3), [["select", "owner_entitlements"], ["eq", "id", "r1"], ["maybeSingle"]]); eq(r.customers, false); });
await K(OW, "getOwnerEntitlements: no row → all ON (the restaurant has stored nothing)", "drive", async () => { db(() => ({ data: null, error: null })); assert(Object.values(await OE.getOwnerEntitlements("r1")).every(Boolean)); });
await K(OW, "getOwnerEntitlements: one failed read then a good one → the good answer (one retry, item 12)", "drive with the first read failing", async () => { let n = 0; db(() => (n++ === 0 ? { data: null, error: { message: "blip" } } : { data: { owner_entitlements: { reports: false } }, error: null })); const r = await OE.getOwnerEntitlements("r1"); eq([n, r.reports, r.customers], [2, false, true]); });
await K(OW, "getOwnerEntitlements: two failed reads → every section CLOSED (item 12)", "drive with both reads failing", async () => { db(() => ({ data: null, error: { message: "down" } })); const r = await OE.getOwnerEntitlements("r1"); eq(calls().length, 2); assert(Object.values(r).every((v) => v === false)); eq(Object.keys(r).length, KEYS.length); });
await K(OW, "entitledSubset([]) → [] and nothing read", "drive", async () => { db(() => ({ data: [] })); eq(await OE.entitledSubset([], "reports"), []); eq(calls().length, 0); });
await K(OW, "entitledSubset: keeps restaurants where the key is absent or true, drops false", "drive", async () => { db(() => ({ data: [{ id: "a", owner_entitlements: { reports: false } }, { id: "b", owner_entitlements: null }, { id: "c", owner_entitlements: { reports: true } }], error: null })); eq(await OE.entitledSubset(["a", "b", "c"], "reports"), ["b", "c"]); });
await K(OW, "entitledSubset: a failed read → [] (fails closed)", "drive", async () => { db(() => ({ data: null, error: { message: "x" } })); eq(await OE.entitledSubset(["a"], "reports"), []); });
await K(OW, "entitledSubset reads id + owner_entitlements, .in(ids), limited to the chunk", "drive", async () => { db(() => ({ data: [], error: null })); await OE.entitledSubset(["a", "b"], "reports"); eq(calls()[0].ops, [["select", "id, owner_entitlements"], ["in", "id", ["a", "b"]], ["limit", 2]]); });
await K(OW, "logViewSubset([]) → [] and nothing read", "drive", async () => { db(() => ({ data: [] })); eq(await OE.logViewSubset([], "activity"), []); eq(calls().length, 0); });
await K(OW, "logViewSubset: absent opts / non-object opts / true keep; false drops", "drive", async () => { db(() => ({ data: [{ id: "a", access_config: null }, { id: "b", access_config: { view_logs: { owner_opts: "x" } } }, { id: "c", access_config: { view_logs: { owner_opts: { activity: true } } } }, { id: "d", access_config: { view_logs: { owner_opts: { activity: false } } } }], error: null })); eq(await OE.logViewSubset(["a", "b", "c", "d"], "activity"), ["a", "b", "c"]); });
await K(OW, "logViewSubset: the two views are independent", "drive", async () => { db(() => ({ data: [{ id: "a", access_config: { view_logs: { owner_opts: { removals: false } } } }], error: null })); eq(await OE.logViewSubset(["a"], "activity"), ["a"]); eq(await OE.logViewSubset(["a"], "removals"), []); });
await K(OW, "logViewSubset: a failed read → [] (fails closed)", "drive", async () => { db(() => ({ data: null, error: { message: "x" } })); eq(await OE.logViewSubset(["a"], "activity"), []); });
await K(OW, "getOwnerEntitlementsUnion([]) → all ON, nothing read", "drive", async () => { db(() => ({ data: [] })); assert(Object.values(await OE.getOwnerEntitlementsUnion([])).every(Boolean)); eq(calls().length, 0); });
await K(OW, "getOwnerEntitlementsUnion: ON if ANY restaurant has it; OFF only if all have it off", "drive", async () => { db(() => ({ data: [{ owner_entitlements: { reports: false, menu: false } }, { owner_entitlements: { reports: true, menu: false } }], error: null })); const u = await OE.getOwnerEntitlementsUnion(["a", "b"]); eq([u.reports, u.menu, u.staff], [true, false, true]); });
await K(OW, "getOwnerEntitlementsUnion: a failed read → every section CLOSED (item 12)", "drive", async () => { db(() => ({ data: null, error: { message: "x" } })); assert(Object.values(await OE.getOwnerEntitlementsUnion(["a"])).every((v) => v === false)); });
await K(OW, "getOwnerEntitlementsUnion: a read that comes back with zero rows → all ON (nothing stored)", "drive", async () => { db(() => ({ data: [], error: null })); assert(Object.values(await OE.getOwnerEntitlementsUnion(["a"])).every(Boolean)); });

// ── viewAsPerson ───────────────────────────────────────────────────────────────────────────────
const ID = "a1b2c3d4-0000-4000-8000-000000000001";
let idN = 0; const newId = () => `a1b2c3d4-0000-4000-8000-${String(++idN).padStart(12, "0")}`;
const req = (as, cookie = "tok") => ({ nextUrl: { searchParams: new URLSearchParams(as ? { as } : {}) }, cookies: { get: () => (cookie === null ? undefined : { value: cookie }) } });
const va = async (row, r, rid = "r1", role = "manager", g = { user: null }, tok = () => true) => { db(() => ({ data: row ? [row] : [], error: null })); globalThis.__t18.tokenOk = tok; return VA.viewAsPerson(r, rid, g, role); };
await K(VP, "isPersonId: a uuid any case yes; anything else (null, '', 35 chars, spaces) no", node, () => { assert(VA.isPersonId(ID)); assert(VA.isPersonId(ID.toUpperCase())); for (const v of [null, undefined, "", ID.slice(1), ` ${ID}`, "not-a-uuid"]) assert(!VA.isPersonId(v), String(v)); });
await K(VP, "a real staff session → null, nothing read", "drive", async () => { eq(await va({ id: ID, role: "manager", restaurant_id: "r1" }, req(ID), "r1", "manager", { user: { id: "u" } }), null); eq(calls().length, 0); });
await K(VP, "an empty restaurant → null before anything is read (item 14)", "drive", async () => { eq(await va({ id: ID, role: "manager", restaurant_id: null }, req(ID), ""), null); eq(calls().length, 0); });
await K(VP, "no ?as= or a malformed one → null, nothing read", "drive", async () => { eq(await va({}, req(null)), null); eq(await va({}, req("x")), null); eq(calls().length, 0); });
await K(VP, "no admin cookie / an invalid one → null, the person is never read", "drive", async () => { const id = newId(); eq(await va({ id, role: "manager", restaurant_id: "r1" }, req(id, null), "r1", "manager", { user: null }, (t) => !!t), null); eq(await va({ id, role: "manager", restaurant_id: "r1" }, req(id, "bad"), "r1", "manager", { user: null }, () => false), null); eq(calls().length, 0); });
await K(VP, "the right person → returned; the read is one active row by id with the named columns", "drive", async () => { const id = newId(); const u = await va({ id, role: "manager", restaurant_id: "r1", name: "Asha" }, req(id)); eq(u?.name, "Asha"); const q = calls()[0]; eq(q.table, "staff_users"); eq(q.ops[0], ["select", "id, username, name, role, restaurant_id, active, permissions, assigned_tables"]); eq(q.ops.slice(1), [["eq", "id", id], ["eq", "active", true], ["limit", 1]]); });
await K(VP, "a different role than the panel's → null", "drive", async () => { const id = newId(); eq(await va({ id, role: "tablet", restaurant_id: "r1" }, req(id), "r1", "manager"), null); });
await K(VP, "another restaurant's person → null; a person with no restaurant → null", "drive", async () => { let id = newId(); eq(await va({ id, role: "manager", restaurant_id: "r2" }, req(id)), null); id = newId(); eq(await va({ id, role: "manager", restaurant_id: null }, req(id)), null); });
await K(VP, "no such (or inactive) person → null, and that answer is cached too", "drive", async () => { const id = newId(); eq(await va(null, req(id)), null); db(() => ({ data: [{ id, role: "manager", restaurant_id: "r1" }], error: null })); eq(await VA.viewAsPerson(req(id), "r1", { user: null }, "manager"), null); eq(calls().length, 0); });
await K(VP, "a failed read → null and is NOT cached (the next request reads again)", "drive", async () => { const id = newId(); db(() => ({ data: null, error: { message: "x" } })); globalThis.__t18.tokenOk = () => true; eq(await VA.viewAsPerson(req(id), "r1", { user: null }, "manager"), null); db(() => ({ data: [{ id, role: "manager", restaurant_id: "r1", name: "B" }], error: null })); eq((await VA.viewAsPerson(req(id), "r1", { user: null }, "manager"))?.name, "B"); });
await K(VP, "the person is cached for 20 s: a second ask within it reads nothing", "drive", async () => { const id = newId(); await va({ id, role: "manager", restaurant_id: "r1" }, req(id)); db(() => ({ data: [], error: null })); await VA.viewAsPerson(req(id), "r1", { user: null }, "manager"); eq(calls().length, 0); });
await K(VP, "after 20 s the person is read again", "drive with a moved clock", async () => { const id = newId(); await va({ id, role: "manager", restaurant_id: "r1" }, req(id)); const now = Date.now; Date.now = () => now() + 20_001; try { db(() => ({ data: [], error: null })); globalThis.__t18.tokenOk = () => true; eq(await VA.viewAsPerson(req(id), "r1", { user: null }, "manager"), null); eq(calls().length, 1); } finally { Date.now = now; } });
await K(VP, "personLabel: name, else username, else null; null person → null", node, () => { eq(VA.personLabel({ name: "A", username: "a" }), "A"); eq(VA.personLabel({ name: "", username: "a" }), "a"); eq(VA.personLabel({ name: null, username: "" }), null); eq(VA.personLabel(null), null); });
