import { chromium } from "playwright";
import { loginAs } from "../login.mjs";
const BASE = "http://localhost:4317";
const [role, path, w, h, skin, out] = process.argv.slice(2);
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: +w, height: +h }, deviceScaleFactor: +w < 500 ? 3 : 1 });
await loginAs(ctx, role, BASE);
await ctx.addCookies([{ name: "aevidine_skin", value: skin, url: BASE }]);
await ctx.addInitScript((s) => { try { localStorage.setItem("aevidine_skin", s); } catch {} }, skin);
const p = await ctx.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push("pageerror: " + e.message));
p.on("console", (m) => { if (m.type() === "error") errs.push("console: " + m.text().slice(0, 200)); });
await p.goto(BASE + path, { waitUntil: "networkidle" });
await p.evaluate(() => document.querySelectorAll("nextjs-portal").forEach((n) => n.remove()));
await p.waitForTimeout(500);
await p.screenshot({ path: `.claude/sweep/shots/T17/${out}.png` });
console.log("errors:", errs.length ? errs : "none");
console.log("url:", p.url());
await ctx.close(); await b.close();
