import { chromium } from "playwright";
import { loginAs } from "./scripts/sweep/login.mjs";
const BASE = "http://localhost:4013";
const sleep = ms => new Promise(r => setTimeout(r, ms));
const b = await chromium.launch(); const ctx = await b.newContext();
const route = await loginAs(ctx, "manager", BASE);
const p = await ctx.newPage();
const reqs = [], forb = [];
p.on("request", r => { const u = r.url(); if (u.includes("/api/")) reqs.push(u.replace(BASE, "")); });
p.on("response", async r => { if (r.status() === 403) forb.push(r.url().replace(BASE, "")); });
await p.goto(BASE + route, { waitUntil: "domcontentloaded" });
await sleep(9000);
console.log("FIRST LOAD — api requests:");
[...new Set(reqs)].slice(0, 14).forEach(u => console.log("  " + u));
const n1 = reqs.length; reqs.length = 0;
await p.reload({ waitUntil: "domcontentloaded" });
await sleep(9000);
console.log("\nSECOND LOAD — api requests:");
[...new Set(reqs)].slice(0, 14).forEach(u => console.log("  " + u));
console.log("\n403s:", forb.length ? [...new Set(forb)].join("  ") : "none");
const cached = await p.evaluate(async () => {
  const c = await caches.open("lfh-data-v4");
  return (await c.keys()).map(r => r.url.replace(location.origin, ""));
});
console.log("\nSAVED FOR OFFLINE:"); cached.slice(0, 14).forEach(u => console.log("  " + u));
await b.close();
