// BLOCK A · P69701–P69900 — the inventory API and the issue-media upload, read line by line.
import { check, has, hasRaw, countOf, count, results, INV_ROUTE as R, MEDIA_ROUTE as M, CODE } from "./static.mjs";

// ── A1 · the gate, the scope and the module rung (P69701–P69730) ────────────────────────────────
check("P69701", "GET asks requireRole(req, 'manager') before any database call", () => has(R, /requireRole\(req, "manager"\)/));
check("P69702", "…and a transient auth failure answers 503, never 'please log in'", () => has(R, /g\.transient[\s\S]{0,140}status: 503/));
check("P69703", "…and a real refusal answers 401 with words a person can read", () => has(R, /Not authorised — please log in\.[\s\S]{0,40}401/));
check("P69704", "the restaurant comes from panelRestaurantId(req, g), never from the body", () => has(R, /panelRestaurantId\(req, g\)/) && !has(R, /body\.restaurant_id/));
check("P69705", "GET refuses with 400 when there is no restaurant scope at all", () => has(R, /if \(!rid\) return err\("No restaurant scope\."/));
check("P69706", "…and that sentence is still the one R48 protects, not a reworded one", () => hasRaw(R, /REJECTED \(owner, 2026-08-28\)[\s\S]{0,200}R48/));
check("P69707", "the module rung is asked on GET before any path is read", () => /moduleOn\(g, rid\)[\s\S]{0,200}const path = \(await ctx\.params\)\.path/.test(CODE[R]));
check("P69708", "…and on POST too", () => countOf(R, /await moduleOn\(g, rid\)/g) === 2);
check("P69709", "the module rung reads inventoryLadder(rid).effective", () => has(R, /\(await inventoryLadder\(rid\)\)\.effective/));
check("P69710", "…and the admin super-user (no staff user) passes it", () => has(R, /if \(!g\.user\) return true;/));
check("P69711", "a module that is off answers 403 with plain words", () => countOf(R, /Inventory isn't enabled for this restaurant\.", 403/g) === 2);
check("P69712", "the per-power question uses the SHARED rule, lib/managerCan", () => has(R, /import \{ managerCan \}/) && has(R, /managerCan\(g, rid, "inv_stock"\)/));
check("P69713", "…and there is no local copy of it left behind", () => !has(R, /function invCan/));
check("P69714", "expenses ask inv_expenses, stock asks inv_stock — two different powers", () => has(R, /managerCan\(g, rid, "inv_expenses"\)/) && has(R, /managerCan\(g, rid, "inv_stock"\)/));
check("P69715", "a refused power answers 403 and names what the owner has not allowed", () => has(R, /Your owner hasn't given managers permission to \$\{what\}\.`, 403/));
check("P69716", "whoami answers display truth only, and says so", () => hasRaw(R, /display\s*truth only/i));
check("P69717", "…and it asks both powers in ONE Promise.all, not two round trips", () => has(R, /Promise\.all\(\[managerCan\(g, rid, "inv_stock"\), managerCan\(g, rid, "inv_expenses"\)\]\)/));
check("P69718", "the actor label is the person's name and role, never a bare uuid", () => has(R, /\$\{g\.user\.name \|\| g\.user\.username\} \(\$\{g\.user\.role\}\)/));
check("P69719", "…and the admin super-user is recorded as 'admin'", () => has(R, /: "admin";/));
check("P69720", "every stock write also records created_by_id, so a name change keeps the link", () => countOf(R, /created_by_id: actorId/g) >= 3);
check("P69721", "the whole POST is wrapped in withIdempotency, so a replay cannot double-post", () => has(R, /export const POST = withIdempotency\(/));
check("P69722", "…and the wrapper is keyed 'inventory'", () => has(R, /\}, "inventory"\);/));
check("P69723", "the clash gate runs on POST before any branch is chosen", () => /const overwrite = await expectClash\(req, rid\);[\s\S]{0,120}try \{/.test(CODE[R]));
check("P69724", "…and a clash answers clashJson, not a 500", () => has(R, /if \(overwrite\) return clashJson\(overwrite\)/));
check("P69725", "the GET catch answers panelFailure, so a busy database reads as busy", () => has(R, /return panelFailure\(e, \{ unknown: "Inventory read failed\." \}\)/));
check("P69726", "the POST catch answers panelFailure with its own sentence", () => has(R, /return panelFailure\(e, \{ unknown: "Inventory write failed\." \}\)/));
check("P69727", "a value the server refuses keeps its own words and a 400", () => has(R, /if \(e instanceof BadInput\) return err\(e\.message, 400\)/));
check("P69728", "…and BadInput is a class of its own, not a plain Error", () => has(R, /class BadInput extends Error \{\}/));
check("P69729", "the route is force-dynamic, so nothing here is ever cached", () => has(R, /export const dynamic = "force-dynamic"/));
check("P69730", "an unknown path answers 404 on both verbs", () => countOf(R, /Unknown inventory path\.", 404/g) === 2);

// ── A2 · never hand a database message to a panel (P69731–P69750) ───────────────────────────────
check("P69731", "a failed READ says the list didn't load, and keeps the real message on our side", () => has(R, /console\.error\(`\[inventory\] couldn't read \$\{what\}/) && has(R, /Couldn't load \$\{what\} — please try again\.`, 500\)/));
check("P69732", "a failed WRITE says nothing was changed, which is the part that matters", () => has(R, /Couldn't save \$\{what\} — nothing was changed\. Please try again\.`, 500\)/));
check("P69733", "…and logs the real message", () => has(R, /console\.error\(`\[inventory\] couldn't save \$\{what\}/));
check("P69734", "no branch answers a raw database message any more", () => !has(R, /err\([a-z]+\.error\.message/));
check("P69735", "…not even with a status attached", () => !has(R, /\.error\.message, 500\)/));
check("P69736", "readFail is used for every list read", () => countOf(R, /return readFail\(/g) >= 10);
check("P69737", "writeFail is used for every save", () => countOf(R, /return writeFail\(/g) >= 10);
check("P69738", "the two helpers are separate, because the two failures need different words", () => has(R, /const readFail =/) && has(R, /const writeFail =/));
check("P69739", "a duplicate ingredient name is a 409 with its own sentence, not a 500", () => countOf(R, /An ingredient with this name already exists\.", 409/g) === 2);
check("P69740", "a movement RPC error keeps its SQLSTATE, so busy and bad-value stay apart", () => has(R, /e\.code = r\.error\.code; e\.details = r\.error\.details; throw e/));
check("P69741", "…in postMovement", () => /const r = await sb\.rpc\("lfh_inv_post_movement"[\s\S]{0,400}e\.code = r\.error\.code/.test(CODE[R]));
check("P69742", "…and in production, which is the other RPC call", () => /lfh_inv_produce"[\s\S]{0,400}e\.code = r\.error\.code/.test(CODE[R]));
check("P69743", "a photo too large is a refusal with its own words, not a 500", () => has(R, /throw new BadInput\("That photo is too large \(max 8 MB\)/));
check("P69744", "a purchase line with no rate names the ingredient it belongs to", () => has(R, /throw new BadInput\(`Rate missing for \$\{it\.name\}\.`\)/));
check("P69745", "…and so does one with no quantity", () => has(R, /throw new BadInput\(`Quantity missing for \$\{it\.name\}\.`\)/));
check("P69746", "a line pointing at a deleted ingredient tells the person what to do", () => has(R, /BadInput\("One line refers to an ingredient that no longer exists — reopen the purchase and pick it again\."\)/));
check("P69747", "a bad id answers 400 and tells the person to refresh", () => has(R, /const badId = \(\) => err\("That item no longer exists — refresh the page\.", 400\)/));
check("P69748", "…and every id-taking branch calls it — all 11 of them", () => countOf(R, /return badId\(\)/g) === 11);
check("P69749", "the discard branch checks the write error BEFORE judging the row count", () => /counts" && path\[1\] && path\[2\] === "discard"[\s\S]{0,900}if \(up\.error\) return writeFail\("the discard", up\.error\);[\s\S]{0,120}if \(!up\.data\?\.length\)/.test(CODE[R]));
check("P69750", "no branch reports a database failure as a wrong-state refusal", () => !/if \(!up\.data\?\.length\) return err[\s\S]{0,120}\n\s*if \(up\.error\)/.test(CODE[R]));

// ── A3 · every read is scoped, column-listed and limited (P69751–P69790) ────────────────────────
const selects = [...CODE[R].matchAll(/\.from\("([a-z_]+)"\)\s*\n?\s*\.select\(([^)]*)\)/g)];
check("P69751", "every select names its table and its columns", () => selects.length >= 14);
check("P69752", "no select in this file uses *", () => !has(R, /\.select\("\*"\)/));
check("P69753", "the ingredient column list is a named constant, not typed twice", () => has(R, /const ITEM_COLS = "/));
check("P69754", "…and so is the purchase one", () => has(R, /const PURCHASE_COLS = "/));
check("P69755", "…and the expense one", () => has(R, /const EXPENSE_COLS = "/));
check("P69756", "…and the waste one", () => has(R, /const WASTE_COLS = "/));
check("P69757", "items are scoped to the restaurant and limited to 500", () => /from\("inv_items"\)\.select\(ITEM_COLS\)\.eq\("restaurant_id", rid\)[\s\S]{0,80}\.limit\(500\)/.test(CODE[R]));
check("P69758", "vendors are scoped and limited to 200", () => /from\("inv_vendors"\)[\s\S]{0,140}\.eq\("restaurant_id", rid\)[\s\S]{0,60}\.limit\(200\)/.test(CODE[R]));
check("P69759", "the purchase list's own limit is bounded to 100 whatever the caller asks", () => has(R, /Math\.min\(Math\.max\(num\(q\.get\("limit"\)\) \|\| 30, 1\), 100\)/));
check("P69760", "…and it is applied to the read", () => /from\("inv_purchases"\)\.select\(PURCHASE_COLS\)[\s\S]{0,120}\.limit\(lim\)/.test(CODE[R]));
check("P69761", "one purchase's lines are scoped and limited to 200", () => /from\("inv_purchase_lines"\)[\s\S]{0,200}\.eq\("purchase_id", path\[1\]\)\.limit\(200\)/.test(CODE[R]));
check("P69762", "the count list is limited to 30", () => /from\("inv_counts"\)[\s\S]{0,200}\.limit\(30\)/.test(CODE[R]));
check("P69763", "one count's lines are limited to 600", () => countOf(R, /\.limit\(600\)/g) >= 2);
check("P69764", "the waste window is bounded to 90 days whatever the caller asks", () => has(R, /Math\.min\(Math\.max\(num\(q\.get\("days"\)\) \|\| 30, 1\), 90\)/));
check("P69765", "…and the waste read is limited to 200 rows as well", () => /from\("inv_waste_entries"\)\.select\(WASTE_COLS\)[\s\S]{0,200}\.limit\(200\)/.test(CODE[R]));
check("P69766", "the expense month is validated against YYYY-MM before it reaches a query", () => has(R, /\/\^\\d\{4\}-\\d\{2\}\$\/\.test\(q\.get\("month"\) \|\| ""\)/));
check("P69767", "…and defaults to the current IST month, not the server's month", () => has(R, /: istToday\(\)\.slice\(0, 7\)/));
check("P69768", "the expense read is bounded by both ends of the month and limited to 300", () => /gte\("expense_date", from\)\.lte\("expense_date", to\)[\s\S]{0,200}\.limit\(300\)/.test(CODE[R]));
check("P69769", "the order list is scoped, active-only and limited to 500", () => /order-list[\s\S]{0,500}\.eq\("active", true\)\.not\("par_qty", "is", null\)\.limit\(500\)/.test(CODE[R]));
check("P69770", "the negative-stock list is limited to 100", () => /lt\("qty_base", 0\)\.limit\(100\)/.test(CODE[R]));
check("P69771", "the recipe read takes dishes and lines in ONE Promise.all", () => /recipes" && !path\[1\][\s\S]{0,200}Promise\.all\(\[/.test(CODE[R]));
check("P69772", "…and the recipe lines are limited to 3000", () => has(R, /\.limit\(3000\)/));
check("P69773", "the usage report is ONE SQL aggregate, never a client-side sum of the ledger", () => has(R, /sb\.rpc\("lfh_inv_usage_report"/));
check("P69774", "…and its window is bounded to 90 days", () => has(R, /num\(q\.get\("days"\)\) \|\| 7, 1\), 90\)/));
check("P69775", "the per-item ledger is limited to the newest 50 movements", () => /from\("inv_movements"\)[\s\S]{0,300}\.limit\(50\)/.test(CODE[R]));
check("P69776", "balances are read from the materialised inv_items columns", () => has(R, /qty_base/) && !has(R, /sum\(qty_base\)/i));
check("P69777", "…and the file says so at the top, so nobody 'improves' it into a sum", () => hasRaw(R, /never by summing inv_movements/));
check("P69778", "every .eq('restaurant_id', rid) is present on every table read", () => countOf(R, /\.eq\("restaurant_id", rid\)/g) >= 25);
check("P69779", "no read in this file is unscoped", () => selects.every((m) => /restaurant_id/.test(CODE[R].slice(m.index, m.index + 500))));
check("P69780", "the failed-lines read is an ERROR, never an empty list", () => has(R, /if \(lines\.error\) return readFail\("the recipes", lines\.error\)/));
check("P69781", "…and the reason is written beside it", () => hasRaw(R, /a well-meaning Save would wipe the real lines/));
check("P69782", "there is no polling in this route — it answers what it is asked", () => !has(R, /setInterval|setTimeout/));
check("P69783", "purchase photos are handed over as a short-lived signed link", () => countOf(R, /signRows\("inv-media"/g) >= 3);
check("P69784", "…and one purchase's photo too", () => has(R, /signOne\("inv-media"/));
check("P69785", "…and the permanent public URL never reaches a screen from a list read", () => !/return ok\(\{ purchases: r\.data/.test(CODE[R]));
check("P69786", "the expense totals are summed from the RAW rows, before signing rewrites a URL", () => /for \(const e of r\.data \|\| \[\]\)[\s\S]{0,300}signRows\("inv-media"/.test(CODE[R]));
check("P69787", "…and a struck-out expense is left out of the total", () => has(R, /if \(e\.voided_at\) continue;/));
check("P69788", "…while still being sent to the screen, so it stays visible", () => /expenses: await signRows\("inv-media", r\.data/.test(CODE[R]));
check("P69789", "the total is rounded to paise, not left as a float", () => has(R, /total: Math\.round\(total \* 100\) \/ 100/));
check("P69790", "the month the screen is showing is echoed back with the rows", () => /return ok\(\{ month, expenses:/.test(CODE[R]));

// ── A4 · the writes: ledger discipline and dedupe (P69791–P69850) ───────────────────────────────
check("P69791", "there is exactly ONE stock write path in this file", () => countOf(R, /sb\.rpc\("lfh_inv_post_movement"/g) === 1);
check("P69792", "…and every caller goes through it", () => countOf(R, /await postMovement\(\{/g) >= 6);
check("P69793", "every movement carries a caller-built dedupe key", () => countOf(R, /dedupe: `/g) >= 6);
check("P69794", "a purchase movement is keyed on the LINE id, so two lines cannot merge", () => has(R, /dedupe: `pur:\$\{pid\}:\$\{row\.id\}`/));
check("P69795", "…and it is built from the row it belongs to, not looked back up by item", () => has(R, /for \(const row of li\.data \|\| \[\]\)/) && !has(R, /lines\.find\(\(x\) => x\.item_id === row\.item_id\)/));
check("P69796", "…and the reason that lookup was wrong is written beside it", () => hasRaw(R, /key that is NOT unique on a purchase/));
check("P69797", "a void reverses each line, keyed on the line id", () => has(R, /dedupe: `purvoid:\$\{path\[1\]\}:\$\{l\.id\}`/));
check("P69798", "…at the line's OWN cost per base unit, not today's average", () => has(R, /const origCost = Number\(l\.qty_base\) > 0 \? Number\(l\.amount\) \/ Number\(l\.qty_base\) : 0/));
check("P69799", "a count adjustment is keyed on (count, item)", () => has(R, /dedupe: `cnt:\$\{path\[1\]\}:\$\{l\.item_id\}`/));
check("P69800", "a waste slip is keyed on its own row id", () => has(R, /dedupe: `waste:\$\{ins\.data\.id\}`/));
check("P69801", "…and undoing one restores at the cost it was recorded at", () => has(R, /unitCost: Number\(w\.unit_cost_snap\)/));
check("P69802", "opening stock is posted as a proper movement, not written into a balance", () => has(R, /kind: "opening", dedupe: `open:\$\{ins\.data\.id\}`/));
check("P69803", "nothing in this file edits a movement in place", () => !has(R, /from\("inv_movements"\)\.update/));
check("P69804", "…and nothing deletes one", () => !has(R, /from\("inv_movements"\)\.delete/));
check("P69805", "a void is a soft strike-out with a reason, never a delete", () => countOf(R, /voided_at: new Date\(\)\.toISOString\(\)/g) >= 3);
check("P69806", "…and every void refuses without a reason", () => countOf(R, /A reason is required/g) >= 3);
check("P69807", "…and records who struck it out", () => countOf(R, /voided_by: actor/g) >= 3);
check("P69808", "a void that has already happened answers 404, not a second reversal", () => countOf(R, /\.is\("voided_at", null\)/g) >= 3);
check("P69809", "a batch of a prep item is ONE database call, so it lands whole or not at all", () => has(R, /sb\.rpc\("lfh_inv_produce"/));
check("P69810", "…and it is no longer fanned out into N+1 movement calls from here", () => !/production"[\s\S]{0,600}for \(const/.test(CODE[R]));
check("P69811", "…and the reason is written beside it", () => hasRaw(R, /ONE ACTION, ONE TRANSACTION, ONE IDENTITY/));
check("P69812", "a batch carries the panel's own action id, so a retry is recognised", () => has(R, /p_attempt: req\.headers\.get\("x-lfh-action-id"\)/));
check("P69813", "a replay of the same batch writes no second diary line", () => has(R, /if \(!out\.replay\) \{/));
check("P69814", "…and tells the screen it was already made", () => has(R, /alreadyMade: out\.replay === true/));
check("P69815", "each refusal from the batch RPC gets its own sentence", () => has(R, /item_not_found"[\s\S]{0,40}Ingredient not found/) && has(R, /no_recipe"[\s\S]{0,60}no prep recipe yet/));
check("P69816", "…and a missing item is a 404 while a bad quantity is a 400", () => has(R, /out\.reason === "item_not_found" \? 404 : 400/));
check("P69817", "a recipe save dedupes its lines server-side, last one wins", () => has(R, /const byItem = new Map<string, number>\(\)/));
check("P69818", "…and the reason is written beside it", () => hasRaw(R, /the UNIQUE index would fail the\s*\n?\/\/ insert AFTER the old lines were deleted — a wiped recipe/));
check("P69819", "…and never trusts the screen to have done it", () => hasRaw(R, /Never trust the UI/));
check("P69820", "a recipe is capped at 60 ingredients", () => has(R, /if \(byItem\.size > 60\) return err\("Too many ingredients \(max 60\)\."\)/));
check("P69821", "a prep recipe may not contain itself", () => has(R, /if \(ids\.includes\(ownerKey\)\) return err\("A prep recipe can't contain itself\."\)/));
check("P69822", "every recipe line is validated against THIS restaurant's ingredients", () => /from\("inv_items"\)\.select\("id"\)\.eq\("restaurant_id", rid\)\.in\("id", ids\)/.test(CODE[R]));
check("P69823", "…and a line naming an unknown one is refused before anything is written", () => /!== ids\.length\) return err\("A line refers to an unknown ingredient\."\)[\s\S]{0,900}from\("inv_recipe_lines"\)\.delete\(\)/.test(CODE[R]));
check("P69824", "a dish recipe checks the dish exists in this restaurant", () => /from\("menu_items"\)\.select\("slug"\)\.eq\("restaurant_id", rid\)\.eq\("slug", ownerKey\)/.test(CODE[R]));
check("P69825", "a prep recipe checks the prep ingredient exists in this restaurant", () => /from\("inv_items"\)\.select\("id"\)\.eq\("restaurant_id", rid\)\.eq\("id", ownerKey\)/.test(CODE[R]));
check("P69826", "…and refuses a batch size that is not a number", () => has(R, /Say how much one batch makes\./));
check("P69827", "the base unit cannot change once an ingredient has stock history", () => has(R, /its base unit can't change\. Make a new ingredient instead\./));
check("P69828", "…and the check reads the movements, not a flag", () => /from\("inv_movements"\)\.select\("id"\)[\s\S]{0,120}\.limit\(1\)/.test(CODE[R]));
check("P69829", "a base unit is one of exactly three, and anything else falls back", () => has(R, /const VALID_UOMS = new Set\(\["g", "ml", "pc"\]\)/));
check("P69830", "an expense category must be one of the eight the screen offers", () => has(R, /const EXPENSE_CATS = new Set\(\["breakage", "repair", "utilities", "cleaning", "supplies", "rent", "transport", "misc"\]\)/));
check("P69831", "a waste reason must be one of the seven", () => has(R, /const WASTE_REASONS = new Set\(\["spoiled", "burnt", "spilled", "expired", "staff_meal", "complimentary", "other"\]\)/));
check("P69832", "zero is not an amount for an expense", () => has(R, /amount <= 0/));
check("P69833", "…and neither is ten million", () => has(R, /amount > 10_000_000/));
check("P69834", "…and the reason zero had to be refused is written beside it", () => hasRaw(R, /ZERO IS NOT AN AMOUNT/));
check("P69835", "an expense with no description is refused with an example", () => has(R, /Say what it was \(e\.g\. “Bar lamp broken”\)\./));
check("P69836", "an expense date is validated as a date, and defaults to today in IST", () => has(R, /isDate\(body\.expense_date\) \? body\.expense_date : istToday\(\)/));
check("P69837", "a purchase is at least one line and at most a hundred", () => has(R, /if \(!rawLines\.length \|\| rawLines\.length > 100\) return err\("Add at least one line \(max 100\)\."\)/));
check("P69838", "every purchase line's items are resolved in ONE scoped select", () => /const ids = \[\.\.\.new Set\(rawLines\.map/.test(CODE[R]));
check("P69839", "a spend-only ingredient never holds stock", () => has(R, /it\.track_level === "EXPENSE"\) continue;/));
check("P69840", "line amounts are rounded to paise as they are computed", () => has(R, /const amount = Math\.round\(qty \* rate \* 100\) \/ 100/));
check("P69841", "…and the subtotal is rounded once at the end", () => has(R, /subtotal = Math\.round\(subtotal \* 100\) \/ 100/));
check("P69842", "…and the bill total is subtotal plus tax, rounded", () => has(R, /total: Math\.round\(\(subtotal \+ tax\) \* 100\) \/ 100/));
check("P69843", "a negative tax is treated as no tax rather than accepted", () => has(R, /num\(body\.tax\) >= 0 \? num\(body\.tax\) : 0/));
check("P69844", "a count line is refused below zero", () => has(R, /counted < 0\) return err\("Bad count line\."\)/));
check("P69845", "a count that is not a draft refuses a new line with 409", () => has(R, /This count is no longer open\.", 409/));
check("P69846", "…and a second submit answers 409 too", () => has(R, /This count was already submitted\.", 409/));
check("P69847", "a count line re-saved replaces the old one on (count, item)", () => has(R, /onConflict: "count_id,item_id"/));
check("P69848", "a submit with no lines is refused before anything is adjusted", () => has(R, /Count at least one item before submitting\./));
check("P69849", "a submit adjusts against the LIVE balance, not the snapshot", () => hasRaw(R, /Adjust against the LIVE balance at submit/));
check("P69850", "…and skips a line whose difference is smaller than a ten-thousandth", () => has(R, /if \(Math\.abs\(delta\) < 0\.0001\) continue;/));

// ── A5 · what it records, and the arithmetic (P69851–P69880) ────────────────────────────────────
check("P69851", "every write that a person would ask about later writes an Activity line", () => countOf(R, /await logAction\("manager", /g) >= 7);
check("P69852", "an expense line names the category, the title and the amount", () => has(R, /detail: `\$\{category\}: \$\{title\} — ₹\$\{amount\}`/));
check("P69853", "a struck-out expense names what it was and why", () => has(R, /detail: `\$\{up\.data\[0\]\.title\}: \$\{reason\}`/));
check("P69854", "a purchase says whether it was a bill or a cash buy", () => has(R, /kind === "cash" \? "Cash buy" : /));
check("P69855", "…and names the supplier when there is one", () => has(R, /vendor_name \? ` — \$\{vendor_name\}` : ""/));
check("P69856", "a count submit records how many were counted and how many moved", () => has(R, /\$\{lines\.data\.length\} items counted, \$\{adjusted\} adjusted/));
check("P69857", "a waste line records the reason and the money it cost", () => has(R, /detail: `\$\{reason\} — ₹\$\{Math\.round\(qty \* Number\(it\.data\.avg_cost\) \* 100\) \/ 100\}`/));
check("P69858", "a batch records the ingredient, the quantity and the cost", () => has(R, /batch of \$\{madeBase\} \(₹\$\{Number\(out\.cost\) \|\| 0\}\)/));
check("P69859", "a recipe save records which recipe and how many ingredients", () => has(R, /\$\{ownerType\} \$\{ownerKey\}: \$\{lines\.length\} ingredients/));
check("P69860", "…and every log line carries the restaurant, the actor and the actor id", () => countOf(R, /restaurant_id: rid, actor, actor_id: actorId/g) >= 7);
check("P69861", "the order list suggests in PURCHASE units, not base units", () => has(R, /needBase \/ Number\(i\.purchase_factor\)/));
check("P69862", "…rounded UP, to one decimal, because you cannot buy nine tenths of a crate", () => has(R, /Math\.ceil\(\(needBase \/ Number\(i\.purchase_factor\)\) \* 10\) \/ 10/));
check("P69863", "…and only for ingredients actually below par", () => has(R, /Number\(i\.qty_base\) < Number\(i\.par_qty\)/));
check("P69864", "urgent means at or below the minimum, and it sorts first", () => has(R, /urgent: i\.min_qty != null && Number\(i\.qty_base\) <= Number\(i\.min_qty\)/));
check("P69865", "…and equal urgency falls back to the ingredient's name", () => has(R, /Number\(b\.urgent\) - Number\(a\.urgent\) \|\| a\.name\.localeCompare\(b\.name\)/));
check("P69866", "opening stock is valued at the purchase rate divided by the factor", () => has(R, /num\(body\.last_rate\) \/ purchase_factor : 0/));
check("P69867", "…and only when the factor is above zero", () => has(R, /purchase_factor > 0 \?/));
check("P69868", "a purchase movement's unit cost is the rate divided by the factor", () => has(R, /unitCost: factor > 0 \? rate \/ factor : 0/));
check("P69869", "last_rate ends on the LAST line's rate — the most recent price paid", () => hasRaw(R, /last_rate` now ends on the LAST line's rate/));
check("P69870", "a dish title falls back sensibly when the multilingual field is odd", () => has(R, /\.en \|\| Object\.values\(d\.title as Record<string, string>\)\[0\]/));
check("P69871", "…and to the slug when there is no title at all", () => has(R, /String\(d\.title \|\| d\.slug\)/));
check("P69872", "a dish price that will not parse becomes zero, never NaN", () => has(R, /price: Number\(d\.price\) \|\| 0/));
check("P69873", "num() returns NaN for anything unparseable, and every caller tests it", () => has(R, /return Number\.isFinite\(n\) \? n : NaN/));
check("P69874", "…so no branch writes a NaN into the database", () => countOf(R, /Number\.isFinite\(num\(/g) >= 8);
check("P69875", "a date is only accepted in YYYY-MM-DD", () => has(R, /const isDate = \(v: unknown\) => typeof v === "string" && \/\^\\d\{4\}-\\d\{2\}-\\d\{2\}\$\//));
check("P69876", "today means today in India, not on the server", () => has(R, /Date\.now\(\) \+ 5\.5 \* 3600_000/));
check("P69877", "the last day of an expense month is computed, not assumed to be the 30th", () => has(R, /new Date\(Date\.UTC\(\+month\.slice\(0, 4\), \+month\.slice\(5, 7\), 0\)\)/));
check("P69878", "every free-text field is length-capped before it is stored", () => countOf(R, /\.slice\(0, \d+\)/g) >= 18);
check("P69879", "an uploaded file's extension is sanitised to letters and digits", () => has(R, /\.replace\(\/\[\^a-z0-9\]\/gi, ""\)\.slice\(0, 5\) \|\| "jpg"/));
check("P69880", "…and its stored path begins with the restaurant's own id", () => has(R, /const path = `\$\{rid\}\/\$\{Date\.now\(\)\}-/));

// ── A6 · the issue-media upload (P69881–P69900) ─────────────────────────────────────────────────
check("P69881", "the upload is a route of its own, because a file body is not JSON", () => hasRaw(M, /Multipart, so it lives in its OWN route/));
check("P69882", "a signed-in staff member is checked first", () => /userFromCookie\(req\.cookies\.get\(USER_COOKIE\)\?\.value\)[\s\S]{0,600}tokenIsValid/.test(CODE[M]));
check("P69883", "a database blip answers 503 + busy, never 'please log in'", () => has(M, /status: 503, headers: \{ "X-LFH-Busy": "1" \}/));
check("P69884", "…and only for AuthDbError; a bad cookie still falls through", () => has(M, /if \(e instanceof AuthDbError\)/));
check("P69885", "…and the busy sentence is the shared one", () => has(M, /error: BUSY_MESSAGE, busy: true/));
check("P69886", "the admin check is AWAITED — without it the 401 was unreachable", () => has(M, /const isAdmin = await tokenIsValid\(/));
check("P69887", "…and the reason that await matters is written beside it", () => hasRaw(M, /`await` MATTERS HERE and its absence made this gate a no-op/));
check("P69888", "nobody at all is refused 401", () => has(M, /if \(!staff && !isAdmin\) return bad\("Not authorised — please log in\.", 401\)/));
check("P69889", "the restaurant comes from the session, never from the body", () => has(M, /panelRestaurantId\(req, \{ user: staff \}\)/));
check("P69890", "…and there is no read of a restaurant id out of the form", () => !has(M, /form\?\.get\("rid"\)|form\?\.get\("restaurant/));
check("P69891", "no scope answers 400 and says how to open the panel properly", () => has(M, /No restaurant scope — open this panel from the admin console\.", 400/));
check("P69892", "…and R48 protects that sentence too", () => hasRaw(M, /R48\. "No restaurant scope" STAYS/));
check("P69893", "a body that is not a form is caught rather than thrown", () => has(M, /await req\.formData\(\)\.catch\(\(\) => null\)/));
check("P69894", "a missing file is a 400 with plain words", () => has(M, /if \(!\(file instanceof File\)\) return bad\("Missing file\."\)/));
check("P69895", "…and it must really be a File, not a text field named file", () => has(M, /file instanceof File/));
check("P69896", "the kind must be image or audio, nothing else", () => has(M, /if \(kind !== "image" && kind !== "audio"\) return bad\("Unknown attachment kind\."\)/));
check("P69897", "storing is delegated to lib/issues, so one place owns the bucket", () => has(M, /await storeIssueMedia\(rid, file, kind\)/));
check("P69898", "a failure to store answers 400 with the reason, not a 500", () => has(M, /return bad\(e instanceof Error \? e\.message : "Upload failed\.", 400\)/));
check("P69899", "the reply names the url and the kind back to the panel", () => has(M, /NextResponse\.json\(\{ ok: true, url, kind \}\)/));
check("P69900", "the route is force-dynamic and has no GET at all", () => has(M, /export const dynamic = "force-dynamic"/) && !has(M, /export async function GET/));

const bad = results.filter((r) => r.res !== "✅");
console.log(`BLOCK A · ${count()} checks · ${results.length - bad.length} ✅ · ${bad.length} not-green`);
for (const b of bad) console.log(`  ${b.res} ${b.id} — ${b.what}`);

try {
  const { writeFileSync: __w, mkdirSync: __m } = await import("node:fs");
  __m(".claude/sweep/t16-rows", { recursive: true });
  __w(".claude/sweep/t16-rows/A.json", JSON.stringify(results, null, 1));
} catch (e) { console.error("could not write rows:", e.message); }
