// scripts/sweep/t13s10/new-a-libs.mjs — sweep #10 T13, new checks block A: the three THINNEST files.
//   lib/liveBoard.ts     — 1 row by subject in the whole ledger before this run, 0 of them driven
//   lib/cancelWatch.ts   — 2 rows, 0 driven
//   lib/floorSummary.ts  — 7 rows, 1 driven (in memory)
// Every check here CALLS the real function (bundled, against the stubs). Static reads are used only
// where the property is a fact about the source itself, and say so.
import { check, bundle, world, call, SRC, CODE, RID, RID2, rd } from "./lib.mjs";

let n = 182001;
// IN-MEMORY waiter sections — nothing real is written, no restaurant's rota moves.
const SEC_1 = [1], SEC_2_3 = [2, 3];
const id = () => `P${n++}`;
const LBF = "lib/liveBoard.ts", CWF = "lib/cancelWatch.ts", FSF = "lib/floorSummary.ts";
const LB = () => bundle("lib/liveBoard.ts");
const BD = () => bundle("lib/businessDay.ts");
const CW = () => bundle("lib/cancelWatch.ts", ["--alias:@/lib/alerts=./scripts/sweep/t13s10/stubs/alerts.mjs"]);
const FS = () => bundle("lib/floorSummary.ts");
const since = () => BD().businessDayStartIso();
const iso = (ms) => new Date(ms).toISOString();
const NOW = () => Date.now();
const today = () => iso(Math.max(new Date(since()).getTime() + 60_000, NOW() - 60_000));
const old = () => iso(new Date(since()).getTime() - 2 * 86400e3);
const ord = (o) => ({ restaurant_id: RID, status: "preparing", payment_status: "pending", archived: false, deleted_at: null, created_at: today(), ...o });
const itm = (o) => ({ restaurant_id: RID, status: "preparing", created_at: today(), ...o });
const ids = (rows) => rows.map((r) => r.id).join(",");

// ════════ lib/liveBoard.ts — 60 ═══════════════════════════════════════════════════════════════════
const how = "STUB — real liveOrdersAndItems, in memory";
check(id(), LBF, "the full board returns today's orders for THIS restaurant only", how, async () => { await world({ fix: { orders: [ord({ id: "a" }), ord({ id: "b", restaurant_id: RID2 })] } }); const r = await LB().liveOrdersAndItems(RID); return { ok: ids(r.orders) === "a", note: ids(r.orders) }; });
check(id(), LBF, "an archived (parked / restarted) order is not on the board", how, async () => { await world({ fix: { orders: [ord({ id: "a" }), ord({ id: "b", archived: true })] } }); return ids((await LB().liveOrdersAndItems(RID)).orders) === "a"; });
check(id(), LBF, "a soft-deleted order is not on the board", how, async () => { await world({ fix: { orders: [ord({ id: "a" }), ord({ id: "b", deleted_at: today() })] } }); return ids((await LB().liveOrdersAndItems(RID)).orders) === "a"; });
check(id(), LBF, "an order from before the 05:00 rollover on a CLOSED table is not on the board", how, async () => { await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "closed", created_at: old() }], orders: [ord({ id: "a", session_id: "s", created_at: old() })] } }); return (await LB().liveOrdersAndItems(RID)).orders.length === 0; });
check(id(), LBF, "an order from before the rollover on a table STILL OPEN stays on the board (the overnight Table 13)", how, async () => { await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "open", created_at: old() }], orders: [ord({ id: "a", session_id: "s", created_at: old() })] } }); return ids((await LB().liveOrdersAndItems(RID)).orders) === "a"; });
check(id(), LBF, "another restaurant's overnight open table never reaches this board", how, async () => { await world({ fix: { sessions: [{ id: "s", restaurant_id: RID2, status: "open", created_at: old() }], orders: [ord({ id: "a", restaurant_id: RID2, session_id: "s", created_at: old() })] } }); return (await LB().liveOrdersAndItems(RID)).orders.length === 0; });
check(id(), LBF, "a targeted read returns only the named table", how, async () => { await world({ fix: { orders: [ord({ id: "a", table_number: "3" }), ord({ id: "b", table_number: "4" })] } }); return ids((await LB().liveOrdersAndItems(RID, ["4"])).orders) === "b"; });
check(id(), LBF, "a targeted read for two tables returns both and nothing else", how, async () => { await world({ fix: { orders: ["3", "4", "5"].map((t) => ord({ id: "o" + t, table_number: t })) } }); return ids((await LB().liveOrdersAndItems(RID, ["3", "5"])).orders) === "o3,o5"; });
check(id(), LBF, "an EMPTY table list means the full board, not an empty one", how, async () => { await world({ fix: { orders: ["3", "4"].map((t) => ord({ id: "o" + t, table_number: t })) } }); return (await LB().liveOrdersAndItems(RID, [])).orders.length === 2; });
check(id(), LBF, "a targeted read's dishes are exactly the dishes of the orders it returned", how, async () => { await world({ fix: { orders: [ord({ id: "a", table_number: "3" }), ord({ id: "b", table_number: "4" })], order_items: [itm({ id: "i1", order_id: "a" }), itm({ id: "i2", order_id: "b" })] } }); return ids((await LB().liveOrdersAndItems(RID, ["3"])).items) === "i1"; });
check(id(), LBF, "a targeted read of an empty table asks for no dishes at all", how, async () => { const G = await world({ fix: { order_items: [itm({ id: "i1", order_id: "x" })] } }); const r = await LB().liveOrdersAndItems(RID, ["9"]); return { ok: r.items.length === 0 && !G.READS.some((x) => x.table === "order_items"), note: `${G.READS.filter((x) => x.table === "order_items").length} dish read(s)` }; });
check(id(), LBF, "the kitchen's active-only board drops served and cancelled orders", how, async () => { await world({ fix: { orders: ["received", "preparing", "served", "cancelled"].map((s) => ord({ id: s, status: s })) } }); return ids((await LB().liveOrdersAndItems(RID, undefined, true)).orders) === "preparing,received" || ids((await LB().liveOrdersAndItems(RID, undefined, true)).orders).split(",").sort().join() === "preparing,received"; });
check(id(), LBF, "…and ships dishes only for the orders still on the pass", how, async () => { await world({ fix: { orders: [ord({ id: "a", status: "preparing" }), ord({ id: "b", status: "served" })], order_items: [itm({ id: "i1", order_id: "a" }), itm({ id: "i2", order_id: "b" })] } }); return ids((await LB().liveOrdersAndItems(RID, undefined, true)).items) === "i1"; });
check(id(), LBF, "…and an empty pass asks for no dishes", how, async () => { const G = await world({ fix: { orders: [ord({ id: "b", status: "served" })] } }); const r = await LB().liveOrdersAndItems(RID, undefined, true); return r.items.length === 0 && !G.READS.some((x) => x.table === "order_items"); });
check(id(), LBF, "the waiter's full board keeps SERVED orders (a bill needs them)", how, async () => { await world({ fix: { orders: [ord({ id: "a", status: "served" })] } }); return (await LB().liveOrdersAndItems(RID)).orders.length === 1; });
check(id(), LBF, "the full board carries today's dishes", how, async () => { await world({ fix: { orders: [ord({ id: "a" })], order_items: [itm({ id: "i1", order_id: "a" })] } }); return ids((await LB().liveOrdersAndItems(RID)).items) === "i1"; });
check(id(), LBF, "the full board carries the dishes of an overnight open table's old orders too", how, async () => { await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "open", created_at: old() }], orders: [ord({ id: "a", session_id: "s", created_at: old() })], order_items: [itm({ id: "i1", order_id: "a", created_at: old() })] } }); return ids((await LB().liveOrdersAndItems(RID)).items) === "i1"; });
check(id(), LBF, "an old dish of a CLOSED table's order is not carried", how, async () => { await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "closed", created_at: old() }], orders: [ord({ id: "a", session_id: "s", created_at: old() })], order_items: [itm({ id: "i1", order_id: "a", created_at: old() })] } }); return (await LB().liveOrdersAndItems(RID)).items.length === 0; });
check(id(), LBF, "another restaurant's dishes never ride along", how, async () => { await world({ fix: { orders: [ord({ id: "a" })], order_items: [itm({ id: "i1", order_id: "a" }), itm({ id: "i2", order_id: "a", restaurant_id: RID2 })] } }); return ids((await LB().liveOrdersAndItems(RID)).items) === "i1"; });
check(id(), LBF, "orders come back oldest first", how, async () => { const t0 = new Date(since()).getTime() + 3600e3; await world({ fix: { orders: [ord({ id: "z", created_at: iso(t0 + 2000) }), ord({ id: "y", created_at: iso(t0) })] } }); return ids((await LB().liveOrdersAndItems(RID)).orders) === "y,z"; });
check(id(), LBF, "two orders in the same millisecond are ordered by id, so the board never reshuffles", how, async () => { const t = iso(new Date(since()).getTime() + 3600e3); await world({ fix: { orders: [ord({ id: "b", created_at: t }), ord({ id: "a", created_at: t })] } }); return ids((await LB().liveOrdersAndItems(RID)).orders) === "a,b"; });
check(id(), LBF, "a dish reached by two passes appears ONCE", how, async () => { await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "open", created_at: old() }], orders: [ord({ id: "a", session_id: "s", created_at: old() })], order_items: [itm({ id: "i1", order_id: "a" })] } }); return ids((await LB().liveOrdersAndItems(RID)).items) === "i1"; });
check(id(), LBF, "a board past PostgREST's 1,000-row page is COMPLETE (2,500 orders → 2,500)", how, async () => { await world({ fix: { orders: Array.from({ length: 2500 }, (_, i) => ord({ id: `o${String(i).padStart(5, "0")}` })) } }); const r = await LB().liveOrdersAndItems(RID); return { ok: r.orders.length === 2500, note: `${r.orders.length}` }; });
check(id(), LBF, "exactly 1,000 orders costs one more (empty) page, and none is lost", how, async () => { const G = await world({ fix: { orders: Array.from({ length: 1000 }, (_, i) => ord({ id: `o${String(i).padStart(5, "0")}` })) } }); const r = await LB().liveOrdersAndItems(RID); const pages = G.READS.filter((x) => x.table === "orders").length; return { ok: r.orders.length === 1000 && pages === 2, note: `${r.orders.length} orders, ${pages} order pages` }; });
check(id(), LBF, "the runaway cap stops at 20,000 rows and SAYS so in the log (never silent)", how, async () => {
  await world({ fix: { orders: Array.from({ length: 20500 }, (_, i) => ord({ id: `o${String(i).padStart(6, "0")}` })) } });
  const errs = []; const orig = console.error; console.error = (...a) => errs.push(a.join(" "));
  try { const r = await LB().liveOrdersAndItems(RID); return { ok: r.orders.length === 20000 && errs.some((e) => /MAX_PAGES/.test(e)), note: `${r.orders.length} rows, logged: ${errs.length}` }; } finally { console.error = orig; }
});
check(id(), LBF, "400 overnight open tables are read in id chunks of 150, never one giant URL", how, async () => {
  const sessions = Array.from({ length: 400 }, (_, i) => ({ id: `s${i}`, restaurant_id: RID, status: "open", created_at: old() }));
  const G = await world({ fix: { sessions, orders: [] } });
  await LB().liveOrdersAndItems(RID);
  const chunked = G.SCOPE_LOG.filter((q) => q.table === "orders" && q.filters.some((f) => f.kind === "in" && f.col === "session_id"));
  const sizes = chunked.map((q) => q.filters.find((f) => f.col === "session_id").val.length);
  return { ok: chunked.length === 3 && Math.max(...sizes) <= 150, note: `${chunked.length} chunk reads, sizes ${sizes.join("/")}` };
});
check(id(), LBF, "chunks run at most six at a time (the connection budget)", "SRC", () => /const CHUNK_CONCURRENCY = 6;/.test(CODE.liveBoard) && /mapLimit\(chunkIds\(openIds\), CHUNK_CONCURRENCY/.test(CODE.liveBoard));
check(id(), LBF, "an id chunk is 150 (≈5.5 KB of URL, far under the 18 KB that still worked)", "SRC", () => /const ID_CHUNK = 150;/.test(CODE.liveBoard));
check(id(), LBF, "the open-tables read is bounded at 2,000", "SRC", () => /\.lt\("created_at", since\)\.limit\(2000\)/.test(CODE.liveBoard));
check(id(), LBF, "a failed open-tables read THROWS (the route answers it) instead of drawing a half board", how, async () => { await world({ fail: { "sessions:select": "error" } }); try { await LB().liveOrdersAndItems(RID); return false; } catch (e) { return { ok: /failed/.test(e.message), note: e.message }; } });
check(id(), LBF, "a failed orders page THROWS", how, async () => { await world({ fail: { "orders:select": "error" } }); try { await LB().liveOrdersAndItems(RID); return false; } catch { return true; } });
check(id(), LBF, "a failed dishes page THROWS", how, async () => { await world({ fix: { orders: [ord({ id: "a" })] }, fail: { "order_items:select": "error" } }); try { await LB().liveOrdersAndItems(RID); return false; } catch { return true; } });
check(id(), LBF, "the order columns carry the MRP / tax-inclusive split the waiter's due needs (269/271)", "SRC", () => /taxable_base, nontax_amount, mrp_amount/.test(CODE.liveBoard));
check(id(), LBF, "the order columns carry `archived`, so the waiter's second-line check is a real check", "SRC", () => /ORDER_COLS =\s*"[^"]*\barchived\b/.test(CODE.liveBoard));
check(id(), LBF, "the order columns carry who punched it (placed_by_id, placed_by) for the kitchen's chime", "SRC", () => /placed_by_id, placed_by"/.test(CODE.liveBoard));
check(id(), LBF, "the dish columns carry tax_mode and is_mrp", "SRC", () => /ITEM_COLS =\s*"[^"]*tax_mode, is_mrp"/.test(CODE.liveBoard));
check(id(), LBF, "`edited_at` is deliberately NOT selected (no panel draws the badge from here)", "SRC", () => !/edited_at/.test((CODE.liveBoard.match(/ORDER_COLS =[\s\S]*?ITEM_COLS =\s*"[^"]*"/) || [""])[0]));
check(id(), LBF, "a table number given as a NUMBER still targets that table", how, async () => { await world({ fix: { orders: [ord({ id: "a", table_number: "3" })] } }); return (await LB().liveOrdersAndItems(RID, [3])).orders.length === 1; });
check(id(), LBF, "stripPlacedBy removes both who-punched-it fields", how, () => { const r = LB().stripPlacedBy([{ id: "a", placed_by: "Ann", placed_by_id: "u" }]); return !("placed_by" in r[0]) && !("placed_by_id" in r[0]); });
check(id(), LBF, "stripPlacedBy(…, true) marks a GUEST's own order with guest:1", how, () => LB().stripPlacedBy([{ id: "a", placed_by: null, placed_by_id: null }], true)[0].guest === 1);
check(id(), LBF, "…and never marks a waiter-punched order", how, () => !("guest" in LB().stripPlacedBy([{ id: "a", placed_by: "Ann", placed_by_id: "u" }], true)[0]));
check(id(), LBF, "…and a name with no id still counts as staff (not a guest)", how, () => !("guest" in LB().stripPlacedBy([{ id: "a", placed_by: "Ann", placed_by_id: null }], true)[0]));
check(id(), LBF, "…and an id with no name still counts as staff", how, () => !("guest" in LB().stripPlacedBy([{ id: "a", placed_by: null, placed_by_id: "u" }], true)[0]));
check(id(), LBF, "the tablet's call (no flag) adds no guest key at all — its payload is unchanged", how, () => !("guest" in LB().stripPlacedBy([{ id: "a" }])[0]));
check(id(), LBF, "stripPlacedBy(null) is an empty list, not a crash", how, () => Array.isArray(LB().stripPlacedBy(null)) && LB().stripPlacedBy(null).length === 0);
check(id(), LBF, "stripPlacedBy never edits the rows it was handed", how, () => { const row = { id: "a", placed_by: "Ann" }; LB().stripPlacedBy([row]); return row.placed_by === "Ann"; });
check(id(), LBF, "the kitchen's active statuses are exactly received + preparing (there is no 'ready' order status)", "SRC", () => /const KITCHEN_ACTIVE_STATUSES = \["received", "preparing"\];/.test(CODE.liveBoard));
check(id(), LBF, "the waiter tablet asks for its slice WITHOUT the kitchen's active-only flag", "SRC", () => /liveOrdersAndItems\(rid, \[tbl\]\)/.test(CODE.route));
check(id(), LBF, "every statement one board read makes names this restaurant", how, async () => { const G = await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "open", created_at: old() }], orders: [ord({ id: "a", session_id: "s", created_at: old() }), ord({ id: "b" })], order_items: [itm({ id: "i1", order_id: "a" })] } }); await LB().liveOrdersAndItems(RID); const bad = G.SCOPE_LOG.filter((q) => !q.filters.some((f) => f.col === "restaurant_id" && f.val === RID)); return { ok: G.SCOPE_LOG.length >= 4 && !bad.length, note: `${G.SCOPE_LOG.length} statements, ${bad.length} unscoped` }; });
check(id(), LBF, "the open-tables read asks for OPEN tables opened BEFORE today only", how, async () => { const G = await world(); await LB().liveOrdersAndItems(RID); const q = G.SCOPE_LOG.find((x) => x.table === "sessions"); return q.filters.some((f) => f.col === "status" && f.val === "open") && q.filters.some((f) => f.kind === "lt" && f.col === "created_at"); });
check(id(), LBF, "every orders statement filters archived=false and deleted_at IS NULL", how, async () => { const G = await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "open", created_at: old() }] } }); await LB().liveOrdersAndItems(RID); const qs = G.SCOPE_LOG.filter((x) => x.table === "orders"); return qs.length >= 2 && qs.every((q) => q.filters.some((f) => f.col === "archived" && f.val === false) && q.filters.some((f) => f.kind === "is" && f.col === "deleted_at")); });
check(id(), LBF, "an order stamped exactly at the 05:00 business-day start counts as today", how, async () => { await world({ fix: { orders: [ord({ id: "a", created_at: since() })] } }); return (await LB().liveOrdersAndItems(RID)).orders.length === 1; });
check(id(), LBF, "an order one millisecond before the rollover, on a closed table, does not", how, async () => { await world({ fix: { orders: [ord({ id: "a", created_at: iso(new Date(since()).getTime() - 1) })] } }); return (await LB().liveOrdersAndItems(RID)).orders.length === 0; });
check(id(), LBF, "an old order with no table session at all is not kept by the open-table arm", how, async () => { await world({ fix: { orders: [ord({ id: "a", session_id: null, created_at: old() })] } }); return (await LB().liveOrdersAndItems(RID)).orders.length === 0; });
check(id(), LBF, "an empty restaurant gets an empty board, not an error", how, async () => { await world(); const r = await LB().liveOrdersAndItems(RID); return r.orders.length === 0 && r.items.length === 0; });
check(id(), LBF, "columns the helper does not touch pass through untouched (kot_no, items, total)", how, async () => { await world({ fix: { orders: [ord({ id: "a", kot_no: 7, total: 210, items: [{ t: 1 }] })] } }); const o = (await LB().liveOrdersAndItems(RID)).orders[0]; return o.kot_no === 7 && o.total === 210 && Array.isArray(o.items); });
check(id(), LBF, "the fan-out is the SHARED lib/mapLimit, not a private copy", "SRC", () => /import \{ mapLimit \} from "@\/lib\/mapLimit";/.test(SRC.liveBoard) && !/function mapLimit/.test(CODE.liveBoard));
check(id(), LBF, "the pager is named pageBoard (it THROWS on a failed page), never confused with lib/pageAll", "SRC", () => /async function pageBoard/.test(CODE.liveBoard) && !/pageAll\(/.test(CODE.liveBoard));
check(id(), LBF, "a targeted read of 200 orders fetches their dishes in two id chunks", how, async () => { const G = await world({ fix: { orders: Array.from({ length: 200 }, (_, i) => ord({ id: `o${String(i).padStart(4, "0")}`, table_number: "3" })) } }); await LB().liveOrdersAndItems(RID, ["3"]); const c = G.SCOPE_LOG.filter((q) => q.table === "order_items" && q.filters.some((f) => f.kind === "in" && f.col === "order_id")); return { ok: c.length === 2, note: `${c.length} dish chunk reads` }; });
check(id(), LBF, "200 overnight orders fetch their dishes in two id chunks too", how, async () => { const G = await world({ fix: { sessions: [{ id: "s", restaurant_id: RID, status: "open", created_at: old() }], orders: Array.from({ length: 200 }, (_, i) => ord({ id: `o${String(i).padStart(4, "0")}`, session_id: "s", created_at: old() })) } }); await LB().liveOrdersAndItems(RID); const c = G.SCOPE_LOG.filter((q) => q.table === "order_items" && q.filters.some((f) => f.kind === "in" && f.col === "order_id")); return { ok: c.length === 2, note: `${c.length} dish chunk reads` }; });
check(id(), LBF, "every paged read is ordered created_at THEN id (a stable page boundary)", "SRC", () => (CODE.liveBoard.match(/\.order\("created_at", \{ ascending: true \}\)\.order\("id", \{ ascending: true \}\)/g) || []).length === 4);

// ════════ lib/cancelWatch.ts — 40 ═════════════════════════════════════════════════════════════════
const cw = "STUB — real watchCancellations, alerts captured in memory";
const cday = (o) => ({ restaurant_id: RID, deleted_at: null, created_at: today(), taxable_base: null, nontax_amount: 0, ...o });
const cancelled = (k, each = 100, extra = {}) => Array.from({ length: k }, (_, i) => cday({ id: `c${i}`, status: "cancelled", subtotal: each, ...extra }));
const sold = (amt, extra = {}) => [cday({ id: "s0", status: "served", payment_status: "paid", subtotal: amt, ...extra })];
async function watch(orders, opts = {}) { const G = await world({ fix: { orders }, restaurants: opts.restaurants, fail: opts.fail }); G.ALERTS = []; G.ALERT_THROWS = !!opts.throws; await CW().watchCancellations(opts.rid || RID); G.ALERT_THROWS = false; return G; }
check(id(), CWF, "no cancellations: one head count, no money read, no alert", cw, async () => { const G = await watch([]); return { ok: G.ALERTS.length === 0 && G.SCOPE_LOG.filter((q) => q.table === "orders").length === 1, note: `${G.SCOPE_LOG.length} statement(s)` }; });
check(id(), CWF, "four cancellations: still no money read (below MIN_COUNT)", cw, async () => { const G = await watch(cancelled(4)); return G.ALERTS.length === 0 && G.SCOPE_LOG.filter((q) => q.table === "orders").length === 1; });
check(id(), CWF, "five cancellations worth half the day: ONE quiet alert", cw, async () => { const G = await watch([...cancelled(5), ...sold(500)]); return { ok: G.ALERTS.length === 1, note: G.ALERTS[0]?.text.replace(/\n/g, " · ").slice(0, 120) }; });
check(id(), CWF, "five cancellations worth a tenth of the day: no alert", cw, async () => { const G = await watch([...cancelled(5, 20), ...sold(900)]); return G.ALERTS.length === 0; });
check(id(), CWF, "exactly a fifth of the day fires (the rule is 'at least')", cw, async () => { const G = await watch([...cancelled(5, 20), ...sold(400)]); return G.ALERTS.length === 1; });
check(id(), CWF, "a hair under a fifth does not", cw, async () => { const G = await watch([...cancelled(5, 19.9), ...sold(400)]); return G.ALERTS.length === 0; });
check(id(), CWF, "a day that sold nothing never fires, however much was voided", cw, async () => { const G = await watch(cancelled(9, 500)); return G.ALERTS.length === 0; });
check(id(), CWF, "a soft-deleted cancellation does not count toward the five", cw, async () => { const G = await watch([...cancelled(4), cday({ id: "x", status: "cancelled", subtotal: 100, deleted_at: today() }), ...sold(100)]); return G.ALERTS.length === 0; });
check(id(), CWF, "a soft-deleted sale is not counted in the day's takings", cw, async () => { const G = await watch([...cancelled(5, 20), ...sold(400), cday({ id: "d", status: "served", subtotal: 10000, deleted_at: today() })]); return G.ALERTS.length === 1; });
check(id(), CWF, "yesterday's cancellations are not today's", cw, async () => { const G = await watch([...cancelled(5, 100, { created_at: old() }), ...sold(100)]); return G.ALERTS.length === 0; });
check(id(), CWF, "another restaurant's cancellations are not counted", cw, async () => { const G = await watch([...cancelled(5, 100, { restaurant_id: RID2 }), ...sold(100)]); return G.ALERTS.length === 0; });
check(id(), CWF, "the alert key is cancel_watch:<restaurant>:<business day> — once a day, per restaurant", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)]); return { ok: G.ALERTS[0]?.key === `cancel_watch:${RID}:${BD().businessDayDate()}`, note: G.ALERTS[0]?.key }; });
check(id(), CWF, "it arrives QUIETLY (silent: true) — a thing worth noticing, not a thing broken", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)]); return G.ALERTS[0]?.opts?.silent === true; });
check(id(), CWF, "its title says what it is: 'Cancellations are high today'", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)]); return G.ALERTS[0]?.opts?.title === "Cancellations are high today"; });
check(id(), CWF, "it names the restaurant (a plain-text name)", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)]); return /Restaurant: French House/.test(G.ALERTS[0]?.text || ""); });
check(id(), CWF, "…or the English half of a multilingual name", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)], { restaurants: [{ id: RID, name: { en: "Maison" }, slug: "maison" }] }); return /Restaurant: Maison/.test(G.ALERTS[0]?.text || ""); });
check(id(), CWF, "…or the slug when there is no name", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)], { restaurants: [{ id: RID, name: null, slug: "maison" }] }); return /Restaurant: maison/.test(G.ALERTS[0]?.text || ""); });
check(id(), CWF, "…or a dash, never 'undefined', when it has neither", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)], { restaurants: [{ id: RID }] }); return /Restaurant: —/.test(G.ALERTS[0]?.text || "") && !/undefined|null/.test(G.ALERTS[0]?.text || ""); });
check(id(), CWF, "the count reads '5 bills' (plural handled)", cw, async () => { const G = await watch([...cancelled(5), ...sold(100)]); return /Cancelled today: 5 bills/.test(G.ALERTS[0]?.text || ""); });
check(id(), CWF, "the value is rupees with Indian grouping (₹12,346 for 12,345.6)", cw, async () => { const G = await watch([...cancelled(5, 2469.12), ...sold(100)]); return { ok: /Worth: ₹12,346/.test(G.ALERTS[0]?.text || ""), note: (G.ALERTS[0]?.text || "").split("\n")[2] }; });
check(id(), CWF, "the share is a whole percentage", cw, async () => { const G = await watch([...cancelled(5, 20), ...sold(400)]); return /Share of the day: 20%/.test(G.ALERTS[0]?.text || ""); });
check(id(), CWF, "money is the taxable base when an order has one (not the subtotal)", cw, async () => { const G = await watch([...cancelled(5, 1000, { taxable_base: 10 }), ...sold(400)]); return G.ALERTS.length === 0; });
check(id(), CWF, "…and the subtotal when the taxable base is empty (orders from before mig 270)", cw, async () => { const G = await watch([...cancelled(5, 100, { taxable_base: null }), ...sold(400)]); return G.ALERTS.length === 1; });
check(id(), CWF, "…plus the untaxed part (an MRP bottle is still money)", cw, async () => { const G = await watch([...cancelled(5, 0, { taxable_base: 0, nontax_amount: 100 }), ...sold(400)]); return G.ALERTS.length === 1; });
check(id(), CWF, "no phone, name, table or dish ever reaches the alert, even when the rows carry them", cw, async () => { const G = await watch([...cancelled(5, 100, { cust_phone: "9876543210", table_number: "12", title: "Pasta" }), ...sold(100)]); return !/9876543210|Pasta|12\b/.test(G.ALERTS[0]?.text.replace("12,", "") || "x"); });
check(id(), CWF, "a failed count never throws into the cancel that triggered it", cw, async () => { try { await watch([], { fail: { "orders:select": "throw" } }); return true; } catch { return false; } });
check(id(), CWF, "a dead alert channel never throws into the cancel either", cw, async () => { try { await watch([...cancelled(5), ...sold(100)], { throws: true }); return true; } catch { return false; } });
check(id(), CWF, "a money read that answers nothing ends quietly", cw, async () => { const G = await world({ fix: { orders: cancelled(5) }, failNth: { "orders:select": { at: 2, mode: "error" } } }); G.ALERTS = []; await CW().watchCancellations(RID); return G.ALERTS.length === 0; });
check(id(), CWF, "the money read is capped at 5,000 rows", "SRC", () => /\.gte\("created_at", since\)\.limit\(5000\)/.test(CODE.cancelWatch));
check(id(), CWF, "the money read names its columns", "SRC", () => /\.select\("status,payment_status,subtotal,taxable_base,nontax_amount,deleted_at"\)/.test(CODE.cancelWatch));
check(id(), CWF, "the restaurant's name is read ONLY on the path that is about to send", cw, async () => { const G = await watch([...cancelled(5, 1), ...sold(1000)]); return !G.SCOPE_LOG.some((q) => q.table === "restaurants"); });
check(id(), CWF, "the thresholds are five bills and a fifth of the day", "STUB", () => CW().MIN_COUNT === 5 && CW().MIN_SHARE === 0.2);
check(id(), CWF, "the share is cancelled ÷ (cancelled + sold), not ÷ sold (18% stays quiet; 'of sold' would read 22.5%)", cw, async () => { const G = await watch([...cancelled(5, 18), ...sold(400)]); return G.ALERTS.length === 0; });
check(id(), CWF, "the head count asks for cancelled, live, today's, this restaurant's", cw, async () => { const G = await watch([]); const q = G.SCOPE_LOG[0]; const f = (c) => q.filters.find((x) => x.col === c); return f("status")?.val === "cancelled" && f("restaurant_id")?.val === RID && f("deleted_at")?.kind === "is" && f("created_at")?.kind === "gte"; });
check(id(), CWF, "the day is the 05:00-IST business day the Z-report uses", "SRC", () => /import \{ businessDayStartIso, businessDayDate \} from "@\/lib\/businessDay";/.test(SRC.cancelWatch));
check(id(), CWF, "the waiter tablet's cancel calls the watch (item 3)", "SRC", () => /await watchCancellations\(rid\);/.test(CODE.route));
check(id(), CWF, "…and so does the manager's cancel — one watch, both doors", "SRC", () => /watchCancellations\(rid\)/.test(rd("app/api/editor/[...path]/route.ts")));
check(id(), CWF, "the tablet calls the watch AFTER the status is written (so this ticket counts)", "SRC", () => { const b = CODE.route.slice(CODE.route.indexOf('if (a === "orders" && c === "delete")')); return b.indexOf('update({ status: "cancelled"') < b.indexOf("watchCancellations(rid)"); });
check(id(), CWF, "the watch returns nothing (fire-and-forget by contract)", cw, async () => { await world(); return (await CW().watchCancellations(RID)) === undefined; });
check(id(), CWF, "the two money figures are rounded to paise before the share is taken", "SRC", () => /cancelledValue = r2\(cancelledValue\);\s*soldValue = r2\(soldValue\);/.test(CODE.cancelWatch));

// ════════ lib/floorSummary.ts — 40 ════════════════════════════════════════════════════════════════
const fsh = "STUB — real sharedFloorSummary/invalidateFloor, clock controlled";
let clock = 1_000_000;
const realNow = Date.now;
async function withClock(fn) { Date.now = () => clock; try { FS()._resetSharedFloorSummary(); return await fn(FS()); } finally { Date.now = realNow; } }
const counter = () => { let c = 0; const f = async () => ++c; f.n = () => c; return f; };
check(id(), FSF, "two reads of the same floor inside the window share ONE computation", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); await f.sharedFloorSummary("floor:A", c); return c.n() === 1; }));
check(id(), FSF, "1,499 ms later it is still shared", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); clock += 1499; await f.sharedFloorSummary("floor:A", c); return c.n() === 1; }));
check(id(), FSF, "at exactly 1,500 ms it computes again", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); clock += 1500; await f.sharedFloorSummary("floor:A", c); return c.n() === 2; }));
check(id(), FSF, "two different restaurants never share", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); await f.sharedFloorSummary("floor:B", c); return c.n() === 2; }));
check(id(), FSF, "every caller in the window gets the SAME object (by reference — the documented trap)", fsh, () => withClock(async (f) => { const a = await f.sharedFloorSummary("floor:A", async () => ({ tiles: {} })); const b = await f.sharedFloorSummary("floor:A", async () => ({ tiles: { x: 1 } })); return a === b; }));
check(id(), FSF, "a failed computation rejects for its caller", fsh, () => withClock(async (f) => { try { await f.sharedFloorSummary("floor:A", async () => { throw new Error("blip"); }); return false; } catch (e) { return e.message === "blip"; } }));
check(id(), FSF, "…and the next caller computes afresh", fsh, () => withClock(async (f) => { try { await f.sharedFloorSummary("floor:A", async () => { throw new Error("x"); }); } catch { /* */ } return (await f.sharedFloorSummary("floor:A", async () => "ok")) === "ok"; }));
check(id(), FSF, "callers already waiting on a failing computation all hear the failure", fsh, () => withClock(async (f) => { let rej; const p1 = f.sharedFloorSummary("floor:A", () => new Promise((_, r) => { rej = r; })); const p2 = f.sharedFloorSummary("floor:A", async () => "never"); rej(new Error("down")); const r = await Promise.allSettled([p1, p2]); return r.every((x) => x.status === "rejected"); }));
check(id(), FSF, "a computation that throws SYNCHRONOUSLY is not cached either", fsh, () => withClock(async (f) => { try { await f.sharedFloorSummary("floor:A", () => { throw new Error("sync"); }); } catch { /* */ } return (await f.sharedFloorSummary("floor:A", async () => 7)) === 7; }));
check(id(), FSF, "a LATE failure never deletes a newer computation stored after the window", fsh, () => withClock(async (f) => { let rej; const p1 = f.sharedFloorSummary("floor:A", () => new Promise((_, r) => { rej = r; })); clock += 2000; const c = counter(); const p2 = f.sharedFloorSummary("floor:A", c); rej(new Error("late")); await p1.catch(() => {}); await p2; await f.sharedFloorSummary("floor:A", c); return c.n() === 1; }));
check(id(), FSF, "invalidateFloor drops the floor AND the merges for that restaurant", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:R", c); await f.sharedFloorSummary("merges:R", c); f.invalidateFloor("R"); await f.sharedFloorSummary("floor:R", c); await f.sharedFloorSummary("merges:R", c); return c.n() === 4; }));
check(id(), FSF, "invalidating restaurant '1' leaves restaurant '11' shared", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:11", c); f.invalidateFloor("1"); await f.sharedFloorSummary("floor:11", c); return c.n() === 1; }));
check(id(), FSF, "invalidating restaurant '11' leaves restaurant '1' shared", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:1", c); f.invalidateFloor("11"); await f.sharedFloorSummary("floor:1", c); return c.n() === 1; }));
check(id(), FSF, "invalidating a restaurant with nothing cached is a quiet no-op", fsh, () => withClock(async (f) => { f.invalidateFloor("nobody"); return true; }));
check(id(), FSF, "after an invalidate the very next read recomputes, inside the window", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); clock += 10; f.invalidateFloor("A"); await f.sharedFloorSummary("floor:A", c); return c.n() === 2; }));
check(id(), FSF, "past 64 entries, the expired ones are swept", fsh, () => withClock(async (f) => { for (let i = 0; i < 70; i++) await f.sharedFloorSummary(`floor:x${i}`, async () => i); clock += 5000; await f.sharedFloorSummary("floor:new", async () => 1); const c = counter(); await f.sharedFloorSummary("floor:x0", c); return c.n() === 1; }));
check(id(), FSF, "…and a fresh entry survives the sweep", fsh, () => withClock(async (f) => { for (let i = 0; i < 70; i++) await f.sharedFloorSummary(`floor:x${i}`, async () => i); const c = counter(); await f.sharedFloorSummary("floor:x5", c); return c.n() === 0; }));
check(id(), FSF, "the test hook forgets everything", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); f._resetSharedFloorSummary(); await f.sharedFloorSummary("floor:A", c); return c.n() === 2; }));
check(id(), FSF, "the shared value is exactly what the computation returned", fsh, () => withClock(async (f) => { const v = { tiles: { 1: { label: "Free" } } }; return (await f.sharedFloorSummary("floor:A", async () => v)) === v; }));
check(id(), FSF, "an empty answer (undefined) is shared like any other", fsh, () => withClock(async (f) => { const c = counter(); const u = async () => { c(); return undefined; }; await f.sharedFloorSummary("floor:A", u); await f.sharedFloorSummary("floor:A", u); return c.n() === 1; }));
check(id(), FSF, "ten simultaneous readers cost one computation", fsh, () => withClock(async (f) => { const c = counter(); await Promise.all(Array.from({ length: 10 }, () => f.sharedFloorSummary("floor:A", c))); return c.n() === 1; }));
check(id(), FSF, "an expired entry is simply overwritten by the next read", fsh, () => withClock(async (f) => { await f.sharedFloorSummary("floor:A", async () => "old"); clock += 3000; return (await f.sharedFloorSummary("floor:A", async () => "new")) === "new"; }));
check(id(), FSF, "an empty restaurant id drops only keys ending in ':' (nothing real) and does not throw", fsh, () => withClock(async (f) => { const c = counter(); await f.sharedFloorSummary("floor:A", c); f.invalidateFloor(""); await f.sharedFloorSummary("floor:A", c); return c.n() === 1; }));
check(id(), FSF, "the window is 1.5 s and lives only in this file", "SRC", () => /const WINDOW_MS = 1500;/.test(CODE.floorSummary) && !/export const WINDOW_MS/.test(CODE.floorSummary));
check(id(), FSF, "it imports nothing — no database, no disk: an in-memory, per-instance share", "SRC", () => !/^import /m.test(SRC.floorSummary));
check(id(), FSF, "the map is module-level (one per server instance), never persisted", "SRC", () => /^const inflight = new Map<string, Entry>\(\);/m.test(CODE.floorSummary));
check(id(), FSF, "arrays (the merges list) pass through the share unchanged", fsh, () => withClock(async (f) => { const v = [{ parent_table: "1" }]; return (await f.sharedFloorSummary("merges:A", async () => v)) === v; }));
// …and the same file seen THROUGH the tablet route (the route bundles its own copy of the module)
const freshFloor = () => call("POST", "nothing-here", { body: {} });
const summaryAns = { tiles: { 1: { counts: {} }, 2: { counts: {} }, 3: { counts: {} } }, calls: [], requests: [], joiners: [], order_count: 0 };
check(id(), FSF, "through the tablet route: two whole-floor reads in a row cost one floor computation", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns } }); await freshFloor(); await call("GET", "summary?nomenu=1".split("?")[0], { query: "?nomenu=1" }); await call("GET", "summary", { query: "?nomenu=1" }); return G.RPCS.filter((x) => x.name === "lfh_table_view_summary").length === 1; });
check(id(), FSF, "…a waiter's write in between makes the next read recompute (read your own write)", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns } }); await freshFloor(); await call("GET", "summary", { query: "?nomenu=1" }); await call("POST", "calls/x/attend", { body: {} }); await call("GET", "summary", { query: "?nomenu=1" }); return G.RPCS.filter((x) => x.name === "lfh_table_view_summary").length === 2; });
check(id(), FSF, "…even a write that FAILED drops the snapshot afterwards (the finally)", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns }, fail: { "waiter_calls:update": "throw" }, fix: { waiter_calls: [{ id: "c1", restaurant_id: RID, table_number: "2" }] } }); await freshFloor(); await call("GET", "summary", { query: "?nomenu=1" }); const w = await call("POST", "calls/c1/attend", { body: {} }); await call("GET", "summary", { query: "?nomenu=1" }); return { ok: w.status >= 500 && G.RPCS.filter((x) => x.name === "lfh_table_view_summary").length === 2, note: `write ${w.status}` }; });
check(id(), FSF, "…a targeted ?table=N read is never shared: two of them, two computations", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns } }); await call("GET", "summary", { query: "?table=2" }); await call("GET", "summary", { query: "?table=2" }); return G.RPCS.filter((x) => x.name === "lfh_table_view_summary").length === 2; });
check(id(), FSF, "…and a targeted read does not seed the whole-floor share", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns } }); await freshFloor(); await call("GET", "summary", { query: "?table=2" }); await call("GET", "summary", { query: "?nomenu=1" }); const calls = G.RPCS.filter((x) => x.name === "lfh_table_view_summary"); return calls.length === 2 && calls[1].args.p_table === null; });
check(id(), FSF, "…twenty targeted reads issue ONE merges read (its own shared key)", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns } }); await freshFloor(); for (let i = 0; i < 20; i++) await call("GET", "summary", { query: `?table=${(i % 3) + 1}` }); return { ok: G.SCOPE_LOG.filter((q) => q.table === "table_merges").length === 1, note: `${G.SCOPE_LOG.filter((q) => q.table === "table_merges").length} merges read(s)` }; });
check(id(), FSF, "…two waiters with different sections, inside one window, each see only their own", "STUB — real tablet route", async () => { const G = await world({ rpc: { lfh_table_view_summary: summaryAns }, user: { assigned_tables: SEC_1 } }); await freshFloor(); const a = await call("GET", "summary", { query: "?nomenu=1" }); G.ACTOR = { ok: true, user: { id: "w2", role: "tablet", restaurant_id: RID, permissions: {}, assigned_tables: SEC_2_3 } }; const b = await call("GET", "summary", { query: "?nomenu=1" }); return { ok: Object.keys(a.json.tiles).join() === "1" && Object.keys(b.json.tiles).join() === "2,3", note: `${Object.keys(a.json.tiles)} | ${Object.keys(b.json.tiles)}` }; });
check(id(), FSF, "…the admin looking at another restaurant (?rid=) never gets this restaurant's snapshot", "STUB — real tablet route", async () => { await world({ who: "admin", rpcImpl: { lfh_table_view_summary: (a) => ({ ...summaryAns, tiles: a.p_restaurant_id === RID ? summaryAns.tiles : {} }) } }); await call("POST", "nothing", { body: {}, query: `?rid=${RID}` }); await call("POST", "nothing", { body: {}, query: `?rid=${RID2}` }); const a = await call("GET", "summary", { query: `?nomenu=1&rid=${RID}` }); const b = await call("GET", "summary", { query: `?nomenu=1&rid=${RID2}` }); return { ok: Object.keys(a.json.tiles).length === 3 && Object.keys(b.json.tiles).length === 0, note: `${Object.keys(a.json.tiles).length} vs ${Object.keys(b.json.tiles).length}` }; });
check(id(), FSF, "…a failed floor computation answers an error, and the next read retries", "STUB — real tablet route", async () => { const G = await world({ fail: { "rpc:lfh_table_view_summary": "error" } }); await freshFloor(); const a = await call("GET", "summary", { query: "?nomenu=1" }); delete G.FAIL; G.RPC_ANSWERS.lfh_table_view_summary = summaryAns; const b = await call("GET", "summary", { query: "?nomenu=1" }); return { ok: a.status >= 500 && b.status === 200, note: `${a.status} then ${b.status}` }; });
check(id(), FSF, "…the slim (nomenu) and full reads carry identical tiles", "STUB — real tablet route", async () => { await world({ rpc: { lfh_table_view_summary: summaryAns } }); await freshFloor(); const a = await call("GET", "summary", { query: "?nomenu=1" }); const b = await call("GET", "summary"); return JSON.stringify(a.json.tiles) === JSON.stringify(b.json.tiles) && !("dishes" in a.json) && Array.isArray(b.json.dishes); });
check(id(), FSF, "the route never writes into the shared snapshot (merges go on a shallow copy)", "SRC", () => /const summaryOut = \{ \.\.\.\(summary as Record<string, unknown>\), merges \};/.test(CODE.route) && !/shared\.\w+\s*=/.test(CODE.route));
check(id(), FSF, "the comment that records WHY a retry was rejected is still beside the code", "SRC", () => /WHY THERE IS NO "JUST RETRY THE READ" HERE/.test(SRC.floorSummary));
