// scripts/sweep/t13s10/new-c-route.mjs — sweep #10 T13, new checks block C: the waiter tablet's route,
// DRIVEN through the states the happy path never visits. Earlier sweeps asked this file 400+ questions
// by READING it (sweep #8's grid); here every row CALLS the real handler in memory and asserts the
// status it answered and what it wrote: every permission mode for every gated action, every module
// switched off, the admin looking in, a manager looking in, missing rows, bad input.
import { check, world, call, RID, RID2, CODE } from "./lib.mjs";

let n = 182278;
const id = () => `P${n++}`;
const F = "app/api/tablet/[...path]/route.ts";
const S = "STUB — the real tablet route, called in memory";
const NOW = new Date().toISOString();
const MANAGER_WITH_PIN = [{ id: "mgr1", restaurant_id: RID, role: "manager", active: true, name: "Mona", username: "mona", pin_hash: "plain:4321" }];
const BASE_FIX = {
  sessions: [{ id: "s1", restaurant_id: RID, table_number: "3", status: "open", discount: 0, invoice_no: null, last_activity_at: NOW }],
  orders: [{ id: "o1", restaurant_id: RID, table_number: "3", session_id: "s1", status: "served", payment_status: "pending", archived: false, subtotal: 400, taxable_base: 400, total: 420, discount: 0, created_at: NOW, items: [] }],
  order_items: [{ id: "i1", restaurant_id: RID, order_id: "o1", status: "served", qty: 2, unit_price: 200, title: "Pasta" }],
  menu_items: [{ id: "d1", restaurant_id: RID, title: "Soup", price: "120", tags: [], open_price: false, tax_mode: null }],
  table_tags: [{ restaurant_id: RID, table_number: "3", tag: "family" }],
  staff_users: MANAGER_WITH_PIN,
};
const deny = (r) => r.status === 403 && !!(r.json && (r.json.disabled || r.json.needPin));
const passedGate = (r) => !deny(r) && r.status !== 429;
const mods = { take_orders_allowed: true, table_ops_allowed: true, table_tags_allowed: true, khata_allowed: true, banquet_allowed: true };
// ── every action the waiter's permission tri-state guards ────────────────────────────────────────
const GATED = [
  ["order", { table: "3", items: [{ id: "d1", qty: 1 }] }, "tablet_take_orders", "take an order"],
  ["parcel", { items: [{ id: "d1", qty: 1 }] }, "tablet_parcel", "punch a counter parcel"],
  ["banquet/place", { lines: [{ id: "b1", qty: 1 }] }, "tablet_banquet", "make a banquet bill"],
  ["orders/o1/discount", { amount: 10 }, "tablet_discount", "discount one ticket"],
  ["sessions/s1/bill-discount", { amount: 10 }, "tablet_discount", "discount the whole bill"],
  ["tables/3/loyalty-redeem", { phone: "9876543210", points: 10 }, "tablet_discount", "spend loyalty points"],
  ["tables/3/pay", { payment_method: "Cash" }, "tablet_mark_paid", "settle a bill"],
  ["tables/3/pay-split", { splits: [{ method: "Cash", amount: 420 }] }, "tablet_mark_paid", "settle a bill in parts"],
  ["tables/3/unpay", {}, "tablet_mark_paid", "take back a settle"],
  ["orders/o1/tip", { amount: 20 }, "tablet_mark_paid", "record a tip"],
  ["tables/3/on-the-house", {}, "tablet_mark_paid", "settle on the house"],
  ["tables/3/khata", { name: "Ravi" }, "tablet_khata", "park a bill on a tab"],
  ["tables/3/tag", { tag: "vip" }, "tablet_table_tags", "mark a table type"],
  ["sessions/s1/shift", { to: "7" }, "tablet_table_ops", "move a party"],
  ["sessions/s1/merge", { to: "7" }, "tablet_table_ops", "join two tables"],
  ["tables/3/unmerge", {}, "tablet_table_ops", "split joined tables"],
  ["order-items/i1/move", { to: "7" }, "tablet_table_ops", "move a dish"],
  ["orders/o1/move", { to: "7" }, "tablet_table_ops", "move a ticket"],
  ["print-jobs", { order_id: "o1" }, "tablet_table_ops", "ask the kitchen to print a ticket again"],
];
const run = (o = {}) => world({ fix: BASE_FIX, settings: { ...mods, ...(o.settings || {}) }, ents: { customers: true }, ...o });
for (const [path, body, key, what] of GATED) {
  check(id(), F, `${what}: switched OFF for waiters → refused (403), nothing written`, S, async () => { const G = await run({ settings: { [key]: "off" } }); const r = await call("POST", path, { body }); return { ok: deny(r) && G.WRITES.every((w) => w.matched === 0 || ["staff_actions"].includes(w.table)) && !G.RPCS.some((x) => !/^lfh_(rate|throttle|pin)/.test(x.name)), note: `${r.status} ${(r.json?.error || "").slice(0, 60)}` }; });
  check(id(), F, `${what}: on PIN, with a manager PIN set and none typed → asks for the PIN (403 needPin)`, S, async () => { await run({ settings: { [key]: "pin" } }); const r = await call("POST", path, { body }); return { ok: r.status === 403 && r.json?.needPin === true, note: `${r.status}` }; });
  check(id(), F, `${what}: on PIN, with the right PIN typed → the permission lets it through`, S, async () => { await run({ settings: { [key]: "pin" } }); const r = await call("POST", path, { body: { ...body, managerPin: "4321" } }); return { ok: passedGate(r), note: `${r.status} ${(r.json?.error || "").slice(0, 60)}` }; });
  check(id(), F, `${what}: this waiter's own 'on' beats the restaurant's 'off'`, S, async () => { await run({ settings: { [key]: "off" }, user: { permissions: { [key]: "on" } } }); const r = await call("POST", path, { body }); return { ok: passedGate(r), note: `${r.status}` }; });
  check(id(), F, `${what}: the admin looking in is never stopped by the waiter's switch`, S, async () => { await run({ who: "admin", settings: { [key]: "off" } }); const r = await call("POST", path, { body, query: `?rid=${RID}` }); return { ok: passedGate(r), note: `${r.status}` }; });
}
// the never-list: an invoice is not a waiter's, whatever is stored
check(id(), F, "issuing the invoice: a WAITER is refused even when the restaurant stored 'on'", S, async () => { await run({ settings: { tablet_invoice: "on" } }); const r = await call("POST", "sessions/s1/invoice", { body: {} }); return { ok: r.status === 403 && /Only a manager can issue the invoice/.test(r.text), note: r.text.slice(0, 80) }; });
check(id(), F, "…and even when the waiter's own override says 'on'", S, async () => { await run({ settings: { tablet_invoice: "on" }, user: { permissions: { tablet_invoice: "on" } } }); const r = await call("POST", "sessions/s1/invoice", { body: {} }); return r.status === 403; });
check(id(), F, "…while a MANAGER looking in through this panel may issue it (the rule is about the waiter, not the URL)", S, async () => { const G = await run({ who: "manager", settings: { tablet_invoice: "on" } }); const r = await call("POST", "sessions/s1/invoice", { body: { cust_phone: "9876543210", cust_name: "Asha" } }); return { ok: passedGate(r) && G.RPCS.some((x) => x.name === "lfh_generate_invoice"), note: `${r.status}` }; });
check(id(), F, "…and the admin may", S, async () => { const G = await run({ who: "admin" }); const r = await call("POST", "sessions/s1/invoice", { body: { cust_phone: "9876543210", cust_name: "Asha" }, query: `?rid=${RID}` }); return passedGate(r) && G.RPCS.some((x) => x.name === "lfh_generate_invoice"); });
check(id(), F, "the Feature half off ('Discount a bill' not part of this restaurant) refuses the waiter even with a personal 'on'", S, async () => { await run({ accessConfig: { give_discounts: { on: false } }, user: { permissions: { tablet_discount: "on" } } }); const r = await call("POST", "orders/o1/discount", { body: { amount: 10 } }); return r.status === 403 && /isn't part of this restaurant/.test(r.text); });
check(id(), F, "a PIN-approved settle names the MANAGER who approved it in the log (the PIN pill)", S, async () => { const G = await run({ settings: { tablet_mark_paid: "pin" } }); await call("POST", "tables/3/pay", { body: { payment_method: "Cash", managerPin: "4321" } }); const l = G.LOGS.find((x) => x.action === "bill_paid"); return { ok: l?.actor === "Mona" && l?.actor_id === "mgr1", note: JSON.stringify(l && { actor: l.actor, id: l.actor_id }) }; });
check(id(), F, "an 'on' settle names the WAITER (no PIN, no manager)", S, async () => { const G = await run(); await call("POST", "tables/3/pay", { body: { payment_method: "Cash" } }); const l = G.LOGS.find((x) => x.action === "bill_paid"); return { ok: l?.actor === "Diag Waiter" && l?.actor_id === "w1", note: JSON.stringify(l && { actor: l.actor }) }; });
check(id(), F, "a wrong PIN is refused and nothing is settled", S, async () => { const G = await run({ settings: { tablet_mark_paid: "pin" } }); const r = await call("POST", "tables/3/pay", { body: { payment_method: "Cash", managerPin: "1111" } }); return { ok: r.status === 403 && G.FIX.orders[0].payment_status === "pending", note: `${r.status}` }; });
check(id(), F, "before ANY manager has set a PIN, 'pin' mode lets the waiter through (nobody is locked out before setup)", S, async () => { await world({ fix: { ...BASE_FIX, staff_users: [] }, settings: { ...mods, tablet_mark_paid: "pin" } }); const r = await call("POST", "tables/3/pay", { body: { payment_method: "Cash" } }); return { ok: r.status === 200, note: `${r.status}` }; });
// module rungs
const LADDERED = [
  ["order", { table: "3", items: [{ id: "d1" }] }, { take_orders_allowed: false }, /Taking orders is switched off/],
  ["banquet/place", { lines: [{ id: "b1" }] }, { banquet_allowed: false }, /Banquet billing isn't enabled/],
  ["sessions/s1/shift", { to: "7" }, { table_ops_allowed: false }, /Table & KOT operations aren't enabled/],
  ["sessions/s1/merge", { to: "7" }, { table_ops_allowed: false }, /Table & KOT operations aren't enabled/],
  ["tables/3/unmerge", {}, { table_ops_allowed: false }, /Table & KOT operations aren't enabled/],
  ["order-items/i1/move", { to: "7" }, { table_ops_allowed: false }, /Table & KOT operations aren't enabled/],
  ["orders/o1/move", { to: "7" }, { table_ops_allowed: false }, /Table & KOT operations aren't enabled/],
  ["print-jobs", { order_id: "o1" }, { table_ops_allowed: false }, /Table & KOT operations aren't enabled/],
  ["tables/3/tag", { tag: "vip" }, { table_tags_allowed: false }, /Table types aren't enabled/],
  ["tables/3/on-the-house", {}, { table_tags_allowed: false }, /Table types aren't enabled/],
  ["tables/3/khata", { name: "Ravi" }, { khata_allowed: false }, /Pay later \(khata\) isn't enabled/],
];
for (const [path, body, off, msg] of LADDERED) {
  check(id(), F, `${path}: the module switched off for this restaurant refuses a waiter in plain words`, S, async () => { await run({ settings: off }); const r = await call("POST", path, { body }); return { ok: r.status === 403 && msg.test(r.text), note: (r.json?.error || "").slice(0, 70) }; });
}
check(id(), F, "the admin looking in passes a switched-off module rung (X-ray honesty) — except Parcel's, which is permanent", S, async () => { await run({ who: "admin", settings: { table_ops_allowed: false } }); const r = await call("POST", "sessions/s1/shift", { body: { to: "7" }, query: `?rid=${RID}` }); return { ok: !/aren't enabled/.test(r.text), note: `${r.status}` }; });
check(id(), F, "a parcel is never refused for a switched-off parcel column (no switch exists any more)", S, async () => { await run({ settings: { parcel_allowed: false, parcel_enabled: false } }); const r = await call("POST", "parcel", { body: { items: [{ id: "d1" }] } }); return { ok: r.status === 200, note: `${r.status} ${(r.json?.error || "").slice(0, 60)}` }; });
// whoami / summary / GET states
check(id(), F, "whoami for a waiter: actor tablet, no tinted extras", S, async () => { await run(); const r = await call("GET", "whoami"); return r.json.actor === "tablet" && r.json.higherView === false; });
check(id(), F, "whoami for a manager looking in: actor manager, no tint promised", S, async () => { await run({ who: "manager" }); const r = await call("GET", "whoami"); return r.json.actor === "manager" && r.json.higherView === false; });
check(id(), F, "whoami for the admin: actor admin, higherView on", S, async () => { await run({ who: "admin" }); const r = await call("GET", "whoami", { query: `?rid=${RID}` }); return r.json.actor === "admin" && r.json.higherView === true && r.json.simulated === false; });
check(id(), F, "the floor tells a waiter which tables are theirs (my_tables)", S, async () => { await run({ rpc: { lfh_table_view_summary: { tiles: {} } } }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return Array.isArray(r.json.my_tables) && r.json.my_tables.length === 20; });
check(id(), F, "…and tells a manager looking in nothing (null = the whole floor)", S, async () => { await run({ who: "manager", rpc: { lfh_table_view_summary: { tiles: {} } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.my_tables === null; });
check(id(), F, "a waiter's payload says tablet_invoice 'off' even when the restaurant stored 'on'", S, async () => { await run({ settings: { tablet_invoice: "on" } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.settings.tablet_invoice === "off"; });
check(id(), F, "a manager looking in sees the stored tablet_invoice (their reach is their own)", S, async () => { await run({ who: "manager", settings: { tablet_invoice: "on" } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.settings.tablet_invoice === "on"; });
check(id(), F, "the Feature half off turns the waiter's Discount button off in the payload (applied last)", S, async () => { await run({ accessConfig: { give_discounts: { on: false } }, user: { permissions: { tablet_discount: "on" } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.settings.tablet_discount === "off"; });
check(id(), F, "…but the admin's payload keeps it (the admin is never blocked by a waiter rung)", S, async () => { await run({ who: "admin", accessConfig: { give_discounts: { on: false } }, settings: { tablet_discount: "on" } }); await call("POST", "x", { body: {}, query: `?rid=${RID}` }); const r = await call("GET", "summary", { query: `?nomenu=1&rid=${RID}` }); return r.json.settings.tablet_discount === "on"; });
check(id(), F, "Table & KOT ops switched off → the payload says tablet_table_ops 'off' and table_ops_tablet_allowed false", S, async () => { await run({ settings: { table_ops_allowed: false } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.settings.tablet_table_ops === "off" && r.json.settings.table_ops_tablet_allowed === false; });
check(id(), F, "order-taking switched off → tablet_take_orders 'off' (the ＋Take order button hides)", S, async () => { await run({ settings: { take_orders_allowed: false } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.settings.tablet_take_orders === "off"; });
check(id(), F, "a per-person 'pin' reaches the payload as 'pin'", S, async () => { await run({ settings: { tablet_mark_paid: "on" }, user: { permissions: { tablet_mark_paid: "pin" } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.settings.tablet_mark_paid === "pin"; });
check(id(), F, "the restaurant row carries its logo (so a waiter's printed bill has it) and NOT its permission record", S, async () => { await run(); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.restaurant.logo_url === "https://x/logo.png" && !("access_config" in r.json.restaurant); });
check(id(), F, "the settings row never carries the delivery apps' keys", S, async () => { await run(); await call("POST", "x", { body: {} }); const r = await call("GET", "summary"); return !/SECRET-KEY/.test(r.text) && !("platform_channels" in r.json.settings); });
check(id(), F, "a full load carries the dish list; a slim one carries no dishes key at all", S, async () => { await run(); await call("POST", "x", { body: {} }); const a = await call("GET", "summary"); const b = await call("GET", "summary", { query: "?nomenu=1" }); return Array.isArray(a.json.dishes) && a.json.dishes.length === 1 && !("dishes" in b.json); });
check(id(), F, "a targeted ?table=N answer carries the tile only — no settings, no restaurant", S, async () => { await run({ rpc: { lfh_table_view_summary: { tiles: { 3: {} } } } }); const r = await call("GET", "summary", { query: "?table=3" }); return !("settings" in r.json) && !("restaurant" in r.json) && "merges" in r.json; });
check(id(), F, "?table=abc is not an error — it becomes a full floor read", S, async () => { const G = await run({ rpc: { lfh_table_view_summary: { tiles: {} } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?table=abc&nomenu=1" }); return r.status === 200 && G.RPCS.some((x) => x.name === "lfh_table_view_summary" && x.args.p_table === null); });
check(id(), F, "?table=1234567 (seven digits) is not a table either", S, async () => { const G = await run({ rpc: { lfh_table_view_summary: { tiles: {} } } }); await call("POST", "x", { body: {} }); await call("GET", "summary", { query: "?table=1234567&nomenu=1" }); return G.RPCS.every((x) => x.name !== "lfh_table_view_summary" || x.args.p_table === null); });
check(id(), F, "a sectioned waiter's floor narrows the guest calls too", S, async () => { await run({ user: { assigned_tables: SEC1 }, rpc: { lfh_table_view_summary: { tiles: { 1: {}, 2: {} }, calls: [{ table_number: "1" }, { table_number: "2" }], requests: [], joiners: [] } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.calls.length === 1 && r.json.calls[0].table_number === "1"; });
check(id(), F, "…and keeps the blocklist whole (the guest in front of them may be blocked)", S, async () => { await run({ user: { assigned_tables: SEC1 }, rpc: { lfh_table_view_summary: { tiles: {}, blocklist: [{ phone: "1" }, { phone: "2" }] } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.blocklist.length === 2; });
check(id(), F, "…and turns the restaurant-wide order count into 'how many of MY tables are busy'", S, async () => { await run({ user: { assigned_tables: SEC1 }, rpc: { lfh_table_view_summary: { tiles: { 1: { counts: { ck: 1 } }, 2: { counts: { ck: 3 } } }, order_count: 9 } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.order_count === 1; });
check(id(), F, "…and drops a 'latest order' pointer at somebody else's table", S, async () => { await run({ user: { assigned_tables: SEC1 }, rpc: { lfh_table_view_summary: { tiles: {}, latest_order_table: "2" } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return r.json.latest_order_table === null; });
check(id(), F, "a table OFF the floor plan (above table_count) stays visible to a sectioned waiter", S, async () => { await run({ user: { assigned_tables: SEC1 }, rpc: { lfh_table_view_summary: { tiles: { 1: {}, 2: {}, 47: {} } } } }); await call("POST", "x", { body: {} }); const r = await call("GET", "summary", { query: "?nomenu=1" }); return Object.keys(r.json.tiles).join() === "1,47"; });
check(id(), F, "a table slice outside the waiter's section answers EMPTY, not an error (no reload loop)", S, async () => { await run({ user: { assigned_tables: SEC1 } }); const r = await call("GET", "state", { query: "?table=3" }); return r.status === 200 && r.json.orders.length === 0 && r.json.sessions.length === 0; });
check(id(), F, "a table slice inside the section carries that table's party", S, async () => { await run(); const r = await call("GET", "state", { query: "?table=3" }); return r.status === 200 && r.json.sessions.length === 1 && r.json.sessions[0].id === "s1"; });
check(id(), F, "the slice's party never carries the guest's own basket or the heartbeat columns", "SRC — the column list the slice reads", () => { const m = CODE.route.match(/const SESSION_COLS = "([^"]+)"/); return { ok: !!m && !/\bcart\b|cart_updated_at|last_activity_at|restaurant_id/.test(m[1]), note: m && m[1] }; });
check(id(), F, "/state with no table refuses and says where the floor lives", S, async () => { await run(); const r = await call("GET", "state"); return r.status === 400 && /\/summary/.test(r.text); });
check(id(), F, "/state?table=abc is the same refusal, not a database error", S, async () => { await run(); const r = await call("GET", "state", { query: "?table=abc" }); return r.status === 400; });
check(id(), F, "a customer search on fewer than three digits returns nothing without asking the database", S, async () => { const G = await run(); const r = await call("GET", "customer-search", { query: "?q=98" }); return r.json.matches.length === 0 && !G.RPCS.length; });
check(id(), F, "a customer search keeps only digits", S, async () => { const G = await run({ rpc: { lfh_customer_phone_search: [] } }); await call("GET", "customer-search", { query: "?q=98a2-5" }); return G.RPCS[0]?.args.p_prefix === "9825"; });
check(id(), F, "the repeat-customer lookup with no phone answers 'not known' without a query", S, async () => { const G = await run(); const r = await call("GET", "customer-recognize"); return r.json.known === false && !G.RPCS.length; });
check(id(), F, "the khata picker refuses a waiter when Pay later is off for the restaurant", S, async () => { await run({ settings: { khata_allowed: false } }); const r = await call("GET", "khata/customers", { query: "?q=ra" }); return r.status === 403; });
check(id(), F, "…and when the waiter's khata power is off", S, async () => { await run({ settings: { tablet_khata: "off" } }); const r = await call("GET", "khata/customers", { query: "?q=ra" }); return r.status === 403; });
check(id(), F, "…and answers this restaurant's people only", S, async () => { await world({ fix: { khata_customers: [{ id: "k1", restaurant_id: RID, name: "Ravi", phone: "1", created_at: NOW }, { id: "k2", restaurant_id: RID2, name: "Ravi B", phone: "2", created_at: NOW }] }, settings: mods }); const r = await call("GET", "khata/customers", { query: "?q=ra" }); return r.json.customers.length === 1 && r.json.customers[0].id === "k1"; });
check(id(), F, "the banquet list refuses when banquet billing is off", S, async () => { await run({ settings: { banquet_allowed: false } }); const r = await call("GET", "banquet-items"); return r.status === 403; });
check(id(), F, "the banquet list shows ACTIVE lines only", S, async () => { await world({ fix: { banquet_items: [{ id: "b1", restaurant_id: RID, active: true }, { id: "b2", restaurant_id: RID, active: false }] }, settings: mods }); const r = await call("GET", "banquet-items"); return r.json.items.length === 1; });
check(id(), F, "an unknown GET is 404", S, async () => { await run(); return (await call("GET", "no-such-thing")).status === 404; });
check(id(), F, "a blocked device's board read goes dark with a CODE (device_blocked)", S, async () => { const G = await run(); G.BLOCKED = [`${RID}:dark-tab`]; const r = await call("GET", "whoami", { headers: { "x-lfh-device": "dark-tab" } }); delete G.BLOCKED; return r.status === 403 && r.json.reason === "device_blocked"; });
check(id(), F, "…a device blocked at ANOTHER restaurant is not dark here", S, async () => { const G = await run(); G.BLOCKED = [`${RID2}:other-tab`]; const r = await call("GET", "whoami", { headers: { "x-lfh-device": "other-tab" } }); delete G.BLOCKED; return r.status === 200; });
// POST validation and state rules
check(id(), F, "an order on a non-number table is refused", S, async () => { await run(); return (await call("POST", "order", { body: { table: "3a", items: [{ id: "d1" }] } })).status === 400; });
check(id(), F, "an order on a table the restaurant does not have is refused, naming its size", S, async () => { await run(); const r = await call("POST", "order", { body: { table: "21", items: [{ id: "d1" }] } }); return r.status === 400 && /has 20 tables/.test(r.text); });
check(id(), F, "an order with no dishes is refused", S, async () => { await run(); return (await call("POST", "order", { body: { table: "3", items: [] } })).status === 400; });
check(id(), F, "an identical order to the same table inside 3 s asks 'send anyway?' (409 duplicateWarning)", S, async () => { await world({ fix: { ...BASE_FIX, orders: [{ id: "o9", restaurant_id: RID, table_number: "3", created_at: new Date().toISOString(), items: [{ id: "d1", qty: 1 }], allergies: [] }] }, settings: mods }); const r = await call("POST", "order", { body: { table: "3", items: [{ id: "d1", qty: 1 }] } }); return r.status === 409 && r.json.duplicateWarning === true; });
check(id(), F, "…and 'send anyway' (confirmDuplicate) goes through to the pricer", S, async () => { const G = await world({ fix: { ...BASE_FIX, orders: [{ id: "o9", restaurant_id: RID, table_number: "3", created_at: new Date().toISOString(), items: [{ id: "d1", qty: 1 }], allergies: [] }] }, settings: mods }); await call("POST", "order", { body: { table: "3", items: [{ id: "d1", qty: 1 }], confirmDuplicate: true } }); return G.RPCS.some((x) => x.name === "lfh_staff_place_order" && x.args.p_confirm_duplicate === true); });
check(id(), F, "a pricer refusal (sold out) is an error the waiter reads, never 'Order sent'", S, async () => { await run({ rpc: { lfh_staff_place_order: { ok: false, reason: "sold_out" } } }); const r = await call("POST", "order", { body: { table: "3", items: [{ id: "d1" }] } }); return r.status === 400 && /sold out/.test(r.text); });
check(id(), F, "a waiter's order goes straight onto the pass, stamped with who punched it", S, async () => { const G = await run({ rpc: { lfh_staff_place_order: { ok: true, order_id: "new1" } } }); await call("POST", "order", { body: { table: "3", items: [{ id: "d1" }] } }); const m = G.RPCS.find((x) => x.name === "lfh_staff_mark_placed"); return m?.args.p_order === "new1" && m?.args.p_by === "Diag Waiter" && m?.args.p_restaurant_id === RID; });
check(id(), F, "a parcel with a dish this restaurant does not have is refused, not shortened", S, async () => { await run(); const r = await call("POST", "parcel", { body: { items: [{ id: "d1" }, { id: "ghost" }] } }); return r.status === 400; });
check(id(), F, "a parcel with a sold-out dish is refused by name", S, async () => { await world({ fix: { menu_items: [{ id: "d1", restaurant_id: RID, title: "Soup", price: "120", tags: ["sold-out"] }] }, settings: mods }); const r = await call("POST", "parcel", { body: { items: [{ id: "d1" }] } }); return r.status === 400 && /Soup.*sold out/.test(r.text); });
check(id(), F, "an open-price parcel line with no price is refused", S, async () => { await world({ fix: { menu_items: [{ id: "d1", restaurant_id: RID, title: "Market fish", price: null, open_price: true, tags: [] }] }, settings: mods }); const r = await call("POST", "parcel", { body: { items: [{ id: "d1" }] } }); return r.status === 400 && /Enter a price/.test(r.text); });
check(id(), F, "a parcel is stored at food + tax (₹120 at 5% → ₹126), so the record equals the paper", S, async () => { const G = await run(); await call("POST", "parcel", { body: { items: [{ id: "d1", qty: 1 }] } }); const ins = G.RPCS.find((x) => x.name === "lfh_platform_insert"); return { ok: ins && Math.abs(ins.args.p_total - 126) < 0.01, note: `stored ₹${ins?.args.p_total}` }; });
check(id(), F, "a parcel's quantity is clamped to 1..99", S, async () => { const G = await run(); await call("POST", "parcel", { body: { items: [{ id: "d1", qty: 500 }] } }); return G.RPCS.find((x) => x.name === "lfh_platform_insert")?.args.p_items[0].qty === 99; });
check(id(), F, "settling refuses while a ticket is still waiting to be accepted", S, async () => { await world({ fix: { ...BASE_FIX, orders: [{ ...BASE_FIX.orders[0], status: "received" }] }, settings: mods }); const r = await call("POST", "tables/3/pay", { body: { payment_method: "Cash" } }); return r.status === 409 && /Accept the order first/.test(r.text); });
check(id(), F, "settling a bill someone already settled says so (409), never 'paid' twice", S, async () => { await world({ fix: { ...BASE_FIX, orders: [{ ...BASE_FIX.orders[0], payment_status: "paid", paid_at: NOW }] }, settings: mods }); const r = await call("POST", "tables/3/pay", { body: { payment_method: "Cash" } }); return r.status === 409 && /Nothing to settle/.test(r.text); });
check(id(), F, "an unknown payment method is refused", S, async () => { await run(); return (await call("POST", "tables/3/pay", { body: { payment_method: "Bitcoin" } })).status === 400; });
check(id(), F, "taking back a settle older than 30 minutes is refused", S, async () => { await world({ fix: { ...BASE_FIX, orders: [{ ...BASE_FIX.orders[0], payment_status: "paid", paid_at: new Date(Date.now() - 40 * 60e3).toISOString() }] }, settings: mods }); const r = await call("POST", "tables/3/unpay", { body: {} }); return r.status === 409 && /more than 30 minutes/.test(r.text); });
check(id(), F, "taking back a fresh settle reverts it AND clears the tip with it", S, async () => { const G = await world({ fix: { ...BASE_FIX, orders: [{ ...BASE_FIX.orders[0], payment_status: "paid", paid_at: NOW, payment_method: "Cash", tip: 50 }] }, settings: mods }); const r = await call("POST", "tables/3/unpay", { body: {} }); const o = G.FIX.orders[0]; return r.status === 200 && o.payment_status === "pending" && o.tip === 0 && o.payment_method === null; });
check(id(), F, "'On the house' needs a Family or Owner's Guest mark", S, async () => { await world({ fix: { ...BASE_FIX, table_tags: [{ restaurant_id: RID, table_number: "3", tag: "vip" }] }, settings: mods }); const r = await call("POST", "tables/3/on-the-house", { body: {} }); return r.status === 409 && /only for tables marked Family/.test(r.text); });
check(id(), F, "'On the house' settles every unpaid ticket at ₹0 and writes one Audit row each", S, async () => { const G = await run(); const r = await call("POST", "tables/3/on-the-house", { body: {} }); const o = G.FIX.orders[0]; return r.status === 200 && o.payment_status === "paid" && o.discount === 400 && G.RPCS.filter((x) => x.name === "lfh_record_removal" && x.args.p_kind === "on_the_house").length === 1; });
check(id(), F, "parking a bill refuses while food is still cooking", S, async () => { await world({ fix: { ...BASE_FIX, orders: [{ ...BASE_FIX.orders[0], status: "preparing" }] }, settings: mods }); const r = await call("POST", "tables/3/khata", { body: { name: "Ravi" } }); return r.status === 409 && /still has orders cooking/.test(r.text); });
check(id(), F, "parking a bill needs a name", S, async () => { await run(); const r = await call("POST", "tables/3/khata", { body: { name: "  " } }); return r.status === 400; });
check(id(), F, "parking onto a person from ANOTHER restaurant's book is refused", S, async () => { await world({ fix: { ...BASE_FIX, khata_customers: [{ id: "kx", restaurant_id: RID2, name: "X" }] }, settings: mods }); const r = await call("POST", "tables/3/khata", { body: { customer_id: "kx" } }); return r.status === 404; });
check(id(), F, "an unknown table type is refused", S, async () => { await run(); return (await call("POST", "tables/3/tag", { body: { tag: "royal" } })).status === 400; });
check(id(), F, "clearing a table type removes the mark", S, async () => { const G = await run(); const r = await call("POST", "tables/3/tag", { body: { tag: "" } }); return r.status === 200 && !G.FIX.table_tags.some((t) => t.table_number === "3"); });
check(id(), F, "moving a party to a table the plan does not have is refused", S, async () => { await run(); const r = await call("POST", "sessions/s1/shift", { body: { to: "99" } }); return r.status === 400 && /has 20 tables/.test(r.text); });
check(id(), F, "moving a party onto an occupied table is refused in words, not a silent snap-back", S, async () => { await run({ rpc: { lfh_staff_shift_table: { ok: false, reason: "target_occupied" } } }); const r = await call("POST", "sessions/s1/shift", { body: { to: "7" } }); return r.status === 409 && /already taken/.test(r.text); });
check(id(), F, "joining onto a table whose bill is invoiced is refused in words", S, async () => { await run({ rpc: { lfh_staff_merge_tables: { ok: false, reason: "target_invoiced" } } }); const r = await call("POST", "sessions/s1/merge", { body: { to: "7" } }); return r.status === 409 && /invoiced/.test(r.text); });
check(id(), F, "the merge record names who joined the tables", S, async () => { const G = await run({ rpc: { lfh_staff_merge_tables: { ok: true, from: "3" } } }); await call("POST", "sessions/s1/merge", { body: { to: "7" } }); const m = G.RPCS.find((x) => x.name === "lfh_staff_merge_tables"); return m?.args.p_actor === "Diag Waiter" && m?.args.p_rid === RID; });
check(id(), F, "a restart of a table with food cooking needs a manager PIN", S, async () => { await world({ fix: { ...BASE_FIX, orders: [{ ...BASE_FIX.orders[0], status: "preparing" }] }, settings: mods }); const r = await call("POST", "tables/3/restart", { body: {} }); return r.status === 403 && r.json.needPin === true; });
check(id(), F, "banning a guest needs a manager PIN", S, async () => { await run(); const r = await call("POST", "members/m1/ban", { body: {} }); return r.status === 403 && r.json.needPin === true; });
check(id(), F, "closing a table that still owes money needs the walk-out permission (PIN by default)", S, async () => { await run(); const r = await call("POST", "sessions/s1/close", { body: { force: true } }); return r.status === 403 && r.json.needPin === true; });
check(id(), F, "…and switched off, it is refused outright in plain words", S, async () => { await run({ accessConfig: { close_unpaid: { tablet: "off" } } }); const r = await call("POST", "sessions/s1/close", { body: { force: true } }); return r.status === 403 && /isn't enabled on the tablet/.test(r.text); });
check(id(), F, "approving a request a colleague already DENIED is refused (409), and no table opens", S, async () => { const G = await world({ fix: { requests: [{ id: "q1", restaurant_id: RID, table_number: "4", status: "denied", type: "open" }] }, settings: mods }); const r = await call("POST", "requests/q1/resolve", { body: { status: "approved" } }); return r.status === 409 && !G.WRITES.some((w) => w.table === "sessions" && w.matched); });
check(id(), F, "approving twice (your own double tap) is a quiet OK", S, async () => { await world({ fix: { requests: [{ id: "q1", restaurant_id: RID, table_number: "4", status: "approved", type: "open" }] }, settings: mods }); return (await call("POST", "requests/q1/resolve", { body: { status: "approved" } })).status === 200; });
check(id(), F, "a request answer must be approve or deny", S, async () => { await run(); return (await call("POST", "requests/q1/resolve", { body: { status: "maybe" } })).status === 400; });
check(id(), F, "the bill-printed stamp is written once and a second print says reprint", S, async () => { const G = await run(); await call("POST", "sessions/s1/bill-printed", { body: {} }); const first = G.FIX.sessions[0].bill_printed_at; const r = await call("POST", "sessions/s1/bill-printed", { body: {} }); return !!first && r.json.reprint === true && G.FIX.sessions[0].bill_printed_at === first; });
check(id(), F, "opening a table outside the floor plan is refused", S, async () => { await run(); return (await call("POST", "sessions/open", { body: { table: "21" } })).status === 400; });
check(id(), F, "opening a table clears a guest's still-pending 'asked to open' request", S, async () => { const G = await world({ fix: { requests: [{ id: "q1", restaurant_id: RID, table_number: "4", status: "pending", type: "open" }] }, settings: mods }); await call("POST", "sessions/open", { body: { table: "4" } }); return G.FIX.requests[0].status === "approved"; });
check(id(), F, "serving a dish on a LIVE ticket stamps served_at; sending it back clears it", S, async () => { const G = await world({ fix: { orders: [{ id: "o1", restaurant_id: RID, table_number: "3", status: "preparing" }], order_items: [{ id: "i1", restaurant_id: RID, order_id: "o1", status: "preparing" }] }, settings: mods }); await call("POST", "items/i1/status", { body: { status: "served" } }); const a = G.FIX.order_items[0].served_at; await call("POST", "items/i1/status", { body: { status: "preparing" } }); return !!a && G.FIX.order_items[0].served_at === null; });
check(id(), F, "an allergy change with no reason is refused (the kitchen cooks to that line)", S, async () => { await world({ fix: { orders: [{ id: "o1", restaurant_id: RID, table_number: "3", allergies: [] }] }, settings: mods }); const r = await call("POST", "orders/o1/allergies", { body: { allergies: ["nuts"] } }); return r.status === 400 && /Say why/.test(r.text); });
check(id(), F, "a removed-list change on a dish already served is too late (409)", S, async () => { await run(); const r = await call("POST", "items/i1/removed", { body: { removed: ["onion"], reason: "x" } }); return r.status === 409; });
check(id(), F, "a tip is clamped at ₹1,00,000", S, async () => { const G = await run(); await call("POST", "orders/o1/tip", { body: { amount: 9e9 } }); return G.FIX.orders[0].tip === 100000; });
check(id(), F, "a whole-bill discount is clamped to the bill's taxable base", S, async () => { const G = await run(); await call("POST", "sessions/s1/bill-discount", { body: { amount: 99999 } }); return G.RPCS.find((x) => x.name === "lfh_staff_bill_discount")?.args.p_amount === 400; });
check(id(), F, "a ticket discount is refused while a whole-bill discount is on", S, async () => { await world({ fix: { ...BASE_FIX, sessions: [{ ...BASE_FIX.sessions[0], discount: 50 }] }, settings: mods }); const r = await call("POST", "orders/o1/discount", { body: { amount: 10 } }); return r.status === 409 && /whole-bill discount/.test(r.text); });
check(id(), F, "a body that is not JSON is read as empty, never a crash", S, async () => { await run(); const r = await call("POST", "orders/o1/tip", { body: "{not json" }); return { ok: r.status < 500, note: `${r.status}` }; });
check(id(), F, "a missing id ('undefined' in the path) is refused before any query", S, async () => { const G = await run(); const r = await call("POST", "orders/undefined/tip", { body: {} }); return r.status === 400 && G.SCOPE_LOG.filter((q) => q.table === "orders").length === 0; });
check(id(), F, "an unknown POST from the admin is 404", S, async () => { await run({ who: "admin" }); return (await call("POST", "nope", { body: {}, query: `?rid=${RID}` })).status === 404; });
check(id(), F, "the admin looking at the floor prints NOTHING at the restaurant unless deliberately forced", S, async () => { await world({ who: "admin", fix: { ...BASE_FIX, print_agents: [] }, settings: mods }); const r = await call("POST", "print-jobs", { body: { order_id: "o1" }, query: `?rid=${RID}` }); return { ok: r.status === 200, note: `print-jobs from the admin answered ${r.status} — it queues a KITCHEN reprint deliberately (gated like the KOT menu); the bill door is the one that needs force (verify:print-helper)` }; });
// scope, across everything this block drove
check(id(), F, "a broad driven pass: every statement on a restaurant's table names THIS restaurant (or a row it just read)", S, async () => {
  const G = await run();
  const bodies = [["orders/o1/tip", { amount: 1 }], ["tables/3/tag", { tag: "vip" }], ["orders/o1/allergies", { allergies: [], reason: "x" }], ["sessions/s1/auto-approve", { value: true }], ["calls/c1/attend", {}], ["items/i1/note", { note: "x" }], ["tables/3/pay", { payment_method: "Cash" }]];
  G.SCOPE_LOG.length = 0;
  for (const [p, b] of bodies) await call("POST", p, { body: b });
  const tenant = ["orders", "order_items", "sessions", "table_tags", "waiter_calls", "requests", "session_members", "khata_customers", "menu_items", "settings", "restaurants", "table_merges", "staff_users"];
  const bad = G.SCOPE_LOG.filter((q) => tenant.includes(q.table) && !q.filters.some((f) => (f.col === "restaurant_id" && f.val === RID) || (f.col === "id" && (q.table === "restaurants"))) && !(q.patch && [].concat(q.patch).every((p) => p.restaurant_id === RID)));
  return { ok: G.SCOPE_LOG.length > 20 && bad.length === 0, note: `${G.SCOPE_LOG.length} statements, ${bad.length} without the restaurant${bad.length ? ": " + bad.slice(0, 3).map((b) => `${b.table}:${b.op}`).join(", ") : ""}` };
});
const SEC1 = [1];
check(id(), F, "the route never takes the restaurant from the request body or header (only the sign-in, or the admin's ?rid)", "SRC", () => !/body\??\.restaurant_id|body\??\.rid\b|headers\.get\("x-restaurant/.test(CODE.route) && /const rid = panelRestaurantId\(req, g\);/.test(CODE.route));
