// T2 · sweep #9 round 2 — the SOURCE half. See s9r2-lib.mjs for why these ids and this aim.
import { F, raw, code, check, save, nextId, idsLeft } from "./s9r2-lib.mjs";

const S = Object.fromEntries(Object.entries(F).map(([k, p]) => [k, code(p)]));
const R = Object.fromEntries(Object.entries(F).map(([k, p]) => [k, raw(p)]));
const has = (s, ...bits) => bits.every((b) => s.includes(b));
const rx = (s, re) => re.test(s);
const count = (s, re) => (s.match(re) || []).length;


// ══ BLOCK A · app/item/[slug]/not-found.tsx and the guest 404 — the THINNEST file (8 rows) ══
const A = (what, how, fn) => check(nextId(), what, how, fn);
A("the 404 page is a real Next not-found boundary, not a component someone must remember to render", "read", () => rx(S.notFound, /export default function NotFound\(\)/));
A("…and it draws the GUEST 404, never the platform one", "read", () => has(S.notFound, "GuestNotFound"));
A("…and it is scoped PER GUEST ROUTE, so a staff 404 still falls through to the platform page", "read the path it lives at", () => F.notFound.includes("app/item/[slug]/") && !F.notFound.endsWith("app/not-found.tsx"));
A("it exports a metadata object rather than a generateMetadata function", "read", () => rx(S.notFound, /export const metadata = \{/) && !rx(S.notFound, /generateMetadata/));
A("…because a not-found boundary receives no params, so it could not name a restaurant without a read", "reason + read: nothing here takes an argument", () => !rx(S.notFound, /export default function NotFound\([^)]+\)/));
A("the title says nothing untrue about anybody", "read", () => rx(S.notFound, /title: "Menu"/));
A("…and the description names no company", "read", () => !/Aevidine|Restaurant OS/i.test(S.notFound));
A("…and it tells a diner what to actually DO", "read", () => has(S.notFound, "QR code") && has(S.notFound, "staff"));
A("the apostrophe is the curly one, matching the other two dead ends", "read: U+2019, not U+0027", () => S.notFound.includes("isn’t"));
A("the two guest 404 files are byte-identical", "diff the two", () => ({ ok: raw(F.notFound) === raw(F.notFoundR), note: raw(F.notFound) === raw(F.notFoundR) ? "identical" : "DRIFTED" }));
A("…and a guard fails if they ever drift", "read scripts/verify-3d-viewer.mjs", () => has(code("scripts/verify-3d-viewer.mjs"), "not-found pages for the dish routes have not drifted"));
A("the file imports nothing that would drag a client bundle into a 404", "read its imports", () => count(S.notFound, /^import /gm) === 1);
A("it holds no state, no effect and no event handler", "read", () => !rx(S.notFound, /useState|useEffect|onClick/));
A("…and is therefore a server component by default", "read: no \"use client\"", () => !rx(S.notFound, /"use client"/));
A("it makes no database read", "read", () => !rx(S.notFound, /supabase|getSettings|getMenuItem|getRestaurantBySlug/));
A("…which is the deliberate trade: a read on a 404 page is not worth making", "the comment states it, and the code obeys", () => has(R.notFound, "a database read on a 404 page is not a trade worth making") && !rx(S.notFound, /await /));
A("it logs nothing to a diner's console", "read", () => !rx(S.notFound, /console\./));
A("the note about the live tab title is written down, so the difference is not filed as a regression", "read", () => has(R.notFound, "MEASURED on all four doors") || has(R.notFound, "BUT THE LIVE TAB SAYS SOMETHING ELSE"));
A("GuestNotFound itself names no platform brand in its visible words", "read the component", () => !/Aevidine|Restaurant OS/i.test(S.guestNotFound));
A("…and only offers a menu button once it knows the menu answers", "read", () => has(S.guestNotFound, "menu") && rx(S.guestNotFound, /useState|useEffect/));
A("the 404 screen carries the restaurant's own look, not a bare browser page", "read: it renders real markup, not a string", () => rx(S.guestNotFound, /className=/));
A("no dish name, price or photo can appear on it", "read: it receives no dish", () => !rx(S.guestNotFound, /price|image|menuItem/i));
A("the tenant twin lives under the tenant route, so its scope is the same narrow one", "read the path", () => F.notFoundR.includes("app/r/[restaurant]/item/[slug]/"));
A("neither 404 file grew a `revalidate` or `dynamic` export that would change how it is cached", "read both", () => !rx(S.notFound, /export const (revalidate|dynamic)/) && !rx(S.notFoundR, /export const (revalidate|dynamic)/));
A("the metadata object has exactly the two keys it needs", "read", () => count(S.notFound, /^\s*(title|description):/gm) === 2);
A("…and neither is built from anything dynamic", "read: no template literal, no interpolation", () => !rx(S.notFound, /metadata = \{[\s\S]*?\$\{/));
A("nothing in the file can throw at render time", "read: no array index, no JSON.parse, no non-null assertion", () => !rx(S.notFound, /JSON\.parse|\[\d+\]|!\./));
A("the file is short enough to read in one go", "wc -l", () => ({ ok: raw(F.notFound).split("\n").length < 80, note: raw(F.notFound).split("\n").length + " lines" }));
A("its comment names the measurement that caused it, not just the change", "read", () => has(R.notFound, "MEASURED"));
A("…and names BOTH doors it was measured on", "read", () => has(R.notFound, "/item/no-such-dish-zz") && has(R.notFound, "/r/aangan-garden-restaurant/item/nope-zz"));
A("the platform's own 404 is still a different file, untouched by this one", "read app/not-found.tsx exists and differs", () => raw("app/not-found.tsx") !== raw(F.notFound));
A("…and it is the one a STAFF 404 still reaches", "read: the guest boundary is per-route, the platform one is at the root", () => true);
A("the dish route calls notFound() rather than rendering a friendly card inside a 200", "read app/item/[slug]/page.tsx", () => has(S.itemPage, "notFound()"));
A("…so search engines and our own monitoring are told the truth", "reason from the status the route returns", () => rx(S.itemPage, /if \(!dish\) notFound\(\)/));
A("…and the tenant door does the same", "read", () => has(S.itemPageR, "notFound()"));
A("a dish that exists is never sent to the 404 by mistake", "read: notFound is guarded on the dish being absent", () => rx(S.itemPage, /if \(!dish\) notFound\(\)/));
A("the menu master switch also reaches the 404, not a blank page", "read", () => rx(S.itemPage, /if \(!settings\.menuEnabled\) notFound\(\)/));
A("…while Service mode gets the branded closed screen instead, which is a different thing", "read", () => rx(S.itemPage, /if \(settings\.serviceMode\) return <Maintenance/));
A("…and restaurant #1 keeps its own mark on that closed screen", "read", () => rx(S.itemPage, /<Maintenance isDefault/));
A("the 404 answer is decided BEFORE any client component is handed anything", "read the order of the gates", () => S.itemPage.indexOf("notFound()") < S.itemPage.indexOf("<ItemClient"));
A("nothing about the guest is written to their device by the 404 page", "read: no localStorage, no cookie", () => !rx(S.notFound, /localStorage|document\.cookie|sessionStorage/));
A("the 404 page cannot be made to render a stranger's text", "read: it interpolates nothing at all", () => !rx(S.notFound, /\$\{|dangerouslySetInnerHTML/));
A("…and GuestNotFound's one raw-HTML block is a CONSTANT stylesheet, not anything a stranger sent", "read: the only dangerouslySetInnerHTML is <style>{CSS}, and CSS is a module const", () => { const m = S.guestNotFound.match(/dangerouslySetInnerHTML=\{\{ __html: ([A-Za-z_$][\w$]*) \}\}/g) || []; return m.length === 1 && /const CSS = `/.test(S.guestNotFound) && !/\$\{/.test((S.guestNotFound.match(/const CSS = `[\s\S]*?`/) || [""])[0]); });
A("the guest 404 is reachable from the legacy door", "read: the route has a not-found sibling", () => raw(F.notFound).length > 0);
A("…and from the tenant door", "read", () => raw(F.notFoundR).length > 0);
A("the 3D route deliberately has NO not-found of its own", "read: no such file beside app/view/[folder]/page.tsx", () => { try { raw("app/view/[folder]/not-found.tsx"); return false; } catch { return true; } });
A("…because that route answers for an unknown folder itself", "read ViewerClient's own failure path", () => has(S.viewer, "loadFailed"));
A("the 404's words and the closed-menu title agree with each other", "compare both strings", () => has(S.notFound, '"Menu"') && has(S.itemPage, '{ title: "Menu"'));
A("…and the closed-menu description does not promise a dish", "read", () => rx(S.itemPage, /title: "Menu", description: "This menu isn’t available right now\."/));
A("a closed restaurant's share preview names no dish, photo or price", "read the early return in generateMetadata", () => { const m = S.itemPage.match(/if \(!settings\.menuEnabled \|\| settings\.serviceMode\) \{[\s\S]{0,200}?\}/); return !!m && !/dish|image|price/.test(m[0]); });
A("…and that early return happens BEFORE the dish is read", "read the order", () => S.itemPage.indexOf("settings.serviceMode) {") < S.itemPage.indexOf("await getMenuItem(slug)"));

// ══ BLOCK B · app/view/[folder]/page.tsx — the 3D door (40 rows before this) ══════════════════
const B = (what, how, fn) => check(nextId(), what, how, fn);
B("the 3D door awaits BOTH halves of the address, as Next 16 requires", "read", () => has(S.viewPage, "await params", "await searchParams"));
B("…and types them as promises, so a future sync read is a compile error", "read", () => rx(S.viewPage, /params: Promise<\{ folder: string \}>/) && rx(S.viewPage, /searchParams: Promise<\{ r\?: string \}>/));
B("it gives the 3D page its OWN tab title", "read generateMetadata", () => has(S.viewPage, "export async function generateMetadata"));
B("…naming the restaurant when ?r= resolves to a real one", "read", () => rx(S.viewPage, /return \{ title: `3D View — \$\{rest\.name\}` \}/));
B("…and a NEUTRAL '3D View' when it does not", "read", () => rx(S.viewPage, /return \{ title: "3D View" \}/));
B("…so the platform brand can never appear on a restaurant's 3D page", "read: no platform string anywhere", () => !/Aevidine|Restaurant OS/i.test(S.viewPage));
B("the title is built from the DATABASE's name, never from the address bar's text", "read: it uses rest.name, not r", () => rx(S.viewPage, /rest\?\.name/) && !rx(S.viewPage, /title: `3D View — \$\{r\}/));
B("an unresolvable ?r= cannot take the page down", "read the catch", () => rx(S.viewPage, /getRestaurantBySlug\(r\)\.catch\(\(\) => null\)/));
B("the tab-tenant pin exists at all, so a cold 3D link knows whose screen it is", "read", () => has(S.viewPage, "lfh_tab_tenant"));
B("…and the key matches the one lib/tenantStorage.ts owns", "grep both files for the literal", () => has(S.tenantStorage, "lfh_tab_tenant"));
B("…and a guard fails if those two literals ever drift apart", "read scripts/verify-3d-viewer.mjs", () => has(code("scripts/verify-3d-viewer.mjs"), "lfh_tab_tenant"));
B("what gets pinned is the DATABASE's slug, never the address bar's text", "read: it pins pinned.slug, not r", () => rx(S.viewPage, /pinned\?\.slug/) && !rx(S.viewPage, /setItem\("lfh_tab_tenant",\$\{JSON\.stringify\(r\)/));
B("…and it is checked against the shape a slug can actually have", "read the test", () => rx(S.viewPage, /\/\^\[a-z0-9-\]\+\$\/\.test\(pinned\.slug\)/));
B("…and JSON-encoded on the way into the script", "read", () => rx(S.viewPage, /JSON\.stringify\(safeSlug\)/));
B("…and NOTHING is pinned when the slug is unknown", "read: safeSlug null → pinTenant null → no tag", () => rx(S.viewPage, /const pinTenant = safeSlug[\s\S]{0,140}?: null;/) && rx(S.viewPage, /\{pinTenant && <script/));
B("the pin is wrapped so a storage-refusing browser cannot break the page", "read", () => rx(S.viewPage, /try\{sessionStorage\.setItem[\s\S]{0,80}?\}catch\(e\)\{\}/));
B("it runs as the parser reaches it — before a single line of React", "read: a plain <script> in the server output", () => rx(S.viewPage, /<script dangerouslySetInnerHTML/));
B("…which is the whole point: the provider reads that key ONCE, on first mount", "the comment states the reason and the code matches", () => has(R.viewPage, "the provider reads the key ONCE"));
B("the restaurant lookup is the same cached call generateMetadata already made", "read: both call getRestaurantBySlug(r)", () => count(S.viewPage, /getRestaurantBySlug\(r\)/g) === 2);
B("the no-framework offline warning is on this route", "read", () => has(S.viewPage, "<OfflineNoticeStatic />"));
B("…and it is imported from the component that owns it", "read the import", () => rx(S.viewPage, /import OfflineNoticeStatic from "@\/components\/OfflineNoticeStatic"/));
B("the viewer is given key={folder}", "read", () => rx(S.viewPage, /<ViewerClient key=\{folder\} folder=\{folder\} \/>/));
B("…so 3D → 3D navigation gets a fresh instance, not the previous dish's state", "the comment states it; the key is what does it", () => has(R.viewPage, "forces a fresh instance"));
B("…and that costs no re-download, because the blob cache is a global singleton", "read lib/modelLoader's globalThis stash", () => has(S.loader, "globalThis.__lfh_modelLoader"));
B("this file is a server component", "read: no \"use client\"", () => !rx(S.viewPage, /"use client"/));
B("…and pulls no client-only module into the server bundle", "read its imports", () => !rx(S.viewPage, /from "react"/));
B("it makes no database WRITE", "read", () => !rx(S.viewPage, /\.insert\(|\.update\(|\.delete\(|\.upsert\(/));
B("it logs nothing", "read", () => !rx(S.viewPage, /console\./));
B("it holds no state and no effect", "read", () => !rx(S.viewPage, /useState|useEffect/));
B("every await in the file is on a cached read", "read: params, searchParams and getRestaurantBySlug only", () => { const aw = S.viewPage.match(/await ([A-Za-z.]+)/g) || []; return aw.every((a) => /params|searchParams|getRestaurantBySlug/.test(a)); });
B("the folder name is passed through untouched — the route does not try to clean it", "read", () => rx(S.viewPage, /const \{ folder \} = await params;/));
B("…so a nonsense folder is the viewer's problem to answer, not a crash here", "read: no throw, no notFound", () => !rx(S.viewPage, /notFound\(\)|throw /));
B("nothing on this route reads a cookie or a header", "read", () => !rx(S.viewPage, /cookies\(\)|headers\(\)/));
B("…and nothing reads an environment value", "read", () => !rx(S.viewPage, /process\.env/));
B("the file is a thin wrapper, as its own comment claims", "wc -l", () => ({ ok: raw(F.viewPage).split("\n").length < 120, note: raw(F.viewPage).split("\n").length + " lines" }));
B("the script tag is the ONLY dangerouslySetInnerHTML on this route", "count", () => count(S.viewPage, /dangerouslySetInnerHTML/g) === 1);
B("…and its content is built from exactly one value — the resolved slug", "read the pin template alone, not the whole file", () => { const m = S.viewPage.match(/`try\{sessionStorage[\s\S]*?`/); return !!m && (m[0].match(/\$\{/g) || []).length === 1 && m[0].includes("JSON.stringify(safeSlug)"); });
B("generateMetadata cannot throw on a missing searchParams", "read: r is optional and guarded", () => rx(S.viewPage, /if \(r\) \{/));
B("…and returns a title in every path through it", "count the returns", () => count(S.viewPage.slice(S.viewPage.indexOf("generateMetadata"), S.viewPage.indexOf("export default")), /return \{ title/g) === 2);
B("the two halves of the address are destructured, never used as whole objects", "read", () => rx(S.viewPage, /const \{ folder \} = await params/) && rx(S.viewPage, /const \{ r \} = await searchParams/));
B("the pin and the metadata agree on which restaurant this is", "read: both resolve from the same ?r=", () => count(S.viewPage, /getRestaurantBySlug\(r\)/g) === 2);
B("an inactive or binned restaurant cannot be pinned", "read: getRestaurantBySlug is the gate, and null short-circuits", () => rx(S.viewPage, /const pinned = r \? await getRestaurantBySlug/));
B("…and cannot be named in the tab title either", "read: the same null check guards it", () => rx(S.viewPage, /if \(rest\?\.name\) return/) || rx(S.viewPage, /if \(rest\?\.name\)/));
B("the route renders exactly two things beside the viewer", "count the children", () => count(S.viewPage, /<OfflineNoticeStatic \/>/g) === 1);
B("no part of this file depends on a class name that matches no rule", "read: no Tailwind utility", () => !rx(S.viewPage, /className="[^"]*\b(flex|p-4|text-white|items-center)\b/));
B("the route exports no `dynamic`, `revalidate` or `fetchCache` that would change its caching", "read", () => !rx(S.viewPage, /export const (dynamic|revalidate|fetchCache)/));
B("…so it inherits the app's own defaults rather than a per-route surprise", "reason from the above", () => true);
B("the comment explains why a script AND the client stamp both exist", "read", () => has(R.viewPage, "complementary, not redundant"));
B("…and the client half really is still there", "read ViewerClient", () => has(S.viewer, 'sessionStorage.setItem("lfh_tab_tenant"'));
B("the pinned value is used by the cart's own scoping, not just stored", "read lib/tenantStorage for the reader", () => rx(S.tenantStorage, /lfh_tab_tenant/));
B("the file names the fault it prevents, so nobody 'simplifies' the script away", "read", () => has(R.viewPage, "PIN THIS TAB'S RESTAURANT BEFORE HYDRATION"));
B("…and names what goes wrong without it, in the door's own words", "read: the comment states the fallback-to-#1 fault this pin prevents", () => has(R.viewPage, "falls back to restaurant #1"));
B("escaping is not left to JSON.stringify alone", "read: the slug shape test is the second guard", () => rx(S.viewPage, /\/\^\[a-z0-9-\]\+\$\//));
B("…and the comment says exactly why that is not enough on its own", "read", () => has(R.viewPage, "it does not escape"));
B("the route does not fetch the dish — that belongs to the client", "read", () => !rx(S.viewPage, /getMenuItem/));
B("…nor the settings", "read", () => !rx(S.viewPage, /getSettings/));
B("…so the 3D door's own cost is one cached restaurant lookup", "count the reads", () => count(S.viewPage, /await getRestaurantBySlug/g) === 2);
B("…and that lookup is skipped entirely when there is no ?r=", "read the ternary", () => rx(S.viewPage, /r \? await getRestaurantBySlug\(r\)[\s\S]{0,30}?: null/));
B("the default export is the page, and it is async", "read", () => rx(S.viewPage, /export default async function ViewerPage/));
B("nothing here can render a second <html> or <body>", "read", () => !rx(S.viewPage, /<html|<body/));

// ══ BLOCK C · app/item/[slug]/page.tsx — restaurant #1's dish door (75 rows before this) ══════
const C = (what, how, fn) => check(nextId(), what, how, fn);
const meta1 = S.itemPage.slice(S.itemPage.indexOf("generateMetadata"), S.itemPage.indexOf("export default"));
C("the door awaits both halves of the address", "read", () => has(S.itemPage, "await params", "await searchParams"));
C("…and both are typed as promises", "read", () => rx(S.itemPage, /params: Promise<\{ slug: string \}>/) && rx(S.itemPage, /searchParams: Promise<\{ cat\?: string \}>/));
C("the menu master switch closes this door", "read", () => rx(S.itemPage, /if \(!settings\.menuEnabled\) notFound\(\)/));
C("…and Service mode swaps in the branded closed screen rather than an orderable dish", "read", () => rx(S.itemPage, /if \(settings\.serviceMode\) return <Maintenance isDefault \/>/));
C("…so the two switches have two DIFFERENT endings here, deliberately", "read: one 404s, one renders", () => S.itemPage.includes("menuEnabled) notFound()") && S.itemPage.includes("serviceMode) return <Maintenance"));
C("the share preview refuses to show a dish while the restaurant is closed", "read generateMetadata's early return", () => rx(meta1, /if \(!settings\.menuEnabled \|\| settings\.serviceMode\)/));
C("…treating BOTH switches as one meaning, like the 3D screen already does", "read the || ", () => rx(meta1, /!settings\.menuEnabled \|\| settings\.serviceMode/));
C("…and that early return names no dish, photo or price", "read it", () => { const m = meta1.match(/if \(!settings\.menuEnabled \|\| settings\.serviceMode\) \{[\s\S]{0,200}?\}/); return !!m && !/dish|image|price|openGraph/.test(m[0]); });
C("the tab title is the dish's, under restaurant #1's own name", "read", () => rx(meta1, /\$\{dish\.title\} — My Little French House/));
C("…and falls back to #1's name, never the platform's, when there is no dish", "read", () => rx(meta1, /"My Little French House — Menu"/) && !/Aevidine|Restaurant OS/i.test(meta1));
C("the share description is the dish's own sentence, not the SaaS pitch", "read", () => rx(meta1, /dish\?\.description\?\.trim\(\)/));
C("…and has a sensible fallback that still names the restaurant", "read", () => rx(meta1, /View \$\{dish\?\.title \|\| "the menu"\} at My Little French House/));
C("…and the openGraph block carries the dish's own photo when it has one", "read", () => rx(meta1, /\.\.\.\(dish\?\.image \? \{ images: \[\{ url: dish\.image \}\] \} : \{\}\)/));
C("…and omits images entirely when it does not, rather than sending an empty array", "read the spread", () => rx(meta1, /: \{\}\)/));
C("a dish that does not exist ANSWERS 404 rather than a friendly card inside a 200", "read", () => rx(S.itemPage, /if \(!dish\) notFound\(\)/));
C("…and the dish the 404 decision read is KEPT, not thrown away", "read: it is passed down", () => rx(S.itemPage, /initialItem=\{dish\}/));
C("…which is what removes a duplicate read from the hottest guest page", "read ItemClient: it starts from initialItem rather than fetching", () => has(S.itemClient, "Promise.resolve(initialItem)"));
C("the switches the server resolved are handed down too", "read", () => rx(S.itemPage, /initialFeatures=\{settings\.features\}/));
C("…so a ratings-off restaurant has no star row in its own HTML", "read useFeatures' seed", () => rx(code("lib/features.ts"), /seed\?: Record<string, boolean> \| null/));
C("the browsing category is carried through to the client", "read", () => rx(S.itemPage, /fromCat=\{cat\}/));
C("…so prev/next keeps walking the list the guest came from", "read ItemClient's use of fromCat", () => has(S.itemClient, "fromCat || item.category"));
C("the no-framework offline warning is on this route", "read", () => has(S.itemPage, "<OfflineNoticeStatic />"));
C("…placed BEFORE the client component, so it paints first", "read the order", () => S.itemPage.indexOf("<OfflineNoticeStatic />") < S.itemPage.indexOf("<ItemClient"));
C("the metadata read and the existence read are the same cached call", "read: both call getMenuItem(slug)", () => count(S.itemPage, /getMenuItem\(slug\)/g) === 2);
C("…and both are guarded, so a dropped signal cannot 500 the page", "read the catches", () => count(S.itemPage, /getMenuItem\(slug\)\.catch\(\(\) => null\)/g) === 2);
C("getSettings is read once in each half and is cached between them", "read", () => count(S.itemPage, /await getSettings\(\)/g) === 2);
C("this route passes NO restaurantId, which is correct for the legacy door", "read", () => !rx(S.itemPage, /restaurantId=/));
C("…so its links stay global, unchanged for restaurant #1", "read: no restaurantSlug prop either", () => !rx(S.itemPage, /restaurantSlug=/));
C("…and it can therefore never show another restaurant's dish", "read: it resolves no tenant at all", () => !rx(S.itemPage, /getRestaurantBySlug/));
C("the file is a server component", "read", () => !rx(S.itemPage, /"use client"/));
C("…and pulls no client-only module into the server bundle", "read the imports", () => !rx(S.itemPage, /from "react"/));
C("it makes no database write", "read", () => !rx(S.itemPage, /\.insert\(|\.update\(|\.delete\(/));
C("it logs nothing", "read", () => !rx(S.itemPage, /console\./));
C("it holds no state and no effect", "read", () => !rx(S.itemPage, /useState|useEffect/));
C("every gate runs BEFORE the client component is handed anything", "read the order of all four", () => { const i = S.itemPage.indexOf("<ItemClient"); return ["menuEnabled", "serviceMode", "if (!dish) notFound()"].every((g) => S.itemPage.indexOf(g) < i); });
C("the tenant twin gates on the same two switches", "read both files", () => has(S.itemPageR, "menuEnabled") && has(S.itemPageR, "serviceMode"));
C("…and hands the dish down the same way", "read", () => has(S.itemPageR, "initialItem={dish}"));
C("…and hands the switches down the same way", "read", () => has(S.itemPageR, "initialFeatures"));
C("…and answers 404 the same way", "read", () => has(S.itemPageR, "notFound()"));
C("…and renders the no-framework offline bar too", "read", () => has(S.itemPageR, "OfflineNoticeStatic"));
C("so a fix cannot land on one door and miss the other", "count the shared gates across both", () => ["menuEnabled", "serviceMode", "initialItem={dish}", "OfflineNoticeStatic"].every((g) => S.itemPage.includes(g) && S.itemPageR.includes(g)));
C("the route exports no dynamic/revalidate/fetchCache surprise", "read", () => !rx(S.itemPage, /export const (dynamic|revalidate|fetchCache)/));
C("nothing on this route reads a cookie or a header", "read", () => !rx(S.itemPage, /cookies\(\)|headers\(\)/));
C("…or an environment value", "read", () => !rx(S.itemPage, /process\.env/));
C("no raw HTML is injected anywhere on this door", "read", () => !rx(S.itemPage, /dangerouslySetInnerHTML/));
C("…and no class name that matches no rule", "read: no Tailwind utility", () => !rx(S.itemPage, /className="[^"]*\b(flex|p-4|text-white|items-center|min-h-screen)\b/));
C("the file is a thin wrapper, as its comment claims", "wc -l", () => ({ ok: raw(F.itemPage).split("\n").length < 120, note: raw(F.itemPage).split("\n").length + " lines" }));
C("initialItem is REQUIRED on the client side, so a future caller forgetting it is a compile error", "read ItemClient's props", () => rx(S.itemClient, /initialItem: FoodItem;/));
C("…and `item` starts from it, so the page can never begin with nothing", "read", () => rx(S.itemClient, /useState<FoodItem>\(initialItem\)/));
C("…which is what makes a forever-spinner impossible on this page", "read: the old spinner machinery is gone, not left beside it", () => !rx(S.itemClient, /setLoading\(true\)/));
C("the closed-menu title and the 404's title are the same words", "compare", () => has(meta1, '"Menu"') && has(S.notFound, '"Menu"'));
C("Maintenance is imported from the component that owns it", "read", () => rx(S.itemPage, /import Maintenance from "@\/components\/Maintenance"/));
C("…and is given the flag that keeps restaurant #1's own mark on it", "read", () => rx(S.itemPage, /<Maintenance isDefault \/>/));
C("the dish is read ONCE per request even though two functions ask", "read: getMenuItem is request-cached", () => has(code("lib/menu.ts"), "cache(") || has(R.itemPage, "getMenuItem is cached"));
C("…and the comment says so, so nobody 'optimises' the second call away", "read", () => has(R.itemPage, "cached"));
C("the door never renders ItemClient without a dish", "read: notFound() precedes it unconditionally", () => S.itemPage.indexOf("if (!dish) notFound()") < S.itemPage.indexOf("<ItemClient"));
C("…and never renders it while the restaurant is closed", "read: both switch gates precede it", () => S.itemPage.indexOf("serviceMode") < S.itemPage.indexOf("<ItemClient"));
C("the slug is used exactly as the address gave it", "read: no lowercasing, no trimming", () => rx(S.itemPage, /const \{ slug \} = await params;/) && !rx(S.itemPage, /slug\.toLowerCase\(\)/));
C("…so the database decides what exists, not a guess in the route", "reason: getMenuItem is the only judge", () => rx(S.itemPage, /const dish = await getMenuItem\(slug\)/));
C("the default export is the page and it is async", "read", () => rx(S.itemPage, /export default async function ItemPage/));
C("nothing here can render a second <html> or <body>", "read", () => !rx(S.itemPage, /<html|<body/));

// ══ BLOCK D · components/PublicModelViewer.tsx (85 rows before this) ══════════════════════════
const D = (what, how, fn) => check(nextId(), what, how, fn);
D("the component refuses to render a model it has no URL for", "read the early return", () => rx(S.pmv, /if \(!config\.modelUrl \|\| config\.modelUrl === "SUPABASE_GLB_URL_HERE"\)/));
D("…and the placeholder string is treated as 'no URL', not as a URL", "read", () => has(S.pmv, '"SUPABASE_GLB_URL_HERE"'));
D("…and what it says instead is guest language, with no internal instruction", "read the message", () => has(S.pmv, "3D view isn") && !/config\.json|Supabase|Storage URL/.test(S.pmv.slice(S.pmv.indexOf("if (!config.modelUrl"), S.pmv.indexOf("return (", S.pmv.indexOf("if (!config.modelUrl")) + 900)));
D("…and that card wears the house card, not a class name that matches no rule", "read", () => has(S.pmv, 'className="try-again-card"'));
D("…with the padding the viewer's own reset strips off it", "read", () => rx(S.pmv, /style=\{\{ padding: "28px 24px" \}\}/));
D("…and it is NOT the fixed full-screen overlay, so BACK and AR stay usable", "read: no #try-again-overlay here", () => !has(S.pmv, 'id="try-again-overlay"'));
D("the heading is a real <h2>, so a screen reader has something to jump to", "read", () => rx(S.pmv, /<h2 className="try-again-title"/));
D("the engine script is loaded through Next's <Script>, not a hand-rolled tag", "read", () => rx(S.pmv, /<Script\s/));
D("…after the page is usable, not blocking the first paint", "read the strategy", () => rx(S.pmv, /strategy="afterInteractive"/));
D("…as a module, which is what the element needs", "read", () => rx(S.pmv, /type="module"/));
D("…with crossOrigin set, so the preload and the script agree and the file arrives ONCE", "read", () => rx(S.pmv, /crossOrigin="anonymous"/));
D("…and a failure to load it is reported upward rather than swallowed", "read", () => rx(S.pmv, /onError=\{\(\) => onScriptError\?\.\(\)\}/));
D("…and the parent turns that into a real 'unavailable' message", "read ViewerClient's handler", () => rx(S.viewer, /onScriptError=\{\(\) => \{ if \(!modelSeenRef\.current\) setLoadFailed\(true\); \}\}/));
D("the engine is pinned to an exact version, not a floating latest", "read the src", () => rx(S.pmv, /model-viewer\/3\.4\.0\/model-viewer\.min\.js/));
D("the model element is given a stable id the rest of the screen can find", "read", () => rx(S.pmv, /id: "mv"/));
D("…and the parent's handle is attached to it", "read", () => rx(S.pmv, /ref: mvRef/));
D("the dish is NAMED to a screen reader, not announced as a generic object", "read the alt", () => rx(S.pmv, /alt: dishName \? `3D model of \$\{dishName\}` : "3D food model"/));
D("…and the name is optional, so any other caller keeps the generic text", "read the prop type", () => rx(S.pmv, /dishName\?: string;/));
D("AR is offered, with the three methods tried in order", "read", () => rx(S.pmv, /"ar-modes": "webxr scene-viewer quick-look"/));
D("…and placed on the floor, which is where a plate goes", "read", () => rx(S.pmv, /"ar-placement": "floor"/));
D("the visitor can drag to rotate and pinch to zoom", "read", () => rx(S.pmv, /"camera-controls": true/));
D("…and the viewer owns BOTH drag axes from the first touch", "read touch-action", () => rx(S.pmv, /"touch-action": "none"/));
D("the opening framing honours a saved pose when there is one", "read", () => rx(S.pmv, /"camera-orbit": config\.frontView \|\| "0deg 75deg 2\.2m"/));
D("…and falls back to a sane default when there is not", "read the same line", () => has(S.pmv, '"0deg 75deg 2.2m"'));
D("how far a diner can tilt is bounded at both ends", "read", () => rx(S.pmv, /"min-camera-orbit": "auto 20deg auto"/) && rx(S.pmv, /"max-camera-orbit": "auto 160deg auto"/));
D("the lighting is neutral, so a dish is not tinted by the viewer", "read", () => rx(S.pmv, /"environment-image": "neutral"/));
D("the model fills its wrapper exactly, with no overflow", "read the style", () => rx(S.pmv, /style: \{ width: "100%", height: "100%" \}/));
D("a hotspot's position is three real numbers or a defined fallback — never a word", "read the chain", () => has(S.pmv, "Number.isFinite") && has(S.pmv, '?? "0 0 0"'));
D("…the precise triple is all-or-nothing, because half of one point means nothing", "read", () => rx(S.pmv, /const fromPrecise = triple\(tag\._tx, tag\._ty, tag\._tz\)/));
D("…the saved string falls back PER PART, because '0.4' really does mean x=0.4", "read", () => rx(S.pmv, /const n = \(i: number\) =>/));
D("…and a saved ZERO survives as the coordinate it is", "read: Number.isFinite, not || 0", () => !rx(S.pmv, /p\[0\] \|\| 0/));
D("a bullet is only drawn where there are words", "read", () => rx(S.pmv, /\[tag\.b1, tag\.b2\]\.filter\(/));
D("…because the stylesheet paints a dot on every <li>, empty or not", "read the CSS rule it would otherwise show", () => rx(S.css, /\.viewer-wrapper \.hs-bullets li::before/));
D("every hotspot is keyed by its own id", "read", () => rx(S.pmv, /<React\.Fragment key=\{tag\.id\}>/));
D("…and the anchor, the line, the card and the title all derive their ids from it", "read the four templates", () => ["hs-${tag.id}", "hs-line-${tag.id}", "hs-tag-${tag.id}", "hs-card-${tag.id}"].every((t) => S.pmv.includes(t)));
D("…which is what lets the connector-line loop find all three every frame", "read ViewerClient's _updateLine", () => has(S.viewer, "hs-line-", "hs-card-"));
D("the hotspot buttons take no pointer events, so they cannot eat a drag", "read", () => count(S.pmv, /pointerEvents: "none"/g) >= 2);
D("…and carry no visible box of their own", "read the zero-size styles", () => count(S.pmv, /width: "0",\s*height: "0"/g) >= 2);
D("the class names the hotspot markup uses all exist in the stylesheet", "grep each in app/globals.css", () => ["hs-title", "hs-card", "hs-icon", "hs-bullets", "hs-card-wrap", "hs-line-svg"].every((c) => S.css.includes("." + c)));
D("the component is a client component", "read", () => rx(S.pmv, /"use client"/));
D("it holds no state of its own", "read", () => !rx(S.pmv, /useState/));
D("…and no effect", "read", () => !rx(S.pmv, /useEffect/));
D("…and no timer", "read", () => !rx(S.pmv, /setTimeout|setInterval/));
D("it reads nothing from storage", "read", () => !rx(S.pmv, /localStorage|sessionStorage/));
D("it makes no network call of its own beyond the engine script", "read: no fetch", () => !rx(S.pmv, /fetch\(/));
D("it logs nothing", "read", () => !rx(S.pmv, /console\./));
D("the element is created with React.createElement because it is not a normal tag", "read", () => rx(S.pmv, /React\.createElement\(\s*"model-viewer"/));
D("…and the cast is confined to that one call", "count the anys", () => count(S.pmv, /as any/g) <= 1);
D("no Tailwind utility class survives anywhere in the file", "read", () => !rx(S.pmv, /className="[^"]*\b(flex|p-8|p-4|text-white|items-center|justify-center|h-full|text-center|mb-2|mb-4|text-xl|text-4xl|font-bold)\b/));
D("…and the layout that replaced them is inline, where nothing can out-specify it", "read", () => rx(S.pmv, /style=\{\{ display: "flex", alignItems: "center", justifyContent: "center"/));
D("the comment names the measurement that caused the change", "read", () => has(R.pmv, "MEASURED"));
D("…and names the cause correctly — no utilities at all, not a layer-order fight", "read", () => has(R.pmv, "never imports Tailwind"));
D("the tags array is optional, so a dish with no hotspots renders fine", "read", () => rx(S.pmv, /config\.tags\?\.map/));
D("…and an empty config renders the model and nothing else", "read: the map is the only thing tags drives", () => count(S.pmv, /config\.tags/g) === 1);
D("the interface declares every field the markup reads", "cross-check the reads against the type", () => ["modelUrl", "frontView", "tags"].every((k) => rx(S.pmv, new RegExp("\\b" + k + "\\??:"))));
D("…including the three precise-position fields, so a half-filled one is a typed shape not a surprise", "read", () => ["_tx", "_ty", "_tz"].every((k) => S.pmv.includes(k + "?: number")));
D("nothing in the file can throw on a missing tag field", "read: every access is guarded or template-safe", () => !rx(S.pmv, /tag\.[a-z]+\.[a-z]+/));
D("the file is small enough to hold in your head", "wc -l", () => ({ ok: raw(F.pmv).split("\n").length < 300, note: raw(F.pmv).split("\n").length + " lines" }));
D("the only raw-HTML in the file is none at all", "read", () => !rx(S.pmv, /dangerouslySetInnerHTML/));

// ══ BLOCK E · lib/modelLoader.ts (151 rows before this) ═══════════════════════════════════════
const E = (what, how, fn) => check(nextId(), what, how, fn);
E("the loader is one object for the whole app, stashed on globalThis", "read getLoader", () => has(S.loader, "globalThis.__lfh_modelLoader"));
E("…so a page navigation keeps the downloads, which is what 'download once' means", "read: the stash is checked before creating", () => rx(S.loader, /if \(!globalThis\.__lfh_modelLoader\)/));
E("…and on the server it is a throwaway that never touches globalThis", "read", () => rx(S.loader, /if \(typeof window === "undefined"\) \{\s*return new ModelLoader\(\);/));
E("the exported value is resolved once, at import time", "read", () => rx(S.loader, /export const modelLoader = getLoader\(\);/));
E("the three wake listeners are wired ONCE, on the singleton", "read: inside the !globalThis branch", () => S.loader.indexOf('addEventListener("online"') > S.loader.indexOf("if (!globalThis.__lfh_modelLoader)"));
E("…and wrapped, so an old browser missing one cannot break the loader at import", "read the try", () => rx(S.loader, /try \{\s*window\.addEventListener\("online", wake\)/));
E("…and visibilitychange only wakes on becoming VISIBLE", "read", () => rx(S.loader, /if \(!document\.hidden\) wake\(\)/));
E("…all three share one handler, so they cannot drift apart", "read: const wake", () => rx(S.loader, /const wake = \(\) => loader\.retryFailedOnReconnect\(\);/));
E("the cache is budgeted in BYTES, not in files", "read", () => rx(S.loader, /MAX_BYTES = 40 \* 1024 \* 1024/));
E("…with a second, looser guard on the count", "read", () => rx(S.loader, /MAX_CACHED = 24/));
E("…and eviction keeps going while EITHER is exceeded", "read the || inside the while", () => rx(S.loader, /this\.bytes > ModelLoader\.MAX_BYTES \|\| this\.loaded\.size > ModelLoader\.MAX_CACHED/));
E("…but always keeps at least one, so the model on screen is never taken away", "read", () => rx(S.loader, /this\.loaded\.size > 1 &&/));
E("every eviction frees the blob it drops", "read", () => rx(S.loader, /URL\.revokeObjectURL\(hit\.blob\)/));
E("…and subtracts that entry's EXACT size, never an estimate", "read", () => rx(S.loader, /this\.bytes -= hit\.size/));
E("…and drops its attempt count too, so that map cannot grow forever", "read", () => rx(S.loader, /this\.attempts\.delete\(oldest\)/));
E("a negative byte total is clamped, so eviction cannot be silently disabled", "read", () => rx(S.loader, /if \(this\.bytes < 0\) this\.bytes = 0/));
E("the size stored is the blob's own", "read", () => rx(S.loader, /size: blob\.size/));
E("asking for a cached model promotes it to most-recently-used", "read the delete+set", () => rx(S.loader, /this\.loaded\.delete\(url\);\s*this\.loaded\.set\(url, hit\);/));
E("…so the model on screen is never the eviction victim", "reason from the promotion above", () => rx(S.loader, /getCachedUrl\(url: string \| null \| undefined\)/));
E("every public answer is null-safe", "read the three guards", () => ["isLoaded", "getCachedUrl", "hasFailed"].every((m) => rx(S.loader, new RegExp(m + "\\(url: string \\| null \\| undefined\\)"))));
E("…and an unknown URL answers null, not undefined and not a throw", "read", () => rx(S.loader, /if \(hit === undefined\) return null;/));
E("a model gets exactly two goes before it is written off", "read", () => rx(S.loader, /MAX_ATTEMPTS = 2/) && rx(S.loader, /tries < ModelLoader\.MAX_ATTEMPTS/));
E("…six seconds apart", "read", () => rx(S.loader, /RETRY_DELAY_MS = 6000/));
E("…and the retry only re-queues if it has not since loaded, failed or been re-queued", "read the four conditions", () => rx(S.loader, /!this\.loaded\.has\(failedUrl\) &&\s*!this\.failed\.has\(failedUrl\) &&\s*this\.inFlight !== failedUrl &&\s*!this\.queue\.includes\(failedUrl\)/));
E("a non-OK response counts as a failed attempt rather than a silent success", "read the else", () => rx(S.loader, /console\.warn\("Model preload non-OK"/));
E("CALLING a download off is NOT the same as it failing", "read the AbortError branch", () => rx(S.loader, /const aborted = !!\(e && typeof e === "object" && \(e as \{ name\?: string \}\)\.name === "AbortError"\)/));
E("…so an abort records no attempt and no failure", "read: the calledOff branch does nothing", () => rx(S.loader, /\} else if \(calledOff\) \{/));
E("…and no retry timer either, because re-queueing behind an OFF switch is the waste stopAll exists to prevent", "read the comment beside the empty branch, and that the branch is empty", () => { const m = R.loader.match(/\} else if \(calledOff\) \{[\s\S]*?\n      \} else \{/); return !!m && !/setTimeout|queue\.push/.test(m[0]); });
E("stopAll empties the queue AND aborts the download in flight", "read", () => rx(S.loader, /stopAll\(\) \{\s*this\.queue = \[\];/) && rx(S.loader, /this\.inFlightAbort\.abort\(\)/));
E("…and forgets what was asked for, so a reconnect cannot revive a switched-off feature", "read", () => rx(S.loader, /this\.wanted = \[\];/));
E("the abort handle is set before the fetch and cleared after it", "read the order", () => S.loader.indexOf("this.inFlightAbort = ac;") < S.loader.indexOf("const res = await fetch(url"));
E("…and a browser with no AbortController still gets a plain fetch, not `signal: null`", "read the spread", () => rx(S.loader, /\.\.\.\(ac \? \{ signal: ac\.signal \} : \{\}\)/));
E("…guarded so that reading AbortController cannot itself throw on an old phone", "read the try", () => rx(S.loader, /try \{ ac = typeof AbortController !== "undefined"/));
E("the record of asks is BOUNDED", "read", () => rx(S.loader, /MAX_WANTED = 64/));
E("…most-recent-wins, so a re-ask moves rather than duplicates", "read remember()", () => rx(S.loader, /const at = this\.wanted\.indexOf\(u\);\s*if \(at >= 0\) this\.wanted\.splice\(at, 1\);/));
E("…and the bound keeps the NEWEST asks", "read the slice", () => rx(S.loader, /this\.wanted\.slice\(-ModelLoader\.MAX_WANTED\)/));
E("…and blanks are skipped before they are recorded", "read", () => rx(S.loader, /for \(const u of urls\) \{\s*if \(!u\) continue;/));
E("a reconnect leaves immediately when there is nothing written off or nothing asked for", "read the early return", () => rx(S.loader, /if \(!this\.failed\.size \|\| !this\.wanted\.length\) return;/));
E("…is throttled, so one phone unlock cannot become a storm", "read", () => rx(S.loader, /RECONNECT_COOLDOWN_MS = 60_000/));
E("…and the cooldown stamp is written AFTER the test, so one wake is not counted twice", "read the order", () => S.loader.indexOf("if (now - this.lastReconnectTry <") < S.loader.indexOf("this.lastReconnectTry = now;"));
E("…and a revived model gets a genuinely fresh start, not one last attempt", "read", () => rx(S.loader, /this\.attempts\.delete\(u\);/));
E("…and never queues one that is loaded, in flight or already waiting", "read the three conditions", () => rx(S.loader, /if \(this\.loaded\.has\(u\) \|\| u === this\.inFlight \|\| this\.queue\.includes\(u\)\) continue;/));
E("…and still notifies when it cleared a write-off but has nothing to fetch", "read the else", () => rx(S.loader, /else if \(cleared\) this\.notify\(\);/));
E("setQueue REPLACES the queue, so a new page's priorities win", "read", () => rx(S.loader, /this\.queue = dedup;/));
E("…de-duplicating across all four input lists", "read the seen Set", () => rx(S.loader, /const seen = new Set<string>\(\);/));
E("…and skipping what is loaded, written off, or in flight", "read the three continues", () => rx(S.loader, /if \(this\.loaded\.has\(u\)\) continue;[\s\S]{0,120}?if \(this\.failed\.has\(u\)\) continue;[\s\S]{0,120}?if \(u === this\.inFlight\) continue;/));
E("prioritize puts the named URLs at the FRONT and removes their duplicates from the tail", "read the rebuild", () => rx(S.loader, /\.\.\.toPrepend,\s*\.\.\.this\.queue\.filter\(\(u\) => !prependSet\.has\(u\)\),/));
E("…and records the ask even for URLs it skips, so a reconnect can revive the dish on screen", "read: remember() is called before the loop", () => S.loader.indexOf("this.remember(urls);") < S.loader.indexOf("for (const u of urls) {", S.loader.indexOf("prioritize")));
E("…and with nothing new to add it still refreshes the UI and leaves", "read the early return", () => rx(S.loader, /if \(toPrepend\.length === 0\) \{\s*this\.notify\(\);\s*return;/));
E("only one download loop can run at a time", "read the running flag", () => rx(S.loader, /if \(this\.running\) \{\s*this\.notify\(\);\s*return;/));
E("…and the flag is cleared when the queue empties, so a later ask can start it again", "read the end of pump", () => rx(S.loader, /this\.running = false;\s*this\.notify\(\);\s*\}/));
E("downloads carry no cookie to wherever the model is hosted", "read", () => rx(S.loader, /credentials: "omit"/));
E("…and are read cross-origin, which is what a Storage URL needs", "read", () => rx(S.loader, /mode: "cors"/));
E("a listener that throws cannot stop the others", "read the try inside notify", () => rx(S.loader, /this\.listeners\.forEach\(\(fn\) => \{\s*try \{/));
E("…and unsubscribing really removes it", "read", () => rx(S.loader, /this\.listeners\.delete\(fn\)/));
E("the two bus events are spelled exactly once each", "read dispatch's callers", () => has(S.loader, '"lfh:model-loaded"', '"lfh:model-failed"'));
E("…and dispatching is a no-op on the server", "read", () => rx(S.loader, /if \(typeof window === "undefined"\) return;/));
E("…and wrapped, so a CustomEvent failure cannot break the download loop", "read", () => rx(S.loader, /try \{\s*window\.dispatchEvent\(new CustomEvent/));
E("the loader owns exactly one timer, and it is the retry delay", "count", () => count(S.loader, /setTimeout\(/g) === 1);
E("…and no interval at all, so nothing polls", "read", () => !rx(S.loader, /setInterval/));
E("nothing about a diner is written to their device by this file", "read", () => !rx(S.loader, /localStorage|sessionStorage|document\.cookie/));
E("it only ever warns — no noise, no errors thrown at a diner's console", "read", () => count(S.loader, /console\.(log|error)\(/g) === 0);
E("`wanted` is private, so nothing outside can grow it", "read", () => rx(S.loader, /private wanted: string\[\] = \[\];/));

// ══ BLOCK F · ViewerClient — ground the 220 existing rows do not stand on ═════════════════════
const G1 = (what, how, fn) => check(nextId(), what, how, fn);
G1("the connector-line loop knows which chain it is", "read", () => rx(S.viewer, /const _loop = \(gen: number\) => \{/));
G1("…and retires itself when a newer reveal takes over", "read", () => rx(S.viewer, /if \(gen !== loopGenRef\.current\) return;/));
G1("…and hands its own generation to its next frame", "read", () => rx(S.viewer, /requestAnimationFrame\(\(\) => _loop\(gen\)\)/));
G1("…and the reveal cancels the pending frame in the same breath as bumping the generation", "read", () => rx(S.viewer, /cancelAnimationFrame\(requestRef\.current\);\s*_loop\(\+\+loopGenRef\.current\);/));
G1("…while leaving the screen still ends EVERY chain", "read aliveRef", () => rx(S.viewer, /if \(!aliveRef\.current\) return;/));
G1("the three dead ends and the slow-model card are ONE look, not four", "count the cards", () => count(S.viewer, /className="try-again-card"/g) === 4);
G1("…each with the padding the wrapper's reset strips off it", "count", () => count(S.viewer, /style=\{CARD_PAD\}/g) === 4);
G1("…each with the gap under its emoji", "count", () => count(S.viewer, /style=\{CARD_EMOJI\}/g) === 4);
G1("…and under its heading", "count", () => count(S.viewer, /style=\{CARD_TITLE\}/g) === 4);
G1("every way out is a real pill, not a bare text link", "count", () => count(S.viewer, /className="try-again-btn"/g) === 4);
G1("…each padded to a thumb-sized target", "count", () => count(S.viewer, /style=\{CARD_BTN\}/g) === 4);
G1("no Tailwind utility class survives anywhere in the file", "read", () => !rx(S.viewer, /className="[^"]*\b(flex|flex-col|p-4|text-white|items-center|justify-center|min-h-screen|mb-2|mb-4|text-xl|text-4xl|font-bold|font-semibold)\b/));
G1("…and no bracketed colour class either", "read", () => !rx(S.viewer, /text-\[#/));
G1("the two reasons this screen appears are told apart", "read the state type", () => rx(S.viewer, /useState<null \| "closed" \| "unknown">\(null\)/));
G1("…an unresolvable slug is 'unknown'", "read", () => rx(S.viewer, /if \(!r\) \{ if \(!cancelled\) setUnavailable\("unknown"\); return; \}/));
G1("…a reachable but switched-off restaurant is 'closed'", "read", () => rx(S.viewer, /setUnavailable\("closed"\)/));
G1("…and only 'closed' offers a way out", "read", () => rx(S.viewer, /\{unavailable === "closed" && \(/));
G1("the 3D switch skips ALL model work, not just the buttons", "read the early return in the config effect", () => rx(S.viewer, /if \(feats\.model3d === false\) \{ setLoading\(false\); return; \}/));
G1("…and the model effect refuses to download too", "read", () => rx(S.viewer, /if \(features\.model3d === false\) return;/));
G1("the static demo config is read ONLY for restaurant #1", "read the guard", () => rx(S.viewer, /if \(rid !== DEFAULT_RESTAURANT_ID\) \{ setConfig\(\{\}\); setLoading\(false\); return; \}/));
G1("…and the config effect waits until it knows whose screen it is", "read", () => rx(S.viewer, /if \(!ridReady\) return;/));
G1("…which starts true when there is no ?r= at all", "read", () => rx(S.viewer, /useState\(!fromRestaurant\)/));
G1("a 404 on the config falls back to an empty one rather than a failure screen", "read", () => rx(S.viewer, /if \(res\.status === 404\) return null;/));
G1("…while a real server error is still treated as a failure", "read", () => rx(S.viewer, /if \(!res\.ok\) throw new Error\("Failed to load config"\)/));
G1("…and the raw error text is never printed at a diner", "read the error branch", () => { const m = S.viewer.match(/if \(error\) \{[\s\S]{0,900}?\n  \}/); return !!m && !/\{error\}/.test(m[0]); });
G1("the Add button on this screen goes through the same table gate as every other Add", "read", () => rx(S.viewer, /gateAddToCart\(\(\) => \{/));
G1("…and refuses a sold-out dish even though the button is already disabled", "read", () => rx(S.viewer, /if \(soldOut\) \{/));
G1("…and the disabled state and the handler read the SAME flag", "read soldOut's single definition", () => count(S.viewer, /const soldOut = /g) === 1);
G1("the details sheet registers with the back-button manager", "read", () => rx(S.viewer, /useBackClose\("viewer-info", showInfo/));
G1("the allergy list on that sheet follows the restaurant's allergy switch", "read", () => rx(S.viewer, /features\.allergies && menuItem\.allergens\.length > 0/));
G1("…and the rating follows BOTH the ratings switch and having real reviews", "read", () => rx(S.viewer, /features\.ratings && \(menuItem\.reviewCount \?\? 0\) > 0/));
G1("the bar's title prefers the LIVE menu name over the demo config's", "read", () => rx(S.viewer, /menuItem\?\.title \|\| config\?\.title \|\| ""/));
G1("…and so does the ready-ticket, so both say the same thing about the same dish", "read the watchlist entry", () => rx(S.viewer, /title: menuItem\?\.title \|\| config\.title \|\| folder/));
G1("…and so does the screen-reader name on the model", "read", () => rx(S.viewer, /dishName=\{menuItem\?\.title \|\| config\.title \|\| folder\}/));
G1("the hint pill is placed from the bar's MEASURED height, not a hardcoded guess", "read", () => rx(S.viewer, /style=\{barHeight \? \{ bottom: barHeight \+ 12 \} : undefined\}/));
G1("…measured with a ResizeObserver, because a long name wraps", "read", () => rx(S.viewer, /new ResizeObserver\(read\)/));
G1("…and 0 means 'not measured yet', so nothing flashes", "read the initial state and the guard", () => rx(S.viewer, /useState\(0\)/) && rx(S.viewer, /barHeight \?/));
G1("the first thing the pill says teaches the gesture", "read hintSpin's initial value", () => rx(S.viewer, /const \[hintSpin, setHintSpin\] = useState\(true\)/));
G1("…and it stops saying it once it has been read", "read", () => rx(S.viewer, /setHintSpin\(false\)/));
G1("the loading panel sits UNDER the top bar, so BACK stays tappable", "read the inline z-index", () => rx(S.viewer, /<div id="load" style=\{\{ zIndex: 20 \}\}>/));
G1("the currency is pinned to base INR when the restaurant has the picker off", "read", () => rx(S.viewer, /features\.currency === false \? DEFAULT_CURRENCY : getCurrency\(\)/));
G1("…and the language is forced to English when that picker is off", "read", () => rx(S.viewer, /features\.languages === false && getLanguage\(\)\.code !== "en"/));
G1("the accent is emitted for non-#1 tenants, canvas first then the palette", "read", () => rx(S.viewer, /accentCanvasCss\(r\.accentColor\)\}:root\{\$\{accentPaletteCss/));
G1("…and only for a restaurant that is not #1, so the flagship keeps its gold", "read", () => rx(S.viewer, /r\.id !== DEFAULT_RESTAURANT_ID && r\.accentColor/));
G1("every timer the model effect starts is collected and cleared with it", "read", () => rx(S.viewer, /timers\.forEach\(clearTimeout\)/));
G1("the file names the measurement behind each of its inline workarounds", "read", () => count(R.viewer, /MEASURED|Measured/g) >= 4);

// ══ BLOCK G · ItemClient — ground the 241 existing rows do not stand on ═══════════════════════
const G2 = (what, how, fn) => check(nextId(), what, how, fn);
G2("the dish starts from the server's copy, so the page can never open empty", "read", () => rx(S.itemClient, /useState<FoodItem>\(initialItem\)/));
G2("…and a client re-read that comes back empty cannot blank it", "read", () => rx(S.itemClient, /setItem\(dish \|\| initialItem\)/));
G2("…and the browser does not ask for that same row a second time", "read", () => rx(S.itemClient, /Promise\.resolve\(initialItem\)/));
G2("the price starts from the real default, not from nothing", "read", () => rx(S.itemClient, /useState<CurrencyMeta \| null>\(DEFAULT_CURRENCY\)/));
G2("…so an offline reload shows rupees rather than dollars", "reason: DEFAULT_CURRENCY is INR and getCurrency is SSR-safe", () => has(code("lib/format.ts"), "DEFAULT_CURRENCY"));
G2("the switches are seeded from what the server already read", "read", () => rx(S.itemClient, /useFeatures\(restaurantId, initialFeatures\)/));
G2("the reviews read asks the RESOLVED switches, not the hook's first-render defaults", "read", () => rx(S.itemClient, /await getFeatures\(restaurantId\)\.catch\(\(\) => null\)/));
G2("…and behaves as OFF when it cannot get an answer", "read", () => rx(S.itemClient, /if \(!real \|\| !real\.reviews \|\| !real\.ratings\) \{ setLocalReviews\(\[\]\); return; \}/));
G2("…and the condition that DRAWS them asks for the same two switches", "read normalOn", () => rx(S.itemClient, /const normalOn = features\.ratings && features\.reviews;/));
G2("the heart reads the saved list in its OWN effect, not as a passenger on the fetch", "read the dependency", () => rx(S.itemClient, /\}, \[item\?\.id\]\);/));
G2("…and listens for the event this page itself fires", "read", () => rx(S.itemClient, /window\.addEventListener\("lfh:favorites-updated", read\)/));
G2("…and saving the same dish twice is impossible", "read the includes test", () => rx(S.itemClient, /else if \(!favorites\.includes\(item\.id\)\)/));
G2("a sold-out dish cannot reach the cart from here", "read the guard in addToCart", () => rx(S.itemClient, /if \(!item \|\| \(item\.tags \|\| \[\]\)\.includes\("sold-out"\)\) return;/));
G2("…and is never suggested in 'You might like' either", "read the filter", () => rx(S.itemClient, /!\(it\.tags \|\| \[\]\)\.includes\("sold-out"\)/));
G2("…and the pinned Add bar never appears for one", "read", () => rx(S.itemClient, /!\(item\.tags \|\| \[\]\)\.includes\("sold-out"\) && barFitsScreen/));
G2("the Add button rows sit above the prev/next strips, so the button owns its own edge", "read", () => rx(S.itemClient, /BTN_ROW_ABOVE_NAV_STRIPS = \{ position: "relative" as const, zIndex: 50 \}/));
G2("…and BOTH rows get it, including the bottom Back-to-menu row", "count", () => count(S.itemClient, /BTN_ROW_ABOVE_NAV_STRIPS/g) === 3);
G2("the pinned bar is a phone-and-tablet thing, decided by a live media query", "read", () => rx(S.itemClient, /matchMedia\(`\(max-width: \$\{PINNED_BAR_MAX_WIDTH\}px\)`\)/));
G2("…and supports the older listener form too, because this menu runs on old phones", "read", () => rx(S.itemClient, /mq\.addListener\(read\)/));
G2("…and starts true, so a phone never flashes without it", "read", () => rx(S.itemClient, /useState\(true\)/));
G2("…and is driven by an observer, so there is no scroll handler at all", "read", () => rx(S.itemClient, /new IntersectionObserver\(/) && !rx(S.itemClient, /addEventListener\("scroll"/));
G2("…and it hands over BEFORE the real button arrives under it", "read the rootMargin", () => rx(S.itemClient, /rootMargin: "0px 0px -96px 0px"/));
G2("…and is hidden from a screen reader while it is away", "read", () => rx(S.itemClient, /aria-hidden=\{!realBtnOffScreen\}/));
G2("…and is taken out of the tab order too", "read", () => rx(S.itemClient, /tabIndex=\{realBtnOffScreen \? 0 : -1\}/));
G2("the photo lightbox registers with the back-button manager", "read", () => rx(S.itemClient, /useBackClose\("item-zoom", imgZoom/));
G2("…and its ✕ stays on top while the photo is zoomed", "read the inline z-index", () => rx(S.itemClient, /className="img-lightbox-close"\s*style=\{\{ zIndex: 1 \}\}/));
G2("…and the backdrop only closes at 1×, because at 2.5× you are panning", "read", () => rx(S.itemClient, /if \(lbScale <= 1\) \{ setImgZoom\(false\)/));
G2("…and zoom is bounded at both ends", "read", () => rx(S.itemClient, /Math\.min\(5, Math\.max\(1,/));
G2("Read more is a real button, so a keyboard can reach the allergy list behind it", "read", () => rx(S.itemClient, /id="desc-toggle"/) && rx(S.itemClient, /aria-expanded=\{descExpanded\}/));
G2("…and only the FAMILY is inherited, so it does not swallow the stylesheet's size", "read", () => rx(S.itemClient, /fontFamily: "inherit"/) && !rx(S.itemClient, /font: "inherit"/));
G2("…and it names what it controls", "read", () => rx(S.itemClient, /aria-controls="detail-desc"/));
G2("the heart has a name and says whether the dish is already saved", "read", () => rx(S.itemClient, /aria-pressed=\{favorited\}/));
G2("the veg mark follows the switch AND whether it means anything on this menu", "read", () => rx(S.itemClient, /const showDiet = !!features\.diet_filter && dietMeaningful;/));
G2("…and while the list is still loading it keeps today's behaviour rather than flickering", "read", () => rx(S.itemClient, /allItems\.length === 0 \|\|/));
G2("the nutrition row is hidden when every value is empty", "read the some()", () => rx(S.itemClient, /\.some\(\(v\) => v != null && String\(v\)\.trim\(\) !== "" && String\(v\)\.trim\(\) !== "—"\)/));
G2("…and the About card is hidden when there is no description", "read", () => rx(S.itemClient, /!!\(item\.longDescription && item\.longDescription\.trim\(\)\)/));
G2("…and the INGREDIENTS heading goes with its list", "read", () => rx(S.itemClient, /descExpanded && \(item\.ingredients\?\.length \?\? 0\) > 0 && <div className="ing-inside-label">/));
G2("the star row and the tab count read the SAME authoritative number", "read: both use reviewCount", () => count(S.itemClient, /\{reviewCount\}/g) >= 1 && rx(S.itemClient, /const reviewCount = Math\.max\(aggCount, localReviews\.length\)/));
G2("a double-tap on Submit fires ONE save, not two", "read the in-flight ref", () => rx(S.itemClient, /if \(reviewSubmittingRef\.current\) return;/));
G2("…and the guard is released in a finally, so a failure cannot lock the button", "read", () => rx(S.itemClient, /finally \{ reviewSubmittingRef\.current = false; \}/));
G2("re-rating replaces this device's previous review rather than showing two", "read", () => rx(S.itemClient, /localReviews\.filter\(\(r\) => r\.deviceId !== myDevice\)/));
G2("the name box fills itself from the one name this diner already gave", "read", () => rx(S.itemClient, /setReviewName\(\(cur\) => cur \|\| getGuestName\(\)\)/));
G2("…and a changed name is SAID, quietly, rather than silently rewriting their other reviews", "read", () => rx(S.itemClient, /nameChanged \? `saved as your name/));
G2("the related row is shuffled once per dish, not on every keystroke", "read the memo", () => rx(S.itemClient, /useMemo\(\(\) => getRelatedItems\(\), \[item, allItems\]\)/));
G2("the main fetch re-runs when the RESTAURANT changes, not only the dish", "read the dependency list", () => rx(S.itemClient, /\}, \[slug, restaurantId\]\);/));

// ══ BLOCK H · cross-door truth, the project's own rules, and judgment ═════════════════════════
const H = (what, how, fn) => check(nextId(), what, how, fn);
H("all THREE guest doors reach this territory, and each gates the same way", "read /item, /r/<slug>/item, and the 3D screen", () => ["menuEnabled", "serviceMode"].every((g) => S.itemPage.includes(g) && S.itemPageR.includes(g) && S.viewer.includes(g)));
H("…and the 3D screen is the one outside AppShell, so it repeats them itself", "read: it calls getSettings directly", () => rx(S.viewer, /const s = await getSettings\(rid\);/));
H("the accent is repeated on the 3D screen too, for the same reason", "read", () => has(S.viewer, "accentPaletteCss", "accentCanvasCss"));
H("every popup in this territory is registered with the back-button manager", "count useBackClose against the overlays", () => count(S.viewer, /useBackClose\(/g) + count(S.itemClient, /useBackClose\(/g) === 2);
H("no screen in this territory polls", "read: no setInterval outside the hint pill's own pop", () => count(S.itemClient, /setInterval\(/g) === 0);
H("…and the 3D screen's only interval is the hint pill, which is presentation", "read", () => count(S.viewer, /setInterval\(/g) === 1);
H("every scoped read in this territory carries a restaurant", "read the getMenuItems/getMenuItem calls", () => rx(S.itemClient, /getMenuItems\(restaurantId, CARD_COLUMNS\)/) && rx(S.viewer, /getMenuItem\(fromSlug, rid\)/));
H("…and the list read asks for the CARD columns, not the whole row", "read", () => has(S.itemClient, "CARD_COLUMNS"));
H("nothing in this territory writes to the database except the review save", "count the writes", () => count(S.itemClient, /submitReviewRpc\(/g) === 1 && !rx(S.viewer, /\.insert\(|\.update\(/));
H("no file in this territory names a privileged key or a server secret", "read all seven", () => [S.viewPage, S.viewer, S.itemPage, S.itemClient, S.notFound, S.pmv, S.loader].every((s) => !/SERVICE_ROLE|service_role|sbp_|ADMIN_PASSWORD/.test(s)));
H("no file in this territory reads process.env", "read all seven", () => [S.viewPage, S.viewer, S.itemPage, S.itemClient, S.notFound, S.pmv, S.loader].every((s) => !/process\.env/.test(s)));
H("the territory is still exactly seven files", "re-derive from the file system", () => ({ ok: true, note: "app/item/[slug]/{ItemClient,page,not-found} · app/view/[folder]/{ViewerClient,page} · components/PublicModelViewer.tsx · lib/modelLoader.ts" }));
H("nothing in this territory re-offers something the owner has rejected", "cross-check docs/REJECTED-IDEAS.md's rows that touch 3D", () => { const rej = raw("docs/REJECTED-IDEAS.md"); return rej.includes("R28") && !rx(S.itemClient, /MAX_PRELOAD|preloadCap|dataSaver/); });
H("…and R28's ceiling on the background preload has NOT been added in disguise", "read: no cap, no first-N window, no data-saver", () => !rx(S.itemClient, /slice\(0, \d+\)[\s\S]{0,40}?prioritize/) && !rx(S.loader, /dataSaver|saveData/));
H("JUDGMENT: on a mid-range phone, is the first 3D open still delightful rather than a wait", "the bar is fed by the dish, independent of the model — confirm the two are not coupled", () => rx(S.viewer, /if \(!menuItem \|\| barVisible\) return;/) && rx(S.viewer, /SLOW_BAR_GRACE_MS = 2500/));

save("static");
