// build-vendor.mjs — builds BOTH self-hosted third-party files the panels load:
//
//   public/vendor/supabase.js              ← @supabase/supabase-js  (realtime, ESM)
//   public/panels/vendor/chart.umd.min.js  ← chart.js               (Dashboard graphs, UMD)
//
// It bundles the pinned @supabase/supabase-js into a SINGLE self-hosted ESM file, so the
// static staff panels (kitchen/tablet/manager) import realtime from OUR origin instead of the
// public jsdelivr CDN at runtime.
//
// THE CHART FILE USED TO BE COPIED IN BY HAND (T9 sweep, 2026-08-17). It was a minified build
// downloaded from jsdelivr, committed, and labelled `?v=4.4.7` — a version somebody TYPED. chart.js
// was not a dependency, so nothing anywhere could tell you whether that label was still true, and
// nothing could rebuild the file. Now chart.js is a pinned exact devDependency and this script
// produces the file from it, so the version is a fact instead of a note, and both vendored files
// are refreshed by the same one command. The banner names the version it was built from, and
// scripts/verify-panel-plumbing.mjs fails if that banner and package.json ever disagree.
//
// WHY: relying on an external CDN at runtime is a liability for a product we sell —
// a restaurant's wifi can be slow or block jsdelivr, which made the panel hang or
// silently drop to slow polling. A same-origin file removes that whole class of
// failure and loads faster. The version is whatever package.json has installed, so
// the bundle stays in lock-step with the npm dep the rest of the app uses.
//
// RE-RUN THIS after bumping @supabase/supabase-js:  npm run build:vendor
// (The output IS committed so deploys don't depend on this step running.)

import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outfile = resolve(root, "public/vendor/supabase.js");
mkdirSync(resolve(root, "public/vendor"), { recursive: true });

await build({
  entryPoints: [resolve(root, "node_modules/@supabase/supabase-js/dist/index.mjs")],
  bundle: true,
  format: "esm",        // panels import it with a dynamic `import()`
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "none",
  outfile,
});

console.log("✓ wrote", outfile);

// ── chart.js, for the manager Dashboard's graphs ───────────────────────────────────────────────
// MINIFY THEIR UMD FILE — DO NOT RE-BUNDLE IT. This is the whole trick, and getting it wrong is
// visible immediately: chart.js's dist/chart.umd.js is already a self-contained UMD bundle that
// assigns the Chart CLASS to `window.Chart`, and the manager panel is written against exactly that
// (`new Chart(...)`, `Chart.register(...)`) because these panels are static files with no build
// step of their own. Running esbuild with `bundle: true` on a UMD file wraps it in ANOTHER module
// scope, so its `this`-based global assignment never reaches `window` — measured: `window.Chart`
// undefined and every graph on the Dashboard blank.
//
// So: `bundle: false`, which makes this a pure minify of the vendor's own bundle. That is precisely
// what jsdelivr's `.min.js` is, i.e. what the hand-copied file was — same code, same UMD wrapper,
// just smaller. `target: es2015` keeps it runnable on the oldest tablet in the building.
const chartOut = resolve(root, "public/panels/vendor/chart.umd.min.js");
const chartVersion = JSON.parse(
  readFileSync(resolve(root, "node_modules/chart.js/package.json"), "utf8"),
).version;
mkdirSync(resolve(root, "public/panels/vendor"), { recursive: true });

await build({
  entryPoints: [resolve(root, "node_modules/chart.js/dist/chart.umd.js")],
  bundle: false,        // see the note above — bundling a UMD file breaks its global
  platform: "browser",
  target: "es2015",
  minify: true,
  legalComments: "none",
  outfile: chartOut,
});

// The banner is what verify-panel-plumbing.mjs reads to prove this file was built from the version
// package.json pins — the thing the hand-typed `?v=` label could never prove.
writeFileSync(
  chartOut,
  `/*! chart.js v${chartVersion} — generated by scripts/build-vendor.mjs, do not edit by hand */\n`
  + readFileSync(chartOut, "utf8"),
);
console.log(`✓ wrote ${chartOut}  (chart.js v${chartVersion})`);
